// frontend/app/taro/src/pages/[locale]/about/index.tsx
'use client';

import {useTranslation} from 'react-i18next';
import {View, Text, Image} from '@tarojs/components';

import '../../globals.css'; // 导入全局 CSS，确保 CSS 变量可用
import styles from './about.scss';

export default function AboutPage() {
  const {t} = useTranslation('page.about');

  const features = [
    {
      icon: 'carbon:document-add',
      title: t('feature_content'),
      description: t('feature_content_desc'),
    },
    {
      icon: 'carbon:cloud-upload',
      title: t('feature_multi_tenant'),
      description: t('feature_multi_tenant_desc'),
    },
    {
      icon: 'carbon:security',
      title: t('feature_security'),
      description: t('feature_security_desc'),
    },
    {
      icon: 'carbon:api',
      title: t('feature_api'),
      description: t('feature_api_desc'),
    },
    {
      icon: 'carbon:collaborate',
      title: t('feature_collaboration'),
      description: t('feature_collaboration_desc'),
    },
    {
      icon: 'carbon:analytics',
      title: t('feature_analytics'),
      description: t('feature_analytics_desc'),
    },
  ];

  const teamMembers = [
    {
      name: t('team_member_1'),
      role: t('team_role_1'),
      avatar: '/logo.png',
    },
    {
      name: t('team_member_2'),
      role: t('team_role_2'),
      avatar: '/logo.png',
    },
    {
      name: t('team_member_3'),
      role: t('team_role_3'),
      avatar: '/logo.png',
    },
  ];

  return (
    <View className={styles.aboutPage}>
      {/* Hero Section */}
      <View className={styles.hero}>
        <View className={styles.heroContent}>
          <Text className={styles.heroTitle}>{t('title')}</Text>
          <Text className={styles.heroSubtitle}>{t('subtitle')}</Text>
          <Text className={styles.heroDescription}>{t('description')}</Text>
        </View>
      </View>

      {/* About Section */}
      <View className={styles.aboutSection}>
        <View className={styles.sectionContainer}>
          <View className={styles.aboutContent}>
            <Text>{t('about_us')}</Text>
            <Text>{t('about_us_desc_1')}</Text>
            <Text>{t('about_us_desc_2')}</Text>
            <Text>{t('about_us_desc_3')}</Text>
          </View>
          <View className={styles.aboutStats}>
            <View className={styles.statCard}>
              <Text className={styles.statNumber}>10K+</Text>
              <Text className={styles.statLabel}>{t('stat_users')}</Text>
            </View>
            <View className={styles.statCard}>
              <Text className={styles.statNumber}>500+</Text>
              <Text className={styles.statLabel}>{t('stat_projects')}</Text>
            </View>
            <View className={styles.statCard}>
              <Text className={styles.statNumber}>99.9%</Text>
              <Text className={styles.statLabel}>{t('stat_uptime')}</Text>
            </View>
            <View className={styles.statCard}>
              <Text className={styles.statNumber}>24/7</Text>
              <Text className={styles.statLabel}>{t('stat_support')}</Text>
            </View>
          </View>
        </View>
      </View>

      {/* Features Section */}
      <View className={styles.featuresSection}>
        <View className={styles.sectionContainer}>
          <View className={styles.sectionHeader}>
            <Text>{t('features')}</Text>
            <Text>{t('features_desc')}</Text>
          </View>
          <View className={styles.featuresGrid}>
            {features.map((feature) => (
              <View key={feature.title} className={styles.featureCard}>
                <View className={styles.featureIcon}>
                  <Text>{feature.icon}</Text>
                </View>
                <Text>{feature.title}</Text>
                <Text>{feature.description}</Text>
              </View>
            ))}
          </View>
        </View>
      </View>

      {/* Team Section */}
      <View className={styles.teamSection}>
        <View className={styles.sectionContainer}>
          <View className={styles.sectionHeader}>
            <Text>{t('team')}</Text>
            <Text>{t('team_desc')}</Text>
          </View>
          <View className={styles.teamGrid}>
            {teamMembers.map((member) => (
              <View key={member.name} className={styles.teamCard}>
                <View className={styles.teamAvatar}>
                  <Image
                    src={member.avatar}
                    style={{width: 120, height: 120}}
                  />
                </View>
                <Text>{member.name}</Text>
                <Text>{member.role}</Text>
              </View>
            ))}
          </View>
        </View>
      </View>

      {/* Values Section */}
      <View className={styles.valuesSection}>
        <View className={styles.sectionContainer}>
          <View className={styles.sectionHeader}>
            <Text>{t('values')}</Text>
            <Text>{t('values_desc')}</Text>
          </View>
          <View className={styles.valuesGrid}>
            <View className={styles.valueCard}>
              <Text>{t('value_innovation')}</Text>
              <Text>{t('value_innovation_desc')}</Text>
            </View>
            <View className={styles.valueCard}>
              <Text>{t('value_reliability')}</Text>
              <Text>{t('value_reliability_desc')}</Text>
            </View>
            <View className={styles.valueCard}>
              <Text>{t('value_customer')}</Text>
              <Text>{t('value_customer_desc')}</Text>
            </View>
          </View>
        </View>
      </View>

      {/* CTA Section */}
      <View className={styles.ctaSection}>
        <View className={styles.sectionContainer}>
          <Text>{t('cta_title')}</Text>
          <Text>{t('cta_desc')}</Text>
          <View className={styles.ctaButtons}>
            <View className={styles.buttonPrimary}>
              <Text>{t('cta_explore')}</Text>
            </View>
            <View className={styles.buttonDefault}>
              <Text>{t('cta_contact')}</Text>
            </View>
          </View>
        </View>
      </View>
    </View>
  );
}

// frontend/app/vue/app/pages/about.vue
<script setup lang="ts">
const { t } = useI18n()
</script>

<template>
  <div class="w-full">
    <LayoutPageHero
      :title="t('page.about.title')"
      :subtitle="t('page.about.subtitle')"
      :description="t('page.about.description')"
      icon="carbon:information"
      :icon-size="56"
      size="lg"
    />

    <!-- About Section -->
    <section class="w-full bg-background py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="grid grid-cols-1 gap-12 lg:grid-cols-2 lg:gap-16">
          <div class="antialiased">
            <h2 class="mb-6 text-3xl font-bold text-foreground">{{ t('page.about.about_us') }}</h2>
            <p class="mb-4 text-[15px] leading-loose tracking-normal text-muted-foreground">{{ t('page.about.about_us_desc_1') }}</p>
            <p class="mb-4 text-[15px] leading-loose tracking-normal text-muted-foreground">{{ t('page.about.about_us_desc_2') }}</p>
            <p class="text-[15px] leading-loose tracking-normal text-muted-foreground">{{ t('page.about.about_us_desc_3') }}</p>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div v-for="stat in [
              { num: '10K+', label: t('page.about.stat_users') },
              { num: '500+', label: t('page.about.stat_projects') },
              { num: '99.9%', label: t('page.about.stat_uptime') },
              { num: '24/7', label: t('page.about.stat_support') },
            ]" :key="stat.label" class="rounded-xl border border-border bg-card p-6 text-center shadow-sm">
              <div class="mb-3 text-3xl font-bold text-primary">{{ stat.num }}</div>
              <div class="text-[15px] font-medium text-muted-foreground">{{ stat.label }}</div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Features -->
    <section class="w-full bg-muted/30 py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mb-12 text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.features') }}</h2>
          <p class="text-muted-foreground">{{ t('page.about.features_desc') }}</p>
        </div>
        <div class="grid grid-cols-[repeat(auto-fit,minmax(280px,1fr))] gap-6">
          <div
            v-for="feature in [
              { icon: 'carbon:document-add', title: t('page.about.feature_content'), description: t('page.about.feature_content_desc') },
              { icon: 'carbon:cloud-upload', title: t('page.about.feature_multi_tenant'), description: t('page.about.feature_multi_tenant_desc') },
              { icon: 'carbon:security', title: t('page.about.feature_security'), description: t('page.about.feature_security_desc') },
              { icon: 'carbon:api', title: t('page.about.feature_api'), description: t('page.about.feature_api_desc') },
              { icon: 'carbon:collaborate', title: t('page.about.feature_collaboration'), description: t('page.about.feature_collaboration_desc') },
              { icon: 'carbon:analytics', title: t('page.about.feature_analytics'), description: t('page.about.feature_analytics_desc') },
            ]"
            :key="feature.title"
            class="group rounded-xl border border-border bg-card p-8 text-center shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-primary/40 hover:shadow-lg"
          >
            <div class="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-xl bg-primary/10 text-primary transition-all duration-300 group-hover:bg-primary group-hover:text-white group-hover:shadow-md">
              <XIcon :icon="feature.icon" :size="32" />
            </div>
            <h3 class="mb-2 text-lg font-bold text-foreground transition-colors group-hover:text-primary">{{ feature.title }}</h3>
            <p class="text-sm leading-relaxed text-muted-foreground">{{ feature.description }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Team -->
    <section class="w-full bg-background py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mb-12 text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.team') }}</h2>
          <p class="text-muted-foreground">{{ t('page.about.team_desc') }}</p>
        </div>
        <div class="grid grid-cols-[repeat(auto-fit,minmax(250px,1fr))] gap-6">
          <div
            v-for="member in [
              { name: t('page.about.team_member_1'), role: t('page.about.team_role_1'), avatar: '/logo.png' },
              { name: t('page.about.team_member_2'), role: t('page.about.team_role_2'), avatar: '/logo.png' },
              { name: t('page.about.team_member_3'), role: t('page.about.team_role_3'), avatar: '/logo.png' },
            ]"
            :key="member.name"
            class="rounded-xl border border-border bg-card p-8 text-center shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
          >
            <div class="mx-auto mb-4 h-[120px] w-[120px] overflow-hidden rounded-full ring-2 ring-primary/20">
              <img :src="member.avatar" :alt="member.name" width="120" height="120" />
            </div>
            <h3 class="mb-2 text-lg font-bold text-foreground">{{ member.name }}</h3>
            <p class="text-xs text-muted-foreground/80">{{ member.role }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Values -->
    <section class="w-full bg-muted/30 py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mb-12 text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.values') }}</h2>
          <p class="text-muted-foreground">{{ t('page.about.values_desc') }}</p>
        </div>
        <div class="grid grid-cols-1 gap-6 md:grid-cols-3">
          <div
            v-for="value in [
              { title: t('page.about.value_innovation'), desc: t('page.about.value_innovation_desc') },
              { title: t('page.about.value_reliability'), desc: t('page.about.value_reliability_desc') },
              { title: t('page.about.value_customer'), desc: t('page.about.value_customer_desc') },
            ]"
            :key="value.title"
            class="rounded-xl border border-border bg-card p-8 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
          >
            <h3 class="mb-3 text-xl font-bold text-primary">{{ value.title }}</h3>
            <p class="text-sm leading-relaxed text-muted-foreground mt-2">{{ value.desc }}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA -->
    <section class="w-full bg-primary/5 py-20">
      <div class="w-full max-w-[1200px] mx-auto px-8 max-md:px-4">
        <div class="mx-auto max-w-[800px] text-center">
          <h2 class="mb-4 text-3xl font-bold text-foreground">{{ t('page.about.cta_title') }}</h2>
          <p class="mb-8 text-lg text-muted-foreground">{{ t('page.about.cta_desc') }}</p>
          <div class="flex flex-wrap justify-center gap-4">
            <UiButton size="lg" class="rounded-lg px-6 py-2.5 font-medium">{{ t('page.about.cta_explore') }}</UiButton>
            <UiButton variant="outline" size="lg" class="rounded-lg px-6 py-2.5 font-medium">{{ t('page.about.cta_contact') }}</UiButton>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>
