// frontend/app/react/src/app/[locale]/disclaimer/page.tsx
'use client';

import {useTranslations} from 'next-intl';
import PageHero from '@/components/layout/PageHero';

export default function DisclaimerPage() {
    const t = useTranslations('page.legal.disclaimer');

    return (
        <div className="w-full">
            <PageHero
                title={t('title')}
                description={t('description')}
                icon="carbon:warning"
                size="sm"
            />

            {/* Content Section */}
            <div className="w-full my-12 max-w-3xl rounded-xl border border-border bg-card p-8 shadow-sm max-md:mx-4 max-md:p-6">
                <ul className="space-y-4 text-foreground">
                    <li className="flex items-start gap-3">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary"/>
                        <span>{t('item_1')}</span>
                    </li>
                    <li className="flex items-start gap-3">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary"/>
                        <span>{t('item_2')}</span>
                    </li>
                    <li className="flex items-start gap-3">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-primary"/>
                        <span>{t('item_3')}</span>
                    </li>
                </ul>
            </div>
        </div>
    );
}

// frontend/app/vue/app/pages/disclaimer.vue
<script setup lang="ts">
const { t } = useI18n()
</script>

<template>
  <LayoutLegalPage
    icon="carbon:warning"
    :title="t('page.legal.disclaimer.title')"
    :description="t('page.legal.disclaimer.description')"
    :items="[t('page.legal.disclaimer.item_1'), t('page.legal.disclaimer.item_2'), t('page.legal.disclaimer.item_3')]"
  />
</template>
