// frontend/app/taro/src/components/layout/Header/index.tsx
import {useState, useEffect} from 'react';
import {useTranslation} from 'react-i18next';
import {View, Text, Image} from '@tarojs/components';

import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';
import XIcon from '@/plugins/xicon';

import {useAccessStore} from "@/store/core/access/store";
import {usePreferences} from '@/core/preferences/hooks/usePreferences';

import TopNavbar from '../TopNavbar';

import './index.scss';


export default function Header() {
  const {t} = useTranslation();

  const preferences = usePreferences();
  const router = useI18nRouter();
  const accessStore = useAccessStore();

  const accessToken = accessStore.accessToken;
  const isLogin = !!accessToken && !accessStore.loginExpired;

  // 下拉菜单状态
  const [openDropdown, setOpenDropdown] = useState<'user' | 'language' | 'theme' | null>(null);

  const handleClickLogo = () => {
    router.push('pages/index');
  };
  const handleClickSettings = () => {
    router.push('/settings');
  };
  const handleClickUserHomepage = () => {
    router.push('/user');
  };
  const handleClickLogin = () => {
    router.push('/login');
  };
  const handleClickRegister = () => {
    router.push('/register');
  };
  const handleClickLogout = async () => {
    console.log('Logout');

    if (isLogin) {
      // TODO: 调用登出API
      accessStore.clearTokens();
    }
    setOpenDropdown(null);
  };

  // 切换下拉菜单
  const toggleDropdown = (type: 'user' | 'language' | 'theme') => {
    setOpenDropdown(openDropdown === type ? null : type);
  };

  // 关闭所有下拉菜单
  const closeAllDropdowns = () => {
    setOpenDropdown(null);
  };

  // 根据登录状态动态生成用户菜单项
  const userMenuItems = isLogin
    ? [
      {
        key: 'homepage',
        label: t('menu.homepage'),
        icon: 'carbon:home',
        onClick: handleClickUserHomepage
      },
      {
        key: 'profile',
        label: t('menu.my_profile'),
        icon: 'carbon:user',
        onClick: handleClickSettings
      },
      {
        type: 'divider' as const
      },
      {
        key: 'logout',
        label: t('menu.logout'),
        icon: 'carbon:logout',
        danger: true,
        onClick: handleClickLogout
      },
    ]
    : [
      {
        key: 'login',
        label: t('navbar.user.login'),
        icon: 'carbon:user',
        onClick: handleClickLogin
      },
      {
        key: 'register',
        label: t('navbar.user.register'),
        icon: 'carbon:user',
        onClick: handleClickRegister
      }
    ];

  // 语言菜单
  const languageMenuItems = [
    {
      key: 'zh-CN',
      label: '简体中文',
      onClick: () => preferences.setLanguage('zh-CN')
    },
    {
      key: 'en-US',
      label: 'English',
      onClick: () => preferences.setLanguage('en-US')
    }
  ];

  const themeMenuItems = [
    {
      key: 'dark',
      label: t('navbar.theme.dark'),
      icon: 'carbon:moon',
      onClick: () => preferences.setThemeMode('dark')
    },
    {
      key: 'light',
      label: t('navbar.theme.light'),
      icon: 'carbon:sun',
      onClick: () => preferences.setThemeMode('light')
    },
    {
      key: 'auto',
      label: t('navbar.theme.system'),
      icon: 'carbon:ibm-watsonx-orchestrate',
      onClick: () => preferences.setThemeMode('auto')
    },
  ];

  const themeIconMap: Record<string, string> = {
    dark: 'carbon:moon',
    light: 'carbon:sun',
    auto: 'carbon:ibm-watsonx-orchestrate'
  };

  const validMode = ['dark', 'light', 'auto'].includes(preferences.theme.mode)
    ? preferences.theme.mode
    : 'auto';
  const iconValue = themeIconMap[validMode];

  // SSR 兼容
  const [mounted, setMounted] = useState(false);
  useEffect(() => {
    setMounted(true);
  }, []);

  const displayIcon = mounted ? iconValue : 'carbon:ibm-watsonx-orchestrate';

  return (
    <View className='fixed-top'>
      <View className='header-inner'>
        <View className='top-bar'>
          {/* Logo + 导航区 */}
          <View className='logo-nav-section'>
            <View
              className='logo-section'
              role='button'
              aria-label='Go to homepage'
              onClick={handleClickLogo}
            >
              <Image
                src='/assets/images/logo.png'
                className='logo'
              />
              <Text className='site-name'>{t('app.title')}</Text>
            </View>
            {/* 主导航菜单 */}
            <View className='navbar-menu-wrap'>
              <TopNavbar />
            </View>
          </View>
          {/* 功能按钮区 */}
          <View className='actions'>
            <View className='space'>
              {/* 用户菜单 */}
              <View className='dropdown-wrapper'>
                <View
                  className='icon-btn'
                  role='button'
                  aria-label='User menu'
                  onClick={() => toggleDropdown('user')}
                >
                  <XIcon name='carbon:user' size={24} />
                </View>
                {openDropdown === 'user' && (
                  <View className='dropdown-menu'>
                    {userMenuItems.map((item) => (
                      <View
                        key={item.key}
                        className={`dropdown-item ${item.danger ? 'danger' : ''}`}
                        onClick={() => {
                          if (item.onClick) item.onClick();
                          closeAllDropdowns();
                        }}
                      >
                        {item.icon && (
                          <XIcon name={item.icon} size={18} className='dropdown-item-icon' />
                        )}
                        <Text className='dropdown-item-label'>{item.label}</Text>
                      </View>
                    ))}
                  </View>
                )}
              </View>
              {/* 语言菜单 */}
              <View className='dropdown-wrapper'>
                <View
                  className='icon-btn'
                  role='button'
                  aria-label='Language'
                  onClick={() => toggleDropdown('language')}
                >
                  <XIcon name='carbon:language' size={24} className='lang-icon' />
                </View>
                {openDropdown === 'language' && (
                  <View className='dropdown-menu'>
                    {languageMenuItems.map((item) => (
                      <View
                        key={item.key}
                        className='dropdown-item'
                        onClick={() => {
                          if (item.onClick) {
                            item.onClick();
                          }
                          closeAllDropdowns();
                        }}
                      >
                        <Text className='dropdown-item-label'>{item.label}</Text>
                      </View>
                    ))}
                  </View>
                )}
              </View>
              {/* 主题菜单 */}
              <View className='dropdown-wrapper'>
                <View
                  className='icon-btn'
                  role='button'
                  aria-label='Toggle theme'
                  onClick={() => toggleDropdown('theme')}
                >
                  <XIcon name={displayIcon} size={24} className='theme-icon' />
                </View>
                {openDropdown === 'theme' && (
                  <View className='dropdown-menu'>
                    {themeMenuItems.map((item) => (
                      <View
                        key={item.key}
                        className='dropdown-item'
                        onClick={() => {
                          item.onClick();
                          closeAllDropdowns();
                        }}
                      >
                        {item.icon && (
                          <XIcon name={item.icon} size={18} className='dropdown-item-icon' />
                        )}
                        <Text className='dropdown-item-label'>{item.label}</Text>
                      </View>
                    ))}
                  </View>
                )}
              </View>
            </View>
          </View>
        </View>
      </View>
    </View>
  );
}

// frontend/app/vue/app/components/layout/Header.vue
<script setup lang="ts">
import { XIcon } from '@/plugins/xicon'
import { usePreferences } from '@/core/preferences/use-preferences'
import { useAccessStore } from '@/stores/modules/core/access.state'
import { useAuthStore } from '@/stores/modules/app/auth.state'

const { t } = useI18n()
const { theme: themePref, setThemeMode } = usePreferences()
const currentMode = computed(() => themePref.value.mode)

const localePath = useLocalePath()
const switchLocalePath = useSwitchLocalePath()
const accessStore = useAccessStore()
const authStore = useAuthStore()

const isLogin = computed(() => {
  const token = accessStore.accessToken
  return !!token?.value && !accessStore.loginExpired
})

const handleClickLogo = () => navigateTo(localePath('/'))
const handleClickSettings = () => navigateTo(localePath('/settings'))
const handleClickUserHomepage = () => navigateTo(localePath('/user'))
const handleClickLogin = () => navigateTo(localePath('/login'))
const handleClickRegister = () => navigateTo(localePath('/register'))
const handleClickLogout = async () => {
  if (isLogin.value) await authStore.logout()
}
</script>

<template>
  <header class="fixed top-0 left-0 right-0 z-1000 flex justify-center bg-background/80 backdrop-blur-md border-b border-border/50 dark:border-border/30 dark:bg-background/60">
    <div class="flex h-(--layout-header-height) w-full max-w-300 items-center gap-6 px-4 max-md:gap-3 max-md:px-3">
      <!-- Logo -->
      <button
        type="button"
        class="flex shrink-0 items-center gap-2 rounded-lg p-1 transition-colors hover:bg-primary/10"
        aria-label="Go to homepage"
        @click="handleClickLogo"
      >
        <img src="/logo.png" alt="Logo" width="36" height="36" class="h-9 w-9 shrink-0 max-md:h-8 max-md:w-8" />
        <span class="text-lg font-bold text-primary whitespace-nowrap max-md:hidden">
          {{ t('app.title') }}
        </span>
      </button>

      <!-- 桌面端导航区 -->
      <div class="min-w-0 flex-1 max-md:hidden">
        <LayoutTopNavbar />
      </div>

      <!-- 桌面端功能按钮区 -->
      <div class="flex shrink-0 items-center gap-1 max-md:hidden">
        <!-- 用户菜单 -->
        <UiDropdownMenu>
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="User menu">
              <XIcon icon="lucide:user" width="16" height="16" />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <template v-if="isLogin">
              <UiDropdownMenuItem @click="handleClickUserHomepage">
                <XIcon icon="lucide:home" width="16" height="16" />
                {{ t('menu.homepage') }}
              </UiDropdownMenuItem>
              <UiDropdownMenuItem @click="handleClickSettings">
                <XIcon icon="lucide:user" width="16" height="16" />
                {{ t('menu.my_profile') }}
              </UiDropdownMenuItem>
              <UiDropdownMenuSeparator />
              <UiDropdownMenuItem class="text-destructive" @click="handleClickLogout">
                <XIcon icon="lucide:log-out" width="16" height="16" />
                {{ t('menu.logout') }}
              </UiDropdownMenuItem>
            </template>
            <template v-else>
              <UiDropdownMenuItem @click="handleClickLogin">
                <XIcon icon="lucide:user" width="16" height="16" />
                {{ t('navbar.user.login') }}
              </UiDropdownMenuItem>
              <UiDropdownMenuItem @click="handleClickRegister">
                <XIcon icon="lucide:user" width="16" height="16" />
                {{ t('navbar.user.register') }}
              </UiDropdownMenuItem>
            </template>
          </UiDropdownMenuContent>
        </UiDropdownMenu>

        <!-- 语言菜单 -->
        <UiDropdownMenu>
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="Language">
              <XIcon icon="lucide:globe" width="16" height="16" />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <UiDropdownMenuItem @click="switchLocalePath('zh')">
              简体中文
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="switchLocalePath('en')">
              English
            </UiDropdownMenuItem>
          </UiDropdownMenuContent>
        </UiDropdownMenu>

        <!-- 主题菜单 -->
        <UiDropdownMenu>
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="Toggle theme">
              <XIcon                 :icon="currentMode === 'dark' ? 'lucide:moon' : currentMode === 'light' ? 'lucide:sun' : 'lucide:monitor'"
                width="16" height="16"
                class="theme-icon-animate"
              />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <UiDropdownMenuItem @click="setThemeMode('dark')">
              <XIcon icon="lucide:moon" width="16" height="16" />
              {{ t('navbar.theme.dark') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('light')">
              <XIcon icon="lucide:sun" width="16" height="16" />
              {{ t('navbar.theme.light') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('auto')">
              <XIcon icon="lucide:monitor" width="16" height="16" />
              {{ t('navbar.theme.system') }}
            </UiDropdownMenuItem>
          </UiDropdownMenuContent>
        </UiDropdownMenu>
      </div>

      <!-- 手机端：主题切换 + 汉堡选单 -->
      <div class="flex shrink-0 items-center gap-1 md:hidden">
        <UiDropdownMenu>
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="Toggle theme">
              <XIcon                 :icon="currentMode === 'dark' ? 'lucide:moon' : currentMode === 'light' ? 'lucide:sun' : 'lucide:monitor'"
                width="16" height="16"
                class="theme-icon-animate"
              />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <UiDropdownMenuItem @click="setThemeMode('dark')">
              <XIcon icon="lucide:moon" width="16" height="16" />
              {{ t('navbar.theme.dark') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('light')">
              <XIcon icon="lucide:sun" width="16" height="16" />
              {{ t('navbar.theme.light') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('auto')">
              <XIcon icon="lucide:monitor" width="16" height="16" />
              {{ t('navbar.theme.system') }}
            </UiDropdownMenuItem>
          </UiDropdownMenuContent>
        </UiDropdownMenu>

        <!-- 汉堡选单 -->
        <LayoutMobileNav />
      </div>
    </div>
  </header>
</template>
