// frontend/app/taro/src/components/layout/TopNavbar.tsx
import {View, Text} from '@tarojs/components';

import {useState, useEffect, useRef} from 'react';

import {XIcon} from '@/plugins/xicon';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';
import {fetchListNavigations} from '@/api/hooks/navigation';
import {useLanguageChangeEffect} from '@/hooks/useLanguageChangeEffect';
import {usePreferences} from '@/core/preferences';
import {cn} from '@/lib/utils';
import {Skeleton} from '@/components/ui/skeleton';

import type {siteservicev1_Navigation, siteservicev1_NavigationItem} from '@/api/generated/app/service/v1';



export interface TopNavbarItem {
    key: string;
    label: string;
    icon?: string;
    children?: TopNavbarItem[];
}

interface TopNavbarProps {
    items?: TopNavbarItem[];
    onClick?: (key: number) => void;
}

export default function TopNavbar({onClick}: TopNavbarProps) {
    const router = useI18nRouter();
    const [navigationItems, setNavigationItems] = useState<siteservicev1_NavigationItem[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const [openMenuId, setOpenMenuId] = useState<number | null>(null);
    const closeTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    const loadNav = async () => {
        try {
            setIsLoading(true);
            const res = await fetchListNavigations({
                paging: {page: 1, pageSize: 10}
            }) as unknown as { items: siteservicev1_Navigation[]; total: number };

            if (res.items?.length) {
                const headerNav = res.items.find(nav =>
                    nav.location === 'HEADER' && nav.isActive === true
                );
                const items = headerNav?.items;
                if (items && items.length > 0) {
                    setNavigationItems(items);
                }
            }
        } catch (error) {
            console.error('[TopNavbar] 加载导航失败:', error);
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        loadNav();

    }, []);

    useLanguageChangeEffect(() => {
        setIsLoading(true);
        fetchListNavigations({paging: {page: 1, pageSize: 10}})
            .then(res => {
                const navRes = res as unknown as { items: siteservicev1_Navigation[]; total: number };
                if (navRes.items?.length) {
                    const headerNav = navRes.items.find(nav =>
                        nav.location === 'HEADER' && nav.isActive === true
                    );
                    const items = headerNav?.items;
                    if (items && items.length > 0) {
                        setNavigationItems(items);
                    }
                }
            })
            .catch(error => console.error('[TopNavbar] 重新加载导航失败:', error))
            .finally(() => setIsLoading(false));
    }, {immediate: false, autoCleanup: true});

    // 清理定时器
    useEffect(() => {
        return () => {
            if (closeTimerRef.current) clearTimeout(closeTimerRef.current);
        };
    }, []);

    const handleNavigate = (item: siteservicev1_NavigationItem) => {
        if (item.url != null) {
            router.push(item.url);
        }
    };

    const handleMouseEnter = (id: number) => {
        if (closeTimerRef.current) {
            clearTimeout(closeTimerRef.current);
            closeTimerRef.current = null;
        }
        setOpenMenuId(id);
    };

    const handleMouseLeave = () => {
        closeTimerRef.current = setTimeout(() => setOpenMenuId(null), 150);
    };

    usePreferences(); // keep theme reactivity

    if (isLoading) {
        return (
            <View className='flex h-full items-center gap-2'>
                {Array.from({length: 5}).map((_, i) => (
                    <Skeleton key={i} className='h-7 w-16 rounded-lg' />
                ))}
            </View>
        );
    }

    if (navigationItems.length === 0) {
        return null;
    }

    return (
        <View className='flex h-full items-center gap-0.5'>
            {navigationItems.map((item) => {
                const itemId = item.id ?? 0;
                const hasChildren = (item.children?.length ?? 0) > 0;
                const isOpen = openMenuId === itemId;

                return (
                    <View
                      key={itemId}
                      className='relative'
                      onClick={() => handleMouseEnter(itemId)}
                    >
                        <View
                          className={cn(
                                'inline-flex h-9 items-center gap-1.5 rounded-lg px-3 text-sm font-medium',
                                'text-foreground/80 transition-all duration-200',
                                'hover:bg-primary/10 hover:text-primary',
                                hasChildren && isOpen && 'bg-primary/10 text-primary',
                                'max-md:px-2',
                            )}
                          onClick={() => {
                                if (!hasChildren) {
                                    handleNavigate(item);
                                    onClick?.(Number(itemId));
                                }
                            }}
                        >
                            {item.icon && <XIcon name={`carbon:${item.icon}`} size={16} />}
                            <Text className='whitespace-nowrap'>{item.title}</Text>
                            {hasChildren && (
                                <XIcon name='carbon:chevron-down' size={12} className={cn('transition-transform duration-200', isOpen && 'rotate-180')} />
                            )}
                        </View>

                        {hasChildren && isOpen && (
                            <View
                              className={cn(
                                    'absolute left-0 top-full z-1001 mt-1.5',
                                    'min-w-50 rounded-lg border border-border bg-popover p-1.5',
                                    'shadow-lg shadow-black/5',
                                    'animate-in fade-in-0 zoom-in-95 duration-150',
                                )}
                              onClick={() => handleMouseEnter(itemId)}
                            >
                                {item.children!.map((child: siteservicev1_NavigationItem) => (
                                    <View
                                      key={child.id?.toString()}
                                      className='flex w-full cursor-pointer items-center gap-2 rounded-md px-2.5 py-2 text-left text-sm text-foreground/80 transition-colors duration-150 hover:bg-primary/10 hover:text-primary'
                                      onClick={() => {
                                            handleNavigate(child);
                                            onClick?.(Number(child.id));
                                            setOpenMenuId(null);
                                        }}
                                    >
                                        {child.icon && <XIcon name={`carbon:${child.icon}`} size={14} />}
                                        <Text className='truncate'>{child.title}</Text>
                                    </View>
                                ))}
                            </View>
                        )}
                    </View>
                );
            })}
        </View>
    );
}

// frontend/app/vue/app/components/layout/TopNavbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { XIcon } from '@/plugins/xicon'
import { useLanguageChangeEffect } from '@/hooks/use-language-change-effect'
import { usePreferences } from '@/core/preferences/use-preferences'
import { cn } from '@/lib/utils'
import { fetchListNavigations } from '@/api/composables/navigation'

// @ts-ignore - generated types
import type { siteservicev1_NavigationItem } from '@/api/generated/app/service/v1'

const localePath = useLocalePath()
const { t } = useI18n()

const navigationItems = ref<siteservicev1_NavigationItem[]>([])
const isLoading = ref(true)
const openMenuId = ref<number | null>(null)
let closeTimer: ReturnType<typeof setTimeout> | null = null

const loadNav = async () => {
  try {
    isLoading.value = true
    const res = await fetchListNavigations({
      paging: { page: 1, pageSize: 10 },
    }) as any

    if (res.items?.length) {
      const headerNav = res.items.find((nav: any) =>
        nav.location === 'HEADER' && nav.isActive === true
      )
      const items = headerNav?.items
      if (items && items.length > 0) {
        navigationItems.value = items
      }
    }
  } catch (error) {
    console.error('[TopNavbar] 加载导航失败:', error)
  } finally {
    isLoading.value = false
  }
}

onMounted(() => {
  loadNav()
})

useLanguageChangeEffect(() => {
  isLoading.value = true
  fetchListNavigations({ paging: { page: 1, pageSize: 10 } })
    .then((res: any) => {
      if (res.items?.length) {
        const headerNav = res.items.find((nav: any) =>
          nav.location === 'HEADER' && nav.isActive === true
        )
        const items = headerNav?.items
        if (items && items.length > 0) {
          navigationItems.value = items
        }
      }
    })
    .catch((error: any) => console.error('[TopNavbar] 重新加载导航失败:', error))
    .finally(() => (isLoading.value = false))
}, { immediate: false, autoCleanup: true })

onUnmounted(() => {
  if (closeTimer) clearTimeout(closeTimer)
})

const handleNavigate = (item: siteservicev1_NavigationItem) => {
  if (item.isOpenNewTab) {
    window.open(item.url, '_blank')
  } else if (item.url != null) {
    navigateTo(localePath(item.url))
  }
}

const handleMouseEnter = (id: number) => {
  if (closeTimer) {
    clearTimeout(closeTimer)
    closeTimer = null
  }
  openMenuId.value = id
}

const handleMouseLeave = () => {
  closeTimer = setTimeout(() => (openMenuId.value = null), 150)
}

usePreferences() // keep theme reactivity
</script>

<template>
  <div v-if="isLoading" class="flex h-full items-center gap-2">
    <Skeleton v-for="i in 5" :key="i" class="h-7 w-16 rounded-lg" />
  </div>
  <nav v-else-if="navigationItems.length > 0" class="flex h-full items-center gap-0.5">
    <div
      v-for="item in navigationItems"
      :key="item.id ?? 0"
      class="relative"
      @mouseenter="handleMouseEnter(item.id ?? 0)"
      @mouseleave="handleMouseLeave"
    >
      <button
        type="button"
        :class="cn(
          'inline-flex h-9 items-center gap-1.5 rounded-lg px-3 text-sm font-medium',
          'text-foreground/80 transition-all duration-200',
          'hover:bg-primary/10 hover:text-primary',
          (item.children?.length ?? 0) > 0 && openMenuId === (item.id ?? 0) && 'bg-primary/10 text-primary',
          'max-md:px-2',
        )"
        @click="() => {
          if (!(item.children?.length > 0)) {
            handleNavigate(item)
          }
        }"
      >
        <XIcon v-if="item.icon" :name="`carbon:${item.icon}`" :size="16" />
        <span class="whitespace-nowrap">{{ item.title }}</span>
        <XIcon
          v-if="(item.children?.length ?? 0) > 0"
          name="carbon:chevron-down"
          :size="12"
          :class="cn('transition-transform duration-200', openMenuId === (item.id ?? 0) && 'rotate-180')"
        />
      </button>

      <div
        v-if="(item.children?.length ?? 0) > 0 && openMenuId === (item.id ?? 0)"
        :class="cn(
          'absolute left-0 top-full z-1001 mt-1.5',
          'min-w-50 rounded-lg border border-border bg-popover p-1.5',
          'shadow-lg shadow-black/5',
          'animate-in fade-in-0 zoom-in-95 duration-150',
        )"
        @mouseenter="handleMouseEnter(item.id ?? 0)"
        @mouseleave="handleMouseLeave"
      >
        <button
          v-for="child in item.children"
          :key="child.id?.toString()"
          type="button"
          class="flex w-full cursor-pointer items-center gap-2 rounded-md px-2.5 py-2 text-left text-sm text-foreground/80 transition-colors duration-150 hover:bg-primary/10 hover:text-primary"
          @click="() => {
            handleNavigate(child)
            openMenuId = null
          }"
        >
          <XIcon v-if="child.icon" :name="`carbon:${child.icon}`" :size="14" />
          <span class="truncate">{{ child.title }}</span>
        </button>
      </div>
    </div>
  </nav>
</template>
