// frontend/app/vue/app/components/home/CategoryListSection.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { XIcon } from '@/plugins/xicon'
import { cn } from '@/lib/utils'
import { fetchListCategories } from '@/api/composables/category'

const { t } = useI18n()
const localePath = useLocalePath()

const categories = ref<any[]>([])
const loading = ref(true)

let abortController: AbortController | null = null

const loadCategories = async () => {
  if (abortController) abortController.abort()
  abortController = new AbortController()

  loading.value = true
  try {
    const res = await fetchListCategories({
      paging: { page: 1, pageSize: 8 },
      formValues: { status: 'CATEGORY_STATUS_ACTIVE' },
      fieldMask: 'id,status,sortOrder,icon,code,postCount,directPostCount,parent_id,createdAt,translations.id,translations.categoryId,translations.name,translations.languageCode,translations.description',
      orderBy: ['-sortOrder', '-postCount'],
    }) as any

    categories.value = res.items || []
  } catch (error) {
    console.error('Failed to load categories:', error)
    categories.value = []
  } finally {
    loading.value = false
  }
}

onMounted(loadCategories)
onUnmounted(() => { abortController?.abort() })

const getIconName = (icon?: string): string => {
  if (!icon) return 'carbon:folder'
  return icon.includes(':') ? icon : `carbon:${icon}`
}

const getCategoryName = (category: any): string => {
  return category.translations?.[0]?.name || ''
}
</script>

<template>
  <section class="categories-section w-full max-w-300 mx-auto scroll-reveal px-8 py-12 max-md:px-4">
    <!-- Section Header -->
    <div class="mb-8 flex items-center justify-between">
      <h2 class="flex items-center gap-2 text-2xl font-extrabold tracking-tight text-foreground max-md:text-xl">
        <XIcon name="carbon:folder-details" :size="28" class="mr-2 text-primary" />
        {{ t('page.home.categories') }}
      </h2>
      <UIButton variant="ghost" @click="navigateTo(localePath('/category'))">
        {{ t('page.home.view_all') }} →
      </UIButton>
    </div>

    <!-- Loading Skeleton -->
    <div v-if="loading" class="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-6">
      <div v-for="i in 8" :key="i" class="flex min-h-50 flex-col rounded-2xl border border-border bg-card p-6">
        <Skeleton class="h-35 w-full" />
      </div>
    </div>
    <template v-else>
      <!-- Desktop Grid -->
      <div class="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-6 max-md:hidden">
        <div
          v-for="category in categories"
          :key="category.id"
          class="group scroll-reveal-item relative flex min-h-50 h-full cursor-pointer flex-col rounded-2xl border border-slate-100 bg-white p-5 transition-all duration-300 ease-out hover:-translate-y-1 hover:border-primary/30 hover:bg-slate-50 dark:border-slate-800/40 dark:bg-slate-900/50 dark:hover:bg-slate-900 hover:shadow-[0_12px_30px_rgba(34,197,94,0.06)]"
          @click="navigateTo(localePath(`/category/${category.id}`))"
        >
          <div class="pointer-events-none absolute inset-0 bg-linear-to-tr from-primary/5 via-transparent to-sky-400/5 opacity-0 transition-opacity duration-500 group-hover:opacity-100 rounded-2xl" />
          <div class="relative z-1 flex h-full flex-col justify-between">
            <div class="mb-5 flex gap-5">
              <div class="mb-4 flex h-17.5 w-17.5 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 border border-emerald-100/50 text-3xl dark:bg-primary/10 dark:text-primary dark:border-primary/20 transition-all duration-500 ease-out group-hover:scale-110 group-hover:bg-emerald-500 group-hover:text-white group-hover:border-emerald-500 dark:group-hover:bg-primary dark:group-hover:text-white dark:group-hover:border-primary group-hover:shadow-[0_8px_24px_-4px_hsl(var(--primary)/0.4)]">
                <XIcon :name="getIconName(category.icon)" :size="48" />
              </div>
              <div class="flex-1 w-full min-w-0">
                <h3 class="mb-2 text-lg font-extrabold leading-tight tracking-wide text-slate-900 dark:text-foreground transition-colors">
                  {{ getCategoryName(category) }}
                </h3>
                <p class="text-xs text-slate-500 dark:text-muted-foreground mt-1">
                  <span class="mr-1 font-medium text-emerald-600 dark:text-primary">{{ category.postCount || 0 }}</span>
                  {{ t('page.home.articles_unit') }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Mobile carousel -->
      <div class="hidden max-md:flex w-full gap-4 overflow-x-auto no-scrollbar scroll-smooth px-4 pb-4 pt-2 -mx-4">
        <div
          v-for="category in categories"
          :key="category.id"
          class="group scroll-reveal-item w-[170px] shrink-0 flex cursor-pointer flex-col items-center rounded-2xl border border-slate-100 bg-white p-4 text-center transition-all duration-300 ease-out hover:-translate-y-1 hover:border-primary/30 dark:border-slate-800/40 dark:bg-slate-900/50"
          @click="navigateTo(localePath(`/category/${category.id}`))"
        >
          <div class="relative z-1 flex h-full w-full flex-col items-center justify-between gap-3">
            <div class="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 border border-emerald-100/50 dark:bg-primary/10 dark:text-primary dark:border-primary/20 transition-all duration-500 ease-out group-hover:scale-110 group-hover:bg-emerald-500 group-hover:text-white dark:group-hover:bg-primary dark:group-hover:text-white">
              <XIcon :name="getIconName(category.icon)" :size="32" />
            </div>
            <div class="flex w-full min-w-0 flex-1 flex-col items-center gap-1">
              <h3 class="line-clamp-2 text-sm font-bold leading-tight tracking-wide text-slate-900 dark:text-foreground">
                {{ getCategoryName(category) }}
              </h3>
              <p class="text-xs text-slate-500 dark:text-muted-foreground">
                <span class="mr-1 font-medium text-emerald-600 dark:text-primary">{{ category.postCount || 0 }}</span>
                {{ t('page.home.articles_unit') }}
              </p>
            </div>
          </div>
        </div>
      </div>
    </template>
  </section>
</template>

// frontend/app/taro/src/components/home/CategoryListSection.tsx
import {View, Text} from '@tarojs/components';
﻿import React, {useState, useEffect, useCallback, useRef, useMemo} from 'react';
import {Skeleton} from '@/components/ui/skeleton';
import {Button} from '@/components/ui/button';
import {useTranslations} from '@/lib/next-intl-compat';

import {fetchListCategories} from '@/api/hooks/category';
import {
    contentservicev1_Category,
    contentservicev1_ListCategoryResponse,
} from '@/api/generated/app/service/v1';
import {XIcon} from '@/plugins/xicon';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';


import HomeCategoryCard from './HomeCategoryCard';

interface CategoryListSectionProps {
    skeletonCount?: number;
    showCarousel?: boolean;
    pageSize?: number;
    page?: number;
    filter?: Record<string, unknown>;
    orderBy?: string[];
    fieldMask?: string;
    showHeader?: boolean;
}

export default function CategoryListSection({
                                                skeletonCount = 8,
                                                showCarousel = false,
                                                pageSize = 8,
                                                page = 1,
                                                filter = {status: 'CATEGORY_STATUS_ACTIVE'} as Record<string, unknown>,
                                                orderBy = ['-sortOrder', '-postCount'],
                                                fieldMask = 'id,status,sortOrder,icon,code,postCount,directPostCount,parent_id,createdAt,translations.id,translations.categoryId,translations.name,translations.languageCode,translations.description',
                                                showHeader = true
                                            }: CategoryListSectionProps) {
    const t = useTranslations('page.home');
    const router = useI18nRouter();

    // 使用 useMemo 稳定对象引用
    const stableFilter = useMemo(() => filter, [filter]);
    const stableOrderBy = useMemo(() => orderBy, [orderBy]);

    const [categories, setCategories] = useState<contentservicev1_Category[]>([]);
    const [loading, setLoading] = useState(false);

    // 用于取消异步操作
    const abortControllerRef = useRef<AbortController | null>(null);

    const loadCategories = useCallback(async () => {
        // 取消之前的请求
        if (abortControllerRef.current) {
            abortControllerRef.current.abort();
        }

        // 创建新的 AbortController
        abortControllerRef.current = new AbortController();
        const signal = abortControllerRef.current.signal;

        setLoading(true);
        try {
            const res = await fetchListCategories({
                paging: {page, pageSize},
                formValues: stableFilter,
                fieldMask,
                orderBy: stableOrderBy,
            }) as unknown as contentservicev1_ListCategoryResponse;

            if (signal.aborted) return;

            setCategories(res.items || []);
        } catch (error) {
            if (signal.aborted) return;
            console.error('Failed to load categories:', error);
            setCategories([]);
        } finally {
            if (!signal.aborted) {
                setLoading(false);
            }
        }
    }, [stableFilter, fieldMask, stableOrderBy]); // 移除 page, pageSize 依赖

    useEffect(() => {
        loadCategories();

        // 组件卸载时取消请求
        return () => {
            if (abortControllerRef.current) {
                abortControllerRef.current.abort();
            }
        };
    }, []); // 空依赖数组，只在首次渲染时执行

    const handleViewCategoryDetail = (id: number) => {
        router.push(`/category/detail?id=${id}`);
    };

    const handleViewCategory = () => {
        router.push(`/category`);
    };

    return (
        <View className='categories-section w-full scroll-reveal'>
            {/* Section Header */}
            {showHeader && (
                <View className='mb-8 flex items-center justify-between'>
                    <Text className='flex items-center gap-2 text-2xl font-extrabold tracking-tight text-foreground max-md:text-xl'>
                        <XIcon name='carbon:folder-details' size={28} className='mr-2 text-primary' />
                        {t('categories')}
                    </Text>
                    <Button variant='ghost' onClick={handleViewCategory}>
                        {t('view_all')} →
                    </Button>
                </View>
            )}

            {/* Loading Skeleton */}
            {loading ? (
                <View className='grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-6'>
                    {Array.from({length: skeletonCount}).map((_, i) => (
                        <View key={i} className='flex min-h-50 flex-col rounded-2xl border border-border bg-card p-6'>
                            <Skeleton className='h-35 w-full' />
                        </View>
                    ))}
                </View>
            ) : (
                <>
                    {/* Desktop Grid */}
                    <View className='grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-6 max-md:hidden'>
                        {categories.map((category) => (
                            <HomeCategoryCard
                              key={category.id}
                              category={category}
                              onClick={handleViewCategoryDetail}
                            />
                        ))}
                    </View>

                    {/* Mobile：横向传送带（X-Axis Slider） */}
                    <View className='hidden max-md:flex w-full gap-4 overflow-x-auto no-scrollbar scroll-smooth px-4 pb-4 pt-2 -mx-4'>
                        {categories.map((category) => (
                            <HomeCategoryCard
                              key={category.id}
                              category={category}
                              onClick={handleViewCategoryDetail}
                              mobileCompact
                            />
                        ))}
                    </View>
                </>
            )}
        </View>
    );
}
