// frontend/app/react/src/app/[locale]/register/page.tsx
'use client';

import {useState, useMemo} from 'react';
import {useTranslations} from 'next-intl';
import {useRouter, usePathname} from 'next/navigation';
import XIcon from '@/plugins/xicon';

import '../../globals.css'; // 导入全局 CSS，确保 CSS 变量可用
import styles from './register.module.css';

import AccountRegisterPage from './components/AccountRegisterPage';
import EmailRegisterPage from './components/EmailRegisterPage';
import PhoneRegisterPage from './components/PhoneRegisterPage';
import OtherRegisterPage from './components/OtherRegisterPage';

// 获取初始主题状态（仅在客户端调用）
function getInitialTheme(): boolean {
    if (typeof window === 'undefined') {
        return false;
    }
    return document.documentElement.classList.contains('dark');
}

export default function RegisterPage() {
    const t = useTranslations('authentication');
    const router = useRouter();
    const pathname = usePathname();
    const [activeTab, setActiveTab] = useState<'account' | 'email' | 'phone' | 'other'>('account');
    const [isDark, setIsDark] = useState<boolean>(getInitialTheme);

    // 从 URL 中获取当前语言
    const currentLocale = pathname?.split('/')[1] || 'zh-CN';

    // 语言选项
    const languageOptions = useMemo(() => [
        {key: 'zh-CN', label: '中文'},
        {key: 'en-US', label: 'English'}
    ], []);

    // 切换语言
    const handleSelectLanguage = (key: string) => {
        // 替换 URL 中的 locale 部分
        const newPath = pathname?.replace(`/${currentLocale}`, `/${key}`) || `/${key}/register`;
        router.push(newPath);
    };

    // 切换主题
    const handleToggleTheme = () => {
        const newIsDark = !document.documentElement.classList.contains('dark');
        setIsDark(newIsDark);
        if (newIsDark) {
            document.documentElement.classList.add('dark');
        } else {
            document.documentElement.classList.remove('dark');
        }
    };

    // 登录
    const handleLoginClick = () => {
        window.location.href = '/login';
    };

    // 返回首页
    const handleBackHome = () => {
        window.location.href = '/';
    };

    // 服务条款
    const handleTermsClick = () => {
        window.location.href = '/terms';
    };

    // 隐私政策
    const handlePrivacyClick = () => {
        window.location.href = '/privacy';
    };

    return (
        <div className={styles['register-page']}>
            {/* 顶部控制按钮 */}
            <div className={styles['register-controls']}>
                <select
                    className={styles['language-select']}
                    value={currentLocale}
                    onChange={(e) => handleSelectLanguage(e.target.value)}
                >
                    {languageOptions.map((option) => (
                        <option key={option.key} value={option.key}>
                            {option.label}
                        </option>
                    ))}
                </select>
                <button
                    className={`${styles['control-btn']} ${styles['theme-toggle']}`}
                    onClick={handleToggleTheme}
                    aria-label="Toggle theme"
                >
                    <XIcon name={isDark ? 'carbon:sun' : 'carbon:moon'} size={18}/>
                </button>
            </div>

            {/* 左侧品牌区 */}
            <div className={styles['register-left']}>
                <div className={styles.brand}>
                    <img src="/logo.png" alt={t('login.logo_alt')} className={styles['brand-logo']}/>
                    <h1 className={styles['brand-title']}>{t('login.brand_title')}</h1>
                    <p className={styles['brand-subtitle']}>{t('login.brand_subtitle')}</p>
                </div>

                <div className={styles['benefits-list']}>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_projects')}</span>
                    </div>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_isolation')}</span>
                    </div>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_permissions')}</span>
                    </div>
                    <div className={styles['benefit-item']}>
                        <span>✓</span>
                        <span>{t('login.feature_analytics')}</span>
                    </div>
                </div>
            </div>

            {/* 右侧注册卡片 */}
            <div className={styles['register-right']}>
                <div className={styles['register-card']}>
                    <div className={styles['card-header']}>
                        <h2>{t('register.title')}</h2>
                        <p>{t('register.register_with')}</p>
                    </div>

                    {/* Tab 切换 */}
                    <div className={styles['register-tabs']}>
                        <button
                            className={`${styles.tab} ${activeTab === 'account' ? styles.active : ''}`}
                            onClick={() => setActiveTab('account')}
                        >
                            {t('login.tab_account')}
                        </button>
                        <button
                            className={`${styles.tab} ${activeTab === 'email' ? styles.active : ''}`}
                            onClick={() => setActiveTab('email')}
                        >
                            {t('login.tab_email')}
                        </button>
                        <button
                            className={`${styles.tab} ${activeTab === 'phone' ? styles.active : ''}`}
                            onClick={() => setActiveTab('phone')}
                        >
                            {t('login.tab_phone')}
                        </button>
                        <button
                            className={`${styles.tab} ${activeTab === 'other' ? styles.active : ''}`}
                            onClick={() => setActiveTab('other')}
                        >
                            {t('login.tab_other')}
                        </button>
                    </div>

                    {/* 注册表单内容 */}
                    <div className={styles['register-content']}>
                        {activeTab === 'account' && <AccountRegisterPage/>}
                        {activeTab === 'email' && <EmailRegisterPage/>}
                        {activeTab === 'phone' && <PhoneRegisterPage/>}
                        {activeTab === 'other' && <OtherRegisterPage/>}
                    </div>

                    {/* 登录链接 */}
                    <div className={styles['login-section']}>
                        <p>
                            {t('register.already_have_account')}
                            <button className={styles['text-btn']} onClick={handleLoginClick}>
                                {t('register.login_now')}
                            </button>
                        </p>
                    </div>

                    {/* 返回首页 */}
                    <div className={styles['back-home']}>
                        <button className={styles['text-btn']} onClick={handleBackHome}>
                            ← {t('login.back_home')}
                        </button>
                    </div>

                    {/* 服务条款 */}
                    <div className={styles.terms}>
                        <small>
                            {t('login.terms_prefix')}
                            <button className={styles['text-btn']} onClick={handleTermsClick}>
                                {t('login.terms_of_service')}
                            </button>
                            {t('login.terms_and')}
                            <button className={styles['text-btn']} onClick={handlePrivacyClick}>
                                {t('login.privacy_policy')}
                            </button>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    );
}

// frontend/app/vue3/src/pages/register/index.vue
<script setup lang="ts">
import {computed, ref} from "vue";
import {definePage} from "unplugin-vue-router/runtime";
import {useRoute, useRouter} from 'vue-router'
import {$t} from '@/locales';

import AccountRegisterPage from "./components/AccountRegisterPage.vue";
import EmailRegisterPage from "./components/EmailRegisterPage.vue";
import PhoneRegisterPage from "./components/PhoneRegisterPage.vue";
import OtherRegisterPage from "./components/OtherRegisterPage.vue";
import { MoonOutline, SunnyOutline } from '@vicons/ionicons5'
import { isDark, toggleDark } from '@/composables/dark'
import { languageColumns, languageShorts, i18n, loadLocaleMessages, type SupportedLanguagesType } from '@/locales'
import { updatePreferences } from "@/preferences";

definePage({
  name: 'register',
  meta: {
    level: 1,
    hideLayout: true, // 隐藏全局 Header 和 Footer
    forceLight: false, // 遵循全局主题设置
  },
})

const router = useRouter()
const route = useRoute()
const activeTab = ref('account');

const forceLight = computed(() => route.meta.forceLight === true)

function getLanguageLabel() {
  const lang = i18n.global.locale.value;
  const ret = languageShorts.find((item) => item.key === lang);
  return ret?.label ?? lang;
}

async function handleSelectLanguage(key: string | number) {
  const locale = key as SupportedLanguagesType;
  if (locale === i18n.global.locale.value) {
    return;
  }

  updatePreferences({
    app: {
      locale,
    },
  });

  await loadLocaleMessages(locale);
}

function handleToggleTheme() {
  toggleDark();
}

const handleLoginClick = () => {
  router.push('/login')
}

const handleBackHome = () => {
  router.push('/')
}

const handleTermsClick = () => {
  router.push('/terms')
}

const handlePrivacyClick = () => {
  router.push('/privacy')
}
</script>

<template>
  <div class="register-page" :class="{ 'force-light': forceLight }">
    <div class="register-controls">
      <n-dropdown trigger="hover" size="huge" :options="languageColumns" @select="handleSelectLanguage">
        <n-button round class="control-btn" :aria-label="$t('navbar.top.language')">
          {{ getLanguageLabel() }}
        </n-button>
      </n-dropdown>
      <n-button round class="control-btn" :aria-label="isDark ? $t('navbar.top.light_mode') : $t('navbar.top.dark_mode')" @click="handleToggleTheme">
        <template #icon>
          <n-icon>
            <component :is="isDark ? SunnyOutline : MoonOutline"/>
          </n-icon>
        </template>
      </n-button>
    </div>

    <div class="register-left">
      <div class="brand">
        <img src="/logo.png" :alt="$t('authentication.login.logo_alt')" class="brand-logo" />
        <h1 class="brand-title">{{ $t('authentication.login.brand_title') }}</h1>
        <p class="brand-subtitle">{{ $t('authentication.login.brand_subtitle') }}</p>
      </div>

      <div class="benefits-list">
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_projects') }}</span>
        </div>
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_isolation') }}</span>
        </div>
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_permissions') }}</span>
        </div>
        <div class="benefit-item">
          <span>✓</span>
          <span>{{ $t('authentication.login.feature_analytics') }}</span>
        </div>
      </div>
    </div>

    <div class="register-right">
      <n-card :bordered="false" class="register-card">
        <template #header>
          <div class="card-header">
            <h2>{{ $t('authentication.register.title') }}</h2>
            <p>{{ $t('authentication.register.register_with') }}</p>
          </div>
        </template>

        <n-tabs v-model:value="activeTab" type="segment" animated class="register-tabs">
          <n-tab-pane name="account" :tab="$t('authentication.login.tab_account')">
            <AccountRegisterPage/>
          </n-tab-pane>

          <n-tab-pane name="email" :tab="$t('authentication.login.tab_email')">
            <EmailRegisterPage/>
          </n-tab-pane>

          <n-tab-pane name="phone" :tab="$t('authentication.login.tab_phone')">
            <PhoneRegisterPage/>
          </n-tab-pane>

          <n-tab-pane name="other" :tab="$t('authentication.login.tab_other')">
            <OtherRegisterPage/>
          </n-tab-pane>
        </n-tabs>

        <div class="login-section">
          <p>{{ $t('authentication.register.already_have_account') }}
            <n-button text type="primary" @click="handleLoginClick">
              {{ $t('authentication.register.login_now') }}
            </n-button>
          </p>
        </div>

        <div class="back-home">
          <n-button text type="primary" @click="handleBackHome">
            ← {{ $t('authentication.login.back_home') }}
          </n-button>
        </div>

        <div class="terms">
          <small>
            {{ $t('authentication.login.terms_prefix') }}
            <n-button text type="primary" @click="handleTermsClick">{{ $t('authentication.login.terms_of_service') }}</n-button>
            {{ $t('authentication.login.terms_and') }}
            <n-button text type="primary" @click="handlePrivacyClick">{{ $t('authentication.login.privacy_policy') }}</n-button>
          </small>
        </div>
      </n-card>
    </div>
  </div>
</template>

<style scoped lang="less">
.register-page {
  --auth-page-bg: var(--color-bg);
  --auth-right-bg: var(--color-surface);
  --auth-card-bg: var(--color-surface);
  --auth-border: var(--color-border);
  --auth-text-primary: var(--color-text-primary);
  --auth-text-secondary: var(--color-text-secondary);
  --auth-brand-start: var(--color-brand);
  --auth-brand-end: var(--color-brand-accent);
  --auth-brand-text: #ffffff;
  --auth-tab-bg: rgba(102, 126, 234, 0.08);
  --auth-tab-active-bg: rgba(102, 126, 234, 0.16);
  --auth-tab-active-text: var(--color-brand);
  --auth-focus-ring: 0 0 0 3px rgba(102, 126, 234, 0.18);

  display: flex;
  min-height: 100vh;
  background: var(--auth-page-bg);

  &.force-light {
    --auth-page-bg: #f5f7fa;
    --auth-right-bg: #ffffff;
    --auth-card-bg: #ffffff;
    --auth-border: #e8e8e8;
    --auth-text-primary: #333333;
    --auth-text-secondary: #666666;
    --auth-tab-bg: rgba(102, 126, 234, 0.08);
    --auth-tab-active-bg: rgba(102, 126, 234, 0.16);
    --auth-tab-active-text: #667eea;
  }

  .register-left {
    flex: 1;
    background: linear-gradient(135deg, var(--auth-brand-start) 0%, var(--auth-brand-end) 100%);
    color: var(--auth-brand-text);
    padding: 4rem 2rem;
    display: flex;
    flex-direction: column;
    justify-content: space-between;

    .brand {
      text-align: center;
      margin-bottom: 3rem;

      .brand-logo {
        width: 80px;
        height: 80px;
        margin-bottom: 1rem;
      }

      .brand-title {
        font-size: 2.5rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
      }

      .brand-subtitle {
        font-size: 1.1rem;
        opacity: 0.92;
      }
    }

    .benefits-list {
      display: flex;
      flex-direction: column;
      gap: 1rem;

      .benefit-item {
        display: flex;
        align-items: center;
        gap: 1rem;
        padding: 1rem 0;
        font-size: 1.05rem;
      }
    }
  }

  .register-right {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2rem;
    background: var(--auth-right-bg);

    .register-card {
      width: 100%;
      max-width: 420px;
      border: 1px solid var(--auth-border);
      border-radius: var(--radius-md);
      background: var(--auth-card-bg);

      :deep(.n-card__content) {
        color: var(--auth-text-primary);
      }

      .card-header {
        text-align: center;
        margin-bottom: 1.5rem;

        h2 {
          font-size: 1.75rem;
          margin-bottom: 0.5rem;
          color: var(--auth-text-primary);
        }

        p {
          color: var(--auth-text-secondary);
          font-size: 0.95rem;
        }
      }
    }
  }
}

.register-controls {
  position: fixed;
  top: 20px;
  right: 20px;
  display: flex;
  gap: 8px;
  z-index: 100;
  background: rgba(255, 255, 255, 0.9);
  padding: 8px;
  border-radius: 12px;
  backdrop-filter: blur(8px);
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease;

  &:hover {
    background: rgba(255, 255, 255, 0.95);
    box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
  }

  .control-btn {
    --n-color: transparent;
    --n-color-hover: rgba(102, 126, 234, 0.08);
    --n-color-pressed: rgba(102, 126, 234, 0.12);
    --n-border: 1px solid transparent;
    --n-border-hover: 1px solid rgba(102, 126, 234, 0.2);
    --n-text-color: var(--color-text-secondary);
    --n-text-color-hover: var(--color-brand);
    min-width: auto;
    padding: 6px 12px;
    font-size: 13px;
    font-weight: 500;
    transition: all 0.2s ease;

    &:hover {
      transform: translateY(-1px);
    }

    :deep(.n-icon) {
      font-size: 16px;
    }
  }
}

.register-tabs {
  margin-bottom: 1.5rem;

  :deep(.n-tabs-nav--segment-type) {
    background: var(--auth-tab-bg);
  }

  :deep(.n-tabs-tab.n-tabs-tab--active) {
    background: var(--auth-tab-active-bg);
    color: var(--auth-tab-active-text);
  }
}

.login-section {
  text-align: center;
  padding: 1.5rem 0;
  border-top: 1px solid var(--auth-border);
  border-bottom: 1px solid var(--auth-border);

  p {
    margin: 0;
    font-size: 0.95rem;
    color: var(--auth-text-secondary);
  }
}

.back-home {
  text-align: center;
  padding: 1rem 0;

  :deep(.n-button) {
    font-size: 0.9rem;
  }
}

.terms {
  text-align: center;
  margin-top: 1rem;
  color: var(--auth-text-secondary);
  line-height: 1.6;

  small {
    font-size: 0.85rem;
  }
}

:deep(.login-section .n-button--text-type),
:deep(.back-home .n-button--text-type),
:deep(.terms .n-button--text-type) {
  --n-text-color-text: var(--color-brand);
  --n-text-color-text-hover: var(--auth-tab-active-text);
  --n-text-color-text-pressed: var(--auth-tab-active-text);
}

:deep(.login-section .n-button--text-type:focus-visible),
:deep(.back-home .n-button--text-type:focus-visible),
:deep(.terms .n-button--text-type:focus-visible) {
  box-shadow: var(--auth-focus-ring);
  border-radius: 6px;
}

html.dark {
  .register-controls {
    background: rgba(27, 31, 39, 0.9);
    box-shadow: 0 2px 12px rgba(0, 0, 0, 0.3);

    &:hover {
      background: rgba(27, 31, 39, 0.95);
      box-shadow: 0 4px 16px rgba(0, 0, 0, 0.4);
    }

    .control-btn {
      --n-text-color: var(--color-text-secondary);
      --n-text-color-hover: var(--color-brand);
      --n-color-hover: rgba(102, 126, 234, 0.12);
      --n-color-pressed: rgba(102, 126, 234, 0.18);
    }
  }

  .register-page:not(.force-light) {
    --auth-page-bg: #121317;
    --auth-right-bg: #1b1f27;
    --auth-card-bg: #1b1f27;
    --auth-border: #2a3140;
    --auth-text-primary: #e8ecf3;
    --auth-text-secondary: #aab3c2;
    --auth-tab-bg: rgba(129, 147, 255, 0.18);
    --auth-tab-active-bg: rgba(129, 147, 255, 0.26);
    --auth-tab-active-text: #b8c5ff;
    --auth-focus-ring: 0 0 0 3px rgba(129, 147, 255, 0.28);
  }
}

@media (max-width: 1024px) {
  .register-page {
    flex-direction: column;

    .register-left {
      padding: 2rem;
      min-height: 200px;
      justify-content: flex-start;
    }

    .register-right {
      flex: 1;
      background: var(--auth-right-bg);

      .register-card {
        max-width: 100%;
      }
    }
  }

  .register-controls {
    top: 12px;
    right: 12px;
    padding: 6px;
    gap: 6px;

    .control-btn {
      padding: 4px 8px;
      font-size: 12px;

      :deep(.n-icon) {
        font-size: 14px;
      }
    }
  }
}
</style>
