// frontend/app/vue/app/pages/category/index.vue
<script setup lang="ts">
import { fetchListCategory } from '@/api/composables/category'

const { t } = useI18n()

useHead({ title: t('page.categories.categories') })
const localePath = useLocalePath()

const categories = ref<any[]>([])
const loading = ref(true)

onMounted(async () => {
  try {
    const res = await fetchListCategory({
      formValues: { status: 'CATEGORY_STATUS_ACTIVE' },
      fieldMask: 'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image',
      orderBy: ['-sortOrder'],
    })
    categories.value = res?.items || []
  } catch (e) {
    console.error('[Category List] 加载失败:', e)
  } finally {
    loading.value = false
  }
})

function handleCategoryClick(id: number) {
  navigateTo(localePath(`/category/${id}`))
}
</script>

<template>
  <div class="w-full">
    <LayoutPageHero
      :title="t('page.categories.categories')"
      :description="t('page.categories.browse_all')"
      icon="carbon:folder"
      size="md"
    />

    <LayoutSectionContainer>
      <!-- Loading Skeleton -->
      <div v-if="loading" class="grid grid-cols-[repeat(auto-fill,minmax(280px,1fr))] gap-6">
        <div v-for="i in 6" :key="i">
          <UiSkeleton class="h-40 w-full" />
        </div>
      </div>

      <template v-else>
        <!-- Category Tree -->
        <CategoryTree
          v-if="categories.length > 0"
          :categories="categories"
          :on-category-click="handleCategoryClick"
        />

        <!-- Empty -->
        <UiAppEmpty
          v-else
          :description="t('page.categories.no_categories')"
          in-container
        />
      </template>
    </LayoutSectionContainer>
  </div>
</template>

// frontend/app/taro/src/pages/category/index.tsx
import {useState, useEffect} from 'react';
import {useTranslation} from 'react-i18next';
import {View, Text} from '@tarojs/components';

import {AppEmpty} from '@/components/ui';
import CategoryTree from '@/components/category/CategoryTree';

import {fetchListCategories} from '@/api/hooks/category';
import {useI18nRouter} from "@/i18n/helpers";

import {contentservicev1_Category} from "@/api/generated/app/service/v1";export default function CategoryListPage() {
  const {t} = useTranslation();
  const router = useI18nRouter();

  const [loading, setLoading] = useState(false);
  const [categories, setCategories] = useState<contentservicev1_Category[]>([]);

  async function loadCategories() {
    setLoading(true);
    try {
      const res = await fetchListCategories({
        paging: undefined,
        formValues: {status: 'CATEGORY_STATUS_ACTIVE'},
        fieldMask: 'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image',
        orderBy: ['-sortOrder']
      });
      setCategories(res.items || []);
    } catch (error) {
      console.error('Load categories failed:', error);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadCategories();
  }, []);

  const handleCategoryClick = (id: number) => {
    router.push(`/category/${id}`);
  };

  return (
    <View className='category-page'>
      {/* Hero Section */}
      <View className='hero-section'>
        <View className='hero-content'>
          <Text className='hero-title'>内容分类</Text>
          <Text className='hero-subtitle'>浏览所有内容分类</Text>
        </View>
      </View>

      {/* Content Section */}
      <View className='page-container'>
        {/* Loading Skeleton - TODO: 实现 Taro 的加载骨架屏 */}
        {loading ? (
          <View className='categories-loading'>
            <Text>{t('common.loading')}</Text>
          </View>
        ) : (
          <>
            {categories.length > 0 ? (
              <CategoryTree
                categories={categories}
                onCategoryClick={handleCategoryClick}
              />
            ) : (
              <AppEmpty
                description={t('page.categories.no_categories')}
                inContainer
                image={<span className='i-carbon:folder-blank' style={{fontSize: '64px'}} />}
              />
            )}
          </>
        )}
      </View>
    </View>
  );
}
