// frontend/app/react/src/app/[locale]/post/page.tsx
'use client';

import {useState, useMemo} from 'react';
import {useTranslations} from 'next-intl';

import PageHero from '@/components/layout/PageHero';
import CategoryFilter from '@/components/category/CategoryFilter';
import PostList from '@/components/post/PostList';

export default function PostListPage() {
    const t = useTranslations('page');
    const [selectedCategoryId, setSelectedCategoryId] = useState<number | null>(null);

    const handleCategoryChange = (categoryId: number | null) => {
        console.log('[PostListPage] Category changed:', categoryId);
        setSelectedCategoryId(categoryId);
    };

    // 构建查询参数 - 使用 useMemo 确保稳定性
    const queryParams = useMemo(() => {
        if (selectedCategoryId) {
            return {category_ids__in: [selectedCategoryId]};
        }
        return {};
    }, [selectedCategoryId]);

    return (
        <div className="w-full">
            <PageHero
                title={t('posts.posts_list')}
                description={t('posts.explore_latest')}
                icon="carbon:document"
                size="md"
            />

            <div className="w-full max-w-[1200px] mx-auto px-8 py-12 max-md:px-4">
                <CategoryFilter
                    selectedCategory={selectedCategoryId}
                    treeMode={true}
                    autoLoad={true}
                    onCategoryChange={handleCategoryChange}
                />

                <PostList
                    key={selectedCategoryId || 'all'}  // 使用 key 强制重新渲染
                    queryParams={queryParams}
                    initialPageSize={12}
                    pageSizes={[12, 24, 36, 48]}
                />
            </div>
        </div>
    );
}

// frontend/app/vue/app/pages/post/index.vue
<script setup lang="ts">
const { t } = useI18n()

useHead({ title: t('page.posts.posts_list') })

const selectedCategoryId = ref<number | null>(null)

const handleCategoryChange = (categoryId: number | null) => {
  selectedCategoryId.value = categoryId
}

const queryParams = computed(() => {
  if (selectedCategoryId.value) {
    return { category_ids__in: [selectedCategoryId.value] }
  }
  return {}
})
</script>

<template>
  <div class="w-full">
    <LayoutPageHero
      :title="t('page.posts.posts_list')"
      :description="t('page.posts.explore_latest')"
      icon="carbon:document"
      size="md"
    />

    <LayoutSectionContainer>
      <CategoryFilter
        :selected-category="selectedCategoryId"
        :tree-mode="true"
        :auto-load="true"
        @category-change="handleCategoryChange"
      />

      <PostList
        :key="selectedCategoryId || 'all'"
        :query-params="queryParams"
        :initial-page-size="12"
      />
    </LayoutSectionContainer>
  </div>
</template>
