// frontend/app/react/src/components/comment/CommentTree.tsx
'use client';

import React, {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Avatar, AvatarFallback} from '@/components/ui/avatar';
import {Spinner} from '@/components/ui/spinner';
import {useTranslations} from 'next-intl';

import {XIcon} from '@/plugins/xicon';
import type {commentservicev1_Comment} from "@/api/generated/app/service/v1";
import {formatDate} from "@/utils/date";

import {cn} from '@/lib/utils';

interface CommentTreeProps {
    comments: commentservicev1_Comment[];
    onReply: (comment: commentservicev1_Comment, content: string) => void;
    onLoadChildren: (comment: commentservicev1_Comment) => Promise<void>;
}

const CommentTree: React.FC<CommentTreeProps> = ({
                                                     comments,
                                                     onReply,
                                                     onLoadChildren
                                                 }) => {
    const t = useTranslations('comment');
    const [replyingCommentId, setReplyingCommentId] = useState<number | null>(null);
    const [replyContent, setReplyContent] = useState('');
    const [submitting, setSubmitting] = useState(false);
    const [expandedComments, setExpandedComments] = useState<Set<number>>(new Set());
    const [loadingChildren, setLoadingChildren] = useState<Set<number>>(new Set());
    const [likedComments, setLikedComments] = useState<Set<number>>(new Set());

    function hasChildren(comment: commentservicev1_Comment): boolean {
        return !!comment.children || (comment.replyCount !== undefined && comment.replyCount > 0);
    }

    function isOwnerReply(comment: commentservicev1_Comment): boolean {
        return comment.authorType === 'AUTHOR_TYPE_ADMIN' && !!comment.replyToId;
    }

    function isExpanded(comment: commentservicev1_Comment): boolean {
        return expandedComments.has(comment.id || 0);
    }

    function isLoading(comment: commentservicev1_Comment): boolean {
        return loadingChildren.has(comment.id || 0);
    }

    function handleReply(comment: commentservicev1_Comment) {
        setReplyingCommentId(comment.id || 0);
        setReplyContent('');
    }

    function cancelReply() {
        setReplyingCommentId(null);
        setReplyContent('');
    }

    async function submitReply(comment: commentservicev1_Comment) {
        if (!replyContent.trim()) {
            alert(t('empty_content'));
            return;
        }

        if (submitting) return;

        setSubmitting(true);
        try {
            onReply(comment, replyContent.trim());
            cancelReply();
        } catch (error) {
            console.error('Submit reply failed:', error);
            alert(t('submit_comment_failed'));
        } finally {
            setSubmitting(false);
        }
    }

    // 处理点赞
    function handleLike(comment: commentservicev1_Comment) {
        const commentId = comment.id || 0;

        if (likedComments.has(commentId)) {
            // 取消点赞
            setLikedComments(prev => {
                const next = new Set(prev);
                next.delete(commentId);
                return next;
            });
        } else {
            // 点赞
            setLikedComments(prev => new Set(prev).add(commentId));
            // 这里可以调用 API 更新点赞数
            // comment.likeCount = (comment.likeCount || 0) + 1;
        }
    }

    function handleShare(comment: commentservicev1_Comment) {
        // 获取当前 URL（不包含 hash）
        const baseUrl = typeof window !== 'undefined' ? window.location.href.split('#')[0] : '';
        const commentUrl = `${baseUrl}#comment-${comment.id}`;

        navigator.clipboard.writeText(commentUrl).then(() => {
            // message.success(t('link_copied'));
        }).catch(() => {
            // message.error(t('copy_failed'));
        });
    }

    // 切换展开/收起子评论
    async function toggleExpand(comment: commentservicev1_Comment) {
        if (isExpanded(comment)) {
            // 收起
            setExpandedComments(prev => {
                const next = new Set(prev);
                next.delete(comment.id || 0);
                return next;
            });
        } else {
            // 展开
            if (!comment.children && comment.replyCount && comment.replyCount > 0) {
                // 需要动态加载子评论
                setLoadingChildren(prev => new Set(prev).add(comment.id || 0));
                try {
                    await onLoadChildren(comment);
                    setExpandedComments(prev => new Set(prev).add(comment.id || 0));
                } catch (error) {
                    console.error('Load children failed:', error);
                } finally {
                    setLoadingChildren(prev => {
                        const next = new Set(prev);
                        next.delete(comment.id || 0);
                        return next;
                    });
                }
            } else {
                // 已经有子评论数据，直接展开
                setExpandedComments(prev => new Set(prev).add(comment.id || 0));
            }
        }
    }

    if (!comments || comments.length === 0) return null;

    return (
        <div className="flex flex-col gap-7">
            {comments.map((comment) => (
                <div key={comment.id} className="flex flex-col">
                    {/* 评论主体 */}
                    <div className={cn(
                        'group relative flex gap-5 overflow-hidden rounded-2xl border border-border bg-linear-to-br from-card to-primary/2 p-7',
                        'shadow-sm transition-all duration-400',
                        'hover:border-primary hover:shadow-md hover:translate-x-1 hover:-translate-y-0.5',
                        'max-md:p-6 max-md:gap-4',
                        'max-sm:p-4 max-sm:gap-3',
                    )}>
                        {/* Left accent bar on hover */}
                        <div className="absolute top-0 start-0 h-full w-1 bg-primary opacity-0 transition-opacity duration-300 group-hover:opacity-100"/>

                        <div className="shrink-0">
                            <Avatar className="h-12 w-12 ring-2 ring-border/30 shadow-md">
                                <AvatarFallback className="bg-primary text-primary-foreground font-semibold">
                                    {comment.authorName?.charAt(0) || 'U'}
                                </AvatarFallback>
                            </Avatar>
                        </div>
                        <div className="min-w-0 flex-1">
                            {/* Header */}
                            <div className={cn(
                                'mb-4 flex items-center justify-between border-b border-primary/8 pb-3',
                                'max-md:flex-col max-md:items-start max-md:gap-2 max-md:mb-3 max-md:pb-2.5',
                                'max-sm:gap-1.5 max-sm:mb-2 max-sm:pb-1.5',
                            )}>
                                <div className="flex flex-wrap items-center gap-3 max-md:flex-col max-md:items-start max-md:gap-1.5">
                                    <strong className="flex items-center gap-2 text-[17px] font-semibold tracking-tight text-foreground max-md:text-base max-sm:text-[15px]">
                                        <span className="text-sm font-bold text-primary">@</span>
                                        {isOwnerReply(comment) && (
                                            <span className="inline-flex items-center gap-1 rounded-lg bg-primary px-2.5 py-0.5 text-[11px] font-bold text-primary-foreground shadow-sm max-sm:text-[10px] max-sm:px-1.5 max-sm:py-0.5">
                                                <XIcon name="carbon:badge" size={13}/>
                                                {t('owner_reply')}
                                            </span>
                                        )}
                                        {comment.authorName}
                                    </strong>
                                    {comment.location && !isOwnerReply(comment) && (
                                        <span className="flex items-center gap-1 text-xs text-muted-foreground">
                                            {comment.location}
                                        </span>
                                    )}
                                </div>
                                <span className="flex items-center gap-1.5 text-[13px] text-muted-foreground max-md:text-xs max-sm:text-[11px]">
                                    {formatDate(comment.createdAt)}
                                </span>
                            </div>

                            {/* Content */}
                            <div className="mb-4 ps-1 text-[15px] leading-relaxed text-foreground max-md:text-sm max-sm:text-[13px]">
                                {comment.content}
                            </div>

                            {/* Actions */}
                            <div className={cn(
                                'flex gap-5 border-t border-primary/5 pt-3',
                                'max-md:flex-wrap max-md:gap-4',
                                'max-sm:gap-2.5',
                            )}>
                                <span
                                    className={cn(
                                        'flex cursor-pointer items-center gap-1.5 text-[13px] text-muted-foreground transition-all duration-200 select-none hover:text-primary hover:-translate-y-0.5',
                                        'max-md:text-xs max-sm:text-[11px]',
                                        likedComments.has(comment.id || 0) && 'text-primary font-semibold',
                                    )}
                                    onClick={() => handleLike(comment)}
                                    title={likedComments.has(comment.id || 0) ? t('unlike') : t('like')}
                                >
                                    <XIcon name="carbon:thumbs-up" size={16}/>
                                    {comment.likeCount || 0}
                                </span>
                                <span
                                    className="flex cursor-pointer items-center gap-1.5 text-[13px] text-muted-foreground transition-all duration-200 select-none hover:text-primary hover:-translate-y-0.5 max-md:text-xs max-sm:text-[11px]"
                                    onClick={() => handleReply(comment)}
                                    title={t('reply')}
                                >
                                    <XIcon name="carbon:chat" size={16}/>
                                    {t('reply')}
                                </span>
                                <span
                                    className="flex cursor-pointer items-center gap-1.5 text-[13px] text-muted-foreground transition-all duration-200 select-none hover:text-primary hover:-translate-y-0.5 max-md:text-xs max-sm:text-[11px]"
                                    onClick={() => handleShare(comment)}
                                    title={t('share')}
                                >
                                    <XIcon name="carbon:share" size={16}/>
                                    {t('share')}
                                </span>
                                {/* 查看回复按钮 */}
                                {comment.replyCount && comment.replyCount > 0 ? (
                                    <span
                                        className="flex cursor-pointer items-center gap-1.5 text-[13px] font-medium text-primary transition-all duration-200 select-none hover:text-primary max-md:text-xs max-sm:text-[11px]"
                                        onClick={() => toggleExpand(comment)}
                                        title={isExpanded(comment) ? t('hide_replies') : t('view_replies', {count: comment.replyCount})}
                                    >
                                        <XIcon
                                            name={isExpanded(comment) ? 'carbon:chevron-up' : 'carbon:chevron-down'}
                                            size={18}
                                        />
                                        {isExpanded(comment)
                                            ? t('hide_replies')
                                            : t('view_replies', {count: comment.replyCount})
                                        }
                                    </span>
                                ) : null}
                            </div>

                            {/* 回复表单 */}
                            {replyingCommentId === comment.id && (
                                <div className="mt-4 border-t border-primary/8 pt-4 max-md:mt-3 max-md:pt-3">
                                    <textarea
                                        value={replyContent}
                                        onChange={(e) => setReplyContent(e.target.value)}
                                        rows={3}
                                        placeholder={t('write_comment')}
                                        className={cn(
                                            'w-full min-h-20 resize-y rounded-lg border border-border bg-muted px-4 py-3 text-sm text-foreground',
                                            'transition-all duration-300',
                                            'hover:border-primary',
                                            'focus:border-primary focus:outline-none focus:ring-[3px] focus:ring-primary/15',
                                            'disabled:cursor-not-allowed disabled:opacity-60 disabled:bg-background',
                                        )}
                                        disabled={submitting}
                                        onKeyDown={(e) => {
                                            if (e.ctrlKey || e.metaKey) {
                                                e.preventDefault();
                                                submitReply(comment);
                                            }
                                        }}
                                    />
                                    <div className="mt-2 mb-3 text-end text-xs text-muted-foreground">
                                        {replyContent.length} / 1000
                                    </div>
                                    <div className="flex justify-end gap-3 max-md:flex-col max-md:gap-2">
                                        <Button
                                            size="sm"
                                            onClick={() => submitReply(comment)}
                                            disabled={submitting}
                                        >
                                            {submitting ? '...' : t('submit_comment')}
                                        </Button>
                                        <Button
                                            variant="outline"
                                            size="sm"
                                            onClick={cancelReply}
                                            disabled={submitting}
                                        >
                                            {t('cancel')}
                                        </Button>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* 递归渲染子评论 */}
                    {hasChildren(comment) && isExpanded(comment) && (
                        <div className={cn(
                            'relative mt-5 ps-16',
                            'max-md:ps-12 max-md:mt-4',
                            'max-sm:ps-9 max-sm:mt-3',
                        )}>
                            {/* Vertical line */}
                            <div className="absolute top-0 start-8 h-full w-0.5 bg-linear-to-b from-primary/20 to-primary/5 max-md:start-6 max-sm:start-4.5 max-sm:w-[1.5px]"/>

                            {/* 加载中提示 */}
                            {isLoading(comment) && (
                                <div className="flex items-center justify-center gap-3 py-5 text-sm text-muted-foreground">
                                    <Spinner size="sm" className="text-primary"/>
                                    <span>{t('loading')}</span>
                                </div>
                            )}
                            {/* 子评论列表 */}
                            {!isLoading(comment) && comment.children && (
                                <CommentTree
                                    comments={comment.children}
                                    onReply={onReply}
                                    onLoadChildren={onLoadChildren}
                                />
                            )}
                        </div>
                    )}
                </div>
            ))}
        </div>
    );
};

export default CommentTree;

// frontend/app/vue3/src/components/CommentSection/CommentTree.vue
<script setup lang="ts">
import {useMessage} from 'naive-ui'
import {ref} from 'vue'

import {$t} from '@/locales'
import {ContentViewer} from '@/components/ContentViewer'
import type {commentservicev1_Comment} from "@/api/generated/app/service/v1"
import {formatDate} from "@/utils/date";

// --- Props ---
defineProps<{
  comments: commentservicev1_Comment[]
}>()

// --- Emits ---
const emit = defineEmits<{
  (e: 'reply', comment: commentservicev1_Comment, content: string): void
  (e: 'load-children', comment: commentservicev1_Comment): Promise<void>
}>()

// --- 状态 ---
const message = useMessage()
const replyingCommentId = ref<number | null>(null)
const replyContent = ref('')
const submitting = ref(false)
const expandedComments = ref<Set<number>>(new Set()) // 已展开的评论 ID
const loadingChildren = ref<Set<number>>(new Set()) // 正在加载子评论的评论 ID

function hasChildren(comment: commentservicev1_Comment): boolean {
  // 有子评论数据，或者有回复数量但未加载
  return !!comment.children || (comment.replyCount && comment.replyCount > 0)
}

function isOwnerReply(comment: commentservicev1_Comment): boolean {
  // 博主回复：authorType 为 ADMIN 且有 replyToId (回复他人)
  return comment.authorType === 'AUTHOR_TYPE_ADMIN' && !!comment.replyToId
}

function isExpanded(comment: commentservicev1_Comment): boolean {
  return expandedComments.value.has(comment.id)
}

function isLoading(comment: commentservicev1_Comment): boolean {
  return loadingChildren.value.has(comment.id)
}

// --- 方法 ---
function handleReply(comment: commentservicev1_Comment) {
  replyingCommentId.value = comment.id
  replyContent.value = ''
}

function cancelReply() {
  replyingCommentId.value = null
  replyContent.value = ''
}

async function submitReply(comment: commentservicev1_Comment) {
  if (!replyContent.value.trim()) {
    message.warning($t('comment.empty_content'))
    return
  }

  if (submitting.value) return

  submitting.value = true
  try {
    emit('reply', comment, replyContent.value.trim())
    cancelReply()
    message.success($t('comment.comment_posted'))
  } catch (error) {
    console.error('Submit reply failed:', error)
    message.error($t('comment.submit_comment_failed'))
  } finally {
    submitting.value = false
  }
}

function handleShare(comment: commentservicev1_Comment) {
  // 复制链接到剪贴板
  const url = window.location.href.split('#')[0]
  const commentUrl = `${url}#comment-${comment.id}`

  navigator.clipboard.writeText(commentUrl).then(() => {
    message.success($t('comment.link_copied'))
  }).catch(() => {
    message.error($t('comment.copy_failed'))
  })
}

// 切换展开/收起子评论
async function toggleExpand(comment: commentservicev1_Comment) {
  if (isExpanded(comment)) {
    // 收起
    expandedComments.value.delete(comment.id)
  } else {
    // 展开
    if (!comment.children && comment.replyCount && comment.replyCount > 0) {
      // 需要动态加载子评论
      loadingChildren.value.add(comment.id)
      try {
        await emit('load-children', comment)
        expandedComments.value.add(comment.id)
      } catch (error) {
        console.error('Load children failed:', error)
        message.error('加载回复失败')
      } finally {
        loadingChildren.value.delete(comment.id)
      }
    } else {
      // 已经有子评论数据，直接展开
      expandedComments.value.add(comment.id)
    }
  }
}
</script>

<template>
  <div class="comment-tree">
    <div v-for="comment in comments" :key="comment.id" class="comment-node">
      <!-- 评论主体 -->
      <div class="comment-item">
        <div class="comment-avatar">
          <n-avatar :size="48" round>
            {{ comment.authorName?.charAt(0) || 'U' }}
          </n-avatar>
        </div>
        <div class="comment-body">
          <div class="comment-header">
            <div class="author-info">
              <strong class="comment-author">
                <span v-if="isOwnerReply(comment)" class="owner-badge">
                  <span class="i-carbon:badge"/>
                  {{ $t('comment.owner_reply') }}
                </span>
                {{ comment.authorName }}
              </strong>
              <span v-if="comment.location && !isOwnerReply(comment)"
                    class="comment-location">{{ comment.location }}</span>
            </div>
            <span class="comment-date">{{ formatDate(comment.createdAt) }}</span>
          </div>
          <div class="comment-content">
            <ContentViewer :content="comment.content" type="text"/>
          </div>
          <div class="comment-actions">
            <span class="action-item">
              <span class="i-carbon:thumbs-up"/>
              {{ comment.likeCount || 0 }}
            </span>
            <span class="action-item" @click="handleReply(comment)">
              <span class="i-carbon:chat"/>
              {{ $t('comment.reply') }}
            </span>
            <span class="action-item" @click="handleShare(comment)">
              <span class="i-carbon:share"/>
              {{ $t('comment.share') }}
            </span>
            <!-- 查看回复按钮 -->
            <span
              v-if="comment.replyCount && comment.replyCount > 0"
              class="action-item view-replies"
              @click="toggleExpand(comment)"
            >
              <span :class="isExpanded(comment) ? 'i-carbon:chevron-up' : 'i-carbon:chevron-down'"/>
              {{
                isExpanded(comment) ? $t('comment.hide_replies') : $t('comment.view_replies', {count: comment.replyCount})
              }}
            </span>
          </div>

          <!-- 回复表单 -->
          <div v-if="replyingCommentId === comment.id" class="reply-form">
            <n-input
              v-model:value="replyContent"
              type="textarea"
              :rows="3"
              :placeholder="$t('comment.write_comment')"
              size="small"
              :disabled="submitting"
              @keydown.ctrl.enter="submitReply(comment)"
            />
            <div class="reply-form-actions">
              <n-button
                size="small"
                type="primary"
                @click="submitReply(comment)"
                :loading="submitting"
              >
                {{ $t('comment.submit_comment') }}
              </n-button>
              <n-button
                size="small"
                @click="cancelReply"
                :disabled="submitting"
              >
                {{ $t('comment.cancel') }}
              </n-button>
            </div>
          </div>
        </div>
      </div>

      <!-- 递归渲染子评论 -->
      <div v-if="hasChildren(comment) && isExpanded(comment)" class="comment-children">
        <!-- 加载中提示 -->
        <div v-if="isLoading(comment)" class="loading-children">
          <n-spin size="small"/>
          <span>{{ $t('comment.loading') }}</span>
        </div>
        <!-- 子评论列表 -->
        <template v-else-if="comment.children">
          <CommentTree :comments="comment.children"/>
        </template>
      </div>
    </div>
  </div>
</template>

<style scoped lang="less">
.comment-tree {
  display: flex;
  flex-direction: column;
  gap: 28px;
}

.comment-node {
  display: flex;
  flex-direction: column;
}

.comment-item {
  display: flex;
  gap: 20px;
  padding: 28px;
  background: linear-gradient(135deg,
  var(--color-bg) 0%,
  rgba(168, 85, 247, 0.02) 100%);
  border-radius: 16px;
  border: 1px solid rgba(168, 85, 247, 0.08);
  transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
  position: relative;
  overflow: hidden;

  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 4px;
    height: 100%;
    background: linear-gradient(180deg,
    var(--color-brand) 0%,
    #764ba2 100%);
    opacity: 0;
    transition: opacity 0.3s;
  }

  &:hover {
    border-color: var(--color-brand);
    box-shadow: 0 8px 24px rgba(168, 85, 247, 0.12),
    0 4px 12px rgba(0, 0, 0, 0.04);
    transform: translateX(4px) translateY(-2px);

    &::before {
      opacity: 1;
    }
  }

  .comment-avatar {
    flex-shrink: 0;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;

    &::after {
      content: '';
      position: absolute;
      top: 50%;
      left: 50%;
      width: calc(100% + 6px);
      height: calc(100% + 6px);
      transform: translate(-50%, -50%);
      border-radius: 50%;
      background: linear-gradient(135deg,
      var(--color-brand) 0%,
      #764ba2 100%);
      opacity: 0.15;
      filter: blur(6px);
      z-index: 0;
    }

    :deep(.n-avatar) {
      position: relative;
      z-index: 1;
      background: linear-gradient(135deg,
      var(--color-brand) 0%,
      #764ba2 100%);
      color: #fff;
      font-weight: 600;
      box-shadow: 0 2px 8px rgba(168, 85, 247, 0.2);
      border: 1px solid rgba(255, 255, 255, 0.1);
    }
  }

  .comment-body {
    flex: 1;
    min-width: 0;
    position: relative;

    .comment-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 16px;
      padding-bottom: 12px;
      border-bottom: 1px solid rgba(168, 85, 247, 0.08);

      .author-info {
        display: flex;
        align-items: center;
        gap: 12px;
        flex-wrap: wrap;

        .comment-author {
          font-size: 17px;
          font-weight: 600;
          color: var(--color-text-primary);
          letter-spacing: -0.2px;
          display: flex;
          align-items: center;
          gap: 8px;

          .owner-badge {
            background: linear-gradient(135deg,
            var(--color-brand) 0%,
            #764ba2 100%);
            color: #fff;
            font-size: 11px;
            font-weight: 700;
            padding: 3px 10px;
            border-radius: 8px;
            letter-spacing: 0;
            display: inline-flex;
            align-items: center;
            gap: 4px;
            box-shadow: 0 2px 8px rgba(168, 85, 247, 0.3);

            span[class^="i-"] {
              font-size: 13px;
            }
          }
        }

        .comment-location {
          font-size: 12px;
          color: var(--color-text-secondary);
          display: flex;
          align-items: center;
          gap: 4px;

          &::before {
            content: '📍';
            font-size: 11px;
          }
        }
      }

      .comment-date {
        font-size: 13px;
        color: var(--color-text-secondary);
        display: flex;
        align-items: center;
        gap: 6px;

        &::before {
          content: '📅';
          font-size: 12px;
        }
      }
    }

    .comment-content {
      font-size: 15px;
      line-height: 1.8;
      color: var(--color-text-primary);
      padding-left: 4px;
      margin-bottom: 16px;
    }

    .comment-actions {
      display: flex;
      gap: 20px;
      padding-top: 12px;
      border-top: 1px solid rgba(168, 85, 247, 0.05);

      .action-item {
        display: flex;
        align-items: center;
        gap: 6px;
        font-size: 13px;
        color: var(--color-text-secondary);
        cursor: pointer;
        transition: all 0.2s;

        span[class^="i-"] {
          font-size: 16px;
        }

        &:hover {
          color: var(--color-brand);
          transform: translateY(-1px);
        }

        &.view-replies {
          color: var(--color-brand);
          font-weight: 500;

          span[class^="i-"] {
            font-size: 18px;
          }

          &:hover {
            color: var(--color-brand-dark);
          }
        }
      }
    }

    // 回复表单
    .reply-form {
      margin-top: 16px;
      padding-top: 16px;
      border-top: 1px solid rgba(168, 85, 247, 0.08);

      :deep(.n-input) {
        border-radius: 8px;
        background: var(--color-bg);
      }

      .reply-form-actions {
        display: flex;
        gap: 12px;
        margin-top: 12px;
        justify-content: flex-end;

        :deep(.n-button) {
          min-width: 80px;
        }
      }
    }

    // 加载中提示
    .loading-children {
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 20px;
      color: var(--color-text-secondary);
      font-size: 14px;
      justify-content: center;

      :deep(.n-spin) {
        color: var(--color-brand);
      }
    }
  }
}

// 子评论嵌套样式
.comment-children {
  margin-top: 20px;
  padding-left: 64px;
  position: relative;

  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 32px;
    width: 2px;
    height: 100%;
    background: linear-gradient(180deg,
    rgba(168, 85, 247, 0.2) 0%,
    rgba(168, 85, 247, 0.05) 100%);
  }

  .comment-node {
    margin-bottom: 20px;

    &:last-child {
      margin-bottom: 0;
    }
  }
}

// 响应式
@media (max-width: 768px) {
  .comment-item {
    padding: 24px;
    gap: 16px;

    .comment-avatar {
      :deep(.n-avatar) {
        --n-size: 44px !important;
      }
    }

    .comment-body {
      .comment-header {
        flex-direction: column;
        align-items: flex-start;
        gap: 8px;
        margin-bottom: 12px;
        padding-bottom: 10px;

        .author-info {
          flex-direction: column;
          align-items: flex-start;
          gap: 6px;
        }

        .comment-author {
          font-size: 16px;
        }

        .comment-date {
          font-size: 12px;
        }
      }

      .comment-content {
        font-size: 14px;
        line-height: 1.7;
      }

      .comment-actions {
        gap: 16px;

        .action-item {
          font-size: 12px;
        }
      }
    }
  }

  .comment-children {
    padding-left: 48px;
    margin-top: 16px;

    &::before {
      left: 24px;
    }
  }
}

@media (max-width: 640px) {
  .comment-item {
    padding: 18px;
    gap: 12px;

    .comment-avatar {
      :deep(.n-avatar) {
        --n-size: 40px !important;
      }
    }

    .comment-body {
      .comment-header {
        margin-bottom: 10px;
        padding-bottom: 8px;

        .comment-author {
          font-size: 15px;
        }

        .comment-date {
          font-size: 11px;
        }
      }

      .comment-content {
        font-size: 13px;
        line-height: 1.65;
      }
    }
  }

  .comment-children {
    padding-left: 36px;
    margin-top: 12px;

    &::before {
      left: 18px;
    }
  }
}
</style>
