// frontend/app/vue/app/pages/tag/[id].vue
<script setup lang="ts">
import { fetchTag, getTagTranslation } from '@/api/composables/tag'

const { t } = useI18n()
const localePath = useLocalePath()
const route = useRoute()

const tag = ref<any>(null)
const loading = ref(true)
const tagId = computed(() => Number(route.params.id))

// 动态标题
const tagTitle = computed(() =>
  tag.value ? getTagName(tag.value) : t('page.tags.tags_list')
)
useHead({ title: () => tagTitle.value })

function getTagName(tagData: any) {
  const translation = getTagTranslation(tagData)
  return translation?.name || t('page.tags.tag_untitled')
}

function getTagDescription(tagData: any) {
  const translation = getTagTranslation(tagData)
  return translation?.description || ''
}

async function loadTag() {
  if (!tagId.value) return
  loading.value = true
  try {
    tag.value = await fetchTag(tagId.value) as any
  } catch (e) {
    console.error('[Tag Detail] 加载失败:', e)
  } finally {
    loading.value = false
  }
}

function handleBack() {
  navigateTo(localePath('/tag'))
}

onMounted(loadTag)
</script>

<template>
  <div class="w-full">
    <!-- Loading -->
    <div v-if="loading" class="w-full py-20">
      <LayoutSectionContainer>
        <div class="mx-auto max-w-3xl space-y-4">
          <UiSkeleton class="h-10 w-1/2" />
          <UiSkeleton class="h-5 w-3/4" />
        </div>
      </LayoutSectionContainer>
    </div>

    <!-- Tag Detail -->
    <template v-else-if="tag">
      <LayoutPageHero
        :title="getTagName(tag)"
        :description="getTagDescription(tag) || undefined"
        :icon="`carbon:${tag.icon || 'tag'}`"
        :icon-size="56"
        size="lg"
        :accent-color="tag.color || undefined"
      >
        <template #default>
          <div class="flex items-center gap-2">
            <XIcon icon="carbon:document" :size="16" />
            <span>{{ tag.postCount || 0 }} {{ t('page.posts.articles') }}</span>
          </div>
        </template>
      </LayoutPageHero>

      <LayoutSectionContainer>
        <!-- Back Button -->
        <div class="mb-8">
          <LayoutBackButton
            :label="t('page.categories.back_to_list')"
            :on-click="handleBack"
          />
        </div>

        <!-- Posts List with Pagination -->
        <PostList
          v-if="tagId"
          :key="tagId"
          :initial-page-size="10"
          :tag-id="tagId"
          from="tag"
        />
      </LayoutSectionContainer>
    </template>

    <!-- Tag not found / Invalid ID -->
    <div v-else class="w-full py-20">
      <LayoutSectionContainer>
        <UiAppEmpty variant="error" :description="t('page.tags.no_tags')" />
      </LayoutSectionContainer>
    </div>
  </div>
</template>

// frontend/app/react/src/app/[locale]/tag/[id]/page.tsx
'use client';

import {useState, useEffect, useMemo} from 'react';
import {useParams} from 'next/navigation';
import {useTranslations} from 'next-intl';
import {Button} from '@/components/ui/button';
import {ArrowLeft} from 'lucide-react';
import {AppEmpty} from '@/components/ui';

import {useI18nRouter} from "@/i18n/helpers";
import PageHero from '@/components/layout/PageHero';
import {XIcon} from '@/plugins/xicon';

import {fetchTag, getTranslation as getTagTranslation} from '@/api/hooks/tag';
import PostListWithPagination from '@/components/post/PostList';
import type {contentservicev1_Tag} from "@/api/generated/app/service/v1";

export default function TagDetailPage() {
    const t = useTranslations('page');
    const params = useParams();
    const router = useI18nRouter();

    const [loading, setLoading] = useState(false);
    const [tag, setTag] = useState<contentservicev1_Tag | null>(null);

    const tagId = useMemo(() => {
        const id = params?.id;
        return id ? parseInt(id as string) : null;
    }, [params?.id]);

    async function loadTag() {
        if (!tagId) return;

        setLoading(true);
        try {
            const tagData = await fetchTag(tagId!) as unknown as contentservicev1_Tag;
            setTag(tagData);
        } catch (error) {
            console.error('Load tag failed:', error);
        } finally {
            setLoading(false);
        }
    }

    function handleBack() {
        router.push('/tag');
    }

    useEffect(() => {
        loadTag();
    }, [tagId]);

    if (!tagId) {
        return <AppEmpty variant="error" description="Invalid tag ID"/>;
    }

    return (
        <div className="w-full">
            <PageHero
                title={getTagTranslation(tag)?.name || t('tags.tag_untitled')}
                description={getTagTranslation(tag)?.description || undefined}
                icon={`carbon:${tag?.icon || 'tag'}`}
                iconSize={56}
                size="lg"
                accentColor={tag?.color || undefined}
                meta={
                    <div className="flex items-center gap-2">
                        <XIcon name="carbon:document" size={16}/>
                        <span>{tag?.postCount || 0} {t('posts.articles')}</span>
                    </div>
                }
            />

            {/* Posts Section */}
            <div className="w-full max-w-[1200px] mx-auto px-8 py-12 max-md:px-4">
                {/* Back Button */}
                <div className="mb-8">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={handleBack}
                        className="gap-2"
                    >
                        <ArrowLeft className="h-4 w-4"/>
                        {t('categories.back_to_list')}
                    </Button>
                </div>

                {/* Posts List with Pagination */}
                {tagId && (
                    <PostListWithPagination
                        key={tagId}
                        initialPageSize={10}
                        pageSizes={[10, 20, 30, 40]}
                        tagId={tagId}
                        from="tag"
                    />
                )}
            </div>
        </div>
    );
}
