// frontend/app/vue/app/pages/settings.vue
<script setup lang="ts">
import { XIcon } from '@/plugins/xicon'
import { usePreferences } from '@/core/preferences/use-preferences'

const { t } = useI18n()
const { locale } = useI18n()
const localePath = useLocalePath()
const switchLocalePath = useSwitchLocalePath()

const { theme: themePref, setThemeMode } = usePreferences()

const activeMenu = ref<'account' | 'message' | 'preference'>('account')

const menuItems = [
  { key: 'account', icon: 'carbon:user', label: t('settings.menu.account') },
  { key: 'message', icon: 'carbon:email', label: t('settings.menu.message') },
  { key: 'preference', icon: 'carbon:settings', label: t('settings.menu.preference') },
]
</script>

<template>
  <div class="w-full py-8 max-md:py-4">
    <div class="w-full max-w-[1200px] mx-auto grid grid-cols-[220px_1fr_280px] gap-6 px-8 max-md:grid-cols-1 max-md:px-4">
      <!-- Left nav -->
      <aside class="max-md:hidden">
        <nav class="space-y-1">
          <div
            v-for="item in menuItems"
            :key="item.key"
            class="flex cursor-pointer items-center gap-3 rounded-lg border px-3 py-2.5 text-sm font-medium transition-all"
            :class="activeMenu === item.key
              ? 'border-primary/20 bg-primary/5 text-primary'
              : 'border-transparent text-muted-foreground hover:bg-muted hover:text-foreground'"
            @click="activeMenu = item.key as any"
          >
            <div class="flex h-8 w-8 items-center justify-center rounded-md bg-primary/10 text-primary">
              <XIcon :name="item.icon" :size="18" />
            </div>
            <span>{{ item.label }}</span>
          </div>
        </nav>
      </aside>

      <!-- Main content -->
      <main class="min-w-0">
        <!-- Account settings -->
        <template v-if="activeMenu === 'account'">
          <div class="mb-8">
            <h1 class="mb-2 text-2xl font-bold text-foreground">{{ t('settings.account.title') }}</h1>
            <p class="text-sm text-muted-foreground">{{ t('settings.account.subtitle') }}</p>
          </div>
          <div class="mb-8">
            <h2 class="mb-2 text-lg font-semibold text-foreground">{{ t('settings.account.section_title') }}</h2>
            <p class="mb-4 text-sm text-muted-foreground">{{ t('settings.account.section_desc') }}</p>
            <div class="space-y-3">
              <UiSettingRow :label="t('settings.account.password')" :description="t('settings.account.password_not_set')">
                <UiButton variant="outline" size="sm">{{ t('settings.account.edit') }}</UiButton>
              </UiSettingRow>
              <UiSettingRow :label="t('settings.account.bind_phone')" :description="t('settings.account.password_not_set')">
                <UiButton variant="outline" size="sm">{{ t('settings.account.edit') }}</UiButton>
              </UiSettingRow>
              <UiSettingRow :label="t('settings.account.bind_email')" :description="t('settings.account.email_not_bound')">
                <UiButton variant="outline" size="sm">{{ t('settings.account.edit') }}</UiButton>
              </UiSettingRow>
            </div>
          </div>
        </template>

        <!-- Message settings -->
        <template v-if="activeMenu === 'message'">
          <div class="mb-8">
            <h1 class="mb-2 text-2xl font-bold text-foreground">{{ t('settings.message.title') }}</h1>
            <p class="text-sm text-muted-foreground">{{ t('settings.message.subtitle') }}</p>
          </div>
          <div class="mb-8">
            <h2 class="mb-2 text-lg font-semibold text-foreground">{{ t('settings.message.email_notifications') }}</h2>
            <div class="space-y-3">
              <UiSettingRow :label="t('settings.message.system_messages')" />
              <UiSettingRow :label="t('settings.message.comment_notifications')" />
              <UiSettingRow :label="t('settings.message.activity_updates')" />
              <UiSettingRow :label="t('settings.message.recommended_content')" />
            </div>
          </div>
        </template>

        <!-- Preference settings -->
        <template v-if="activeMenu === 'preference'">
          <div class="mb-8">
            <h1 class="mb-2 text-2xl font-bold text-foreground">{{ t('settings.preference.title') }}</h1>
            <p class="text-sm text-muted-foreground">{{ t('settings.preference.subtitle') }}</p>
          </div>
          <div class="mb-8">
            <h2 class="mb-2 text-lg font-semibold text-foreground">{{ t('settings.preference.theme_settings') }}</h2>
            <p class="mb-4 text-sm text-muted-foreground">{{ t('settings.preference.theme_desc') }}</p>
            <UiSettingRow :label="t('settings.preference.theme')">
              <UiSelect v-model="themePref.mode" @update:model-value="(v: any) => setThemeMode(v)">
                <UiSelectTrigger class="w-[180px] h-8">
                  <UiSelectValue />
                </UiSelectTrigger>
                <UiSelectContent>
                  <UiSelectItem value="light">{{ t('settings.preference.theme_light') }}</UiSelectItem>
                  <UiSelectItem value="dark">{{ t('settings.preference.theme_dark') }}</UiSelectItem>
                  <UiSelectItem value="auto">{{ t('settings.preference.theme_auto') }}</UiSelectItem>
                </UiSelectContent>
              </UiSelect>
            </UiSettingRow>
          </div>
        </template>
      </main>

      <!-- Right help -->
      <aside class="max-md:hidden">
        <div class="sticky top-24 rounded-lg border border-border bg-card p-5">
          <h3 class="mb-3 text-base font-bold text-foreground">{{ t('settings.help.title') }}</h3>
          <h4 class="mb-2 text-sm font-semibold text-foreground">{{ t('settings.help.account_password') }}</h4>
          <ul class="mb-4 space-y-2 text-xs">
            <li class="text-muted-foreground hover:text-foreground">1. {{ t('settings.help.q1') }}</li>
            <li class="text-muted-foreground hover:text-foreground">2. {{ t('settings.help.q2') }}</li>
            <li class="text-muted-foreground hover:text-foreground">3. {{ t('settings.help.q3') }}</li>
            <li class="text-muted-foreground hover:text-foreground">4. {{ t('settings.help.q4') }}</li>
          </ul>
        </div>
      </aside>
    </div>
  </div>
</template>

// frontend/app/react/src/app/[locale]/settings/page.tsx
'use client';

import {useState, useMemo} from 'react';
import {useTranslations, useLocale} from 'next-intl';
import {Switch} from '@/components/ui/switch';
import {Select, SelectContent, SelectItem, SelectTrigger, SelectValue} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import SettingRow from '@/components/ui/setting-row';
import XIcon from '@/plugins/xicon';

import {usePreferences} from '@/core/preferences';
import {useI18n} from '@/i18n';
import type {ThemeModeType, SupportedLanguagesType} from '@/core/preferences';

interface MenuItem {
    key: string;
    icon: string;
    label: string;
}

export default function SettingsPage() {
    const t = useTranslations('settings');
    const locale = useLocale();

    const {
        theme: themePref,
        content: contentPref,
        setThemeMode,
        updateContent,
        setLanguage,
        resetPreferences,
    } = usePreferences();
    const {changeLocale} = useI18n();

    const [activeMenu, setActiveMenu] = useState<'account' | 'message' | 'preference'>('account');

    const menuItems: MenuItem[] = useMemo(() => [
        {key: 'account', icon: 'carbon:user', label: t('menu.account')},
        {key: 'message', icon: 'carbon:email', label: t('menu.message')},
        {key: 'preference', icon: 'carbon:settings', label: t('menu.preference')}
    ], [t]);

    const themeOptions = useMemo(() => [
        {value: 'light' as ThemeModeType, label: t('preference.theme_light')},
        {value: 'dark' as ThemeModeType, label: t('preference.theme_dark')},
        {value: 'auto' as ThemeModeType, label: t('preference.theme_auto')},
    ], [t]);

    const languageOptions = useMemo(() => [
        {value: 'zh-CN' as SupportedLanguagesType, label: t('preference.language_chinese')},
        {value: 'en-US' as SupportedLanguagesType, label: t('preference.language_english')},
    ], [t]);

    const handleThemeChange = (mode: ThemeModeType) => {
        setThemeMode(mode);
    };

    const handleLanguageChange = (newLocale: SupportedLanguagesType) => {
        setLanguage(newLocale);
        if (newLocale !== locale) {
            changeLocale(newLocale);
        }
    };

    return (
        <div className="w-full py-8 max-md:py-4">
            <div className="w-full max-w-[1200px] mx-auto grid grid-cols-[220px_1fr_280px] gap-6 px-8 max-md:grid-cols-1 max-md:px-4">
                {/* 左侧导航 */}
                <aside className="max-md:hidden">
                    <nav className="space-y-1">
                        {menuItems.map((item) => (
                            <div
                                key={item.key}
                                className={`flex cursor-pointer items-center gap-3 rounded-lg border border-transparent px-3 py-2.5 text-sm font-medium transition-all ${
                                    activeMenu === item.key
                                        ? 'border-primary/20 bg-primary/5 text-primary'
                                        : 'text-muted-foreground hover:bg-muted hover:text-foreground'
                                }`}
                                onClick={() => setActiveMenu(item.key as 'account' | 'message' | 'preference')}
                            >
                                <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary/10 text-primary">
                                    <XIcon name={item.icon} size={18}/>
                                </div>
                                <span>{item.label}</span>
                            </div>
                        ))}
                    </nav>
                </aside>

                {/* 中间内容区 */}
                <main className="min-w-0">
                    {/* 账号设置 */}
                    {activeMenu === 'account' && (
                        <>
                            <div className="mb-8">
                                <h1 className="mb-2 text-2xl font-bold text-foreground">{t('account.title')}</h1>
                                <p className="text-sm text-muted-foreground">{t('account.subtitle')}</p>
                            </div>
                            <div className="mb-8">
                                <h2 className="mb-2 text-lg font-semibold text-foreground">{t('account.section_title')}</h2>
                                <p className="mb-4 text-sm text-muted-foreground">{t('account.section_desc')}</p>
                                <div className="space-y-3">
                                    <SettingRow label={t('account.password')} description={t('account.password_not_set')}>
                                        <Button variant="outline" size="sm">{t('account.edit')}</Button>
                                    </SettingRow>
                                    <SettingRow label={t('account.bind_phone')} description={t('account.password_not_set')}>
                                        <Button variant="outline" size="sm">{t('account.edit')}</Button>
                                    </SettingRow>
                                    <SettingRow label={t('account.bind_email')} description={t('account.email_not_bound')}>
                                        <Button variant="outline" size="sm">{t('account.edit')}</Button>
                                    </SettingRow>
                                </div>
                            </div>
                            <div>
                                <h2 className="mb-4 text-lg font-semibold text-foreground">{t('account.third_party_title')}</h2>
                                <div className="grid grid-cols-3 gap-3 max-md:grid-cols-1">
                                    <div className="flex items-center gap-3 rounded-lg border border-border bg-card p-4">
                                        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-green-500">
                                            <XIcon name="fa:wechat" size={24} color="white"/>
                                        </div>
                                        <span className="text-sm font-medium text-foreground">
                                            {t('account.bind_wechat')}
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-3 rounded-lg border border-border bg-card p-4">
                                        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-red-500">
                                            <XIcon name="fa:weibo" size={24} color="white"/>
                                        </div>
                                        <span className="text-sm font-medium text-foreground">
                                            {t('account.bind_weibo')}
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-3 rounded-lg border border-border bg-card p-4">
                                        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-500">
                                            <XIcon name="fa:qq" size={24} color="white"/>
                                        </div>
                                        <span className="text-sm font-medium text-foreground">
                                            {t('account.bind_qq')}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </>
                    )}

                    {/* 消息设置 */}
                    {activeMenu === 'message' && (
                        <>
                            <div className="mb-8">
                                <h1 className="mb-2 text-2xl font-bold text-foreground">{t('message.title')}</h1>
                                <p className="text-sm text-muted-foreground">{t('message.subtitle')}</p>
                            </div>
                            <div className="mb-8">
                                <h2 className="mb-2 text-lg font-semibold text-foreground">{t('message.email_notifications')}</h2>
                                <p className="mb-4 text-sm text-muted-foreground">{t('message.email_notifications_desc')}</p>
                                <div className="space-y-3">
                                    <SettingRow label={t('message.system_messages')}>
                                        <Switch defaultChecked/>
                                    </SettingRow>
                                    <SettingRow label={t('message.comment_notifications')}>
                                        <Switch defaultChecked/>
                                    </SettingRow>
                                    <SettingRow label={t('message.activity_updates')}>
                                        <Switch defaultChecked/>
                                    </SettingRow>
                                    <SettingRow label={t('message.recommended_content')}>
                                        <Switch defaultChecked/>
                                    </SettingRow>
                                </div>
                            </div>
                            <div>
                                <h2 className="mb-4 text-lg font-semibold text-foreground">{t('message.email_frequency')}</h2>
                                <SettingRow label={t('message.frequency_desc')}>
                                    <Select defaultValue="immediately">
                                        <SelectTrigger className="w-[180px] h-8">
                                            <SelectValue/>
                                        </SelectTrigger>
                                        <SelectContent>
                                            <SelectItem value="immediately">{t('message.frequency_immediately')}</SelectItem>
                                            <SelectItem value="daily">{t('message.frequency_daily')}</SelectItem>
                                            <SelectItem value="weekly">{t('message.frequency_weekly')}</SelectItem>
                                            <SelectItem value="monthly">{t('message.frequency_monthly')}</SelectItem>
                                        </SelectContent>
                                    </Select>
                                </SettingRow>
                            </div>
                        </>
                    )}

                    {/* 偏好设置 */}
                    {activeMenu === 'preference' && (
                        <>
                            <div className="mb-8">
                                <h1 className="mb-2 text-2xl font-bold text-foreground">{t('preference.title')}</h1>
                                <p className="text-sm text-muted-foreground">{t('preference.subtitle')}</p>
                            </div>
                            <div className="mb-8">
                                <h2 className="mb-2 text-lg font-semibold text-foreground">{t('preference.theme_settings')}</h2>
                                <p className="mb-4 text-sm text-muted-foreground">{t('preference.theme_desc')}</p>
                                <SettingRow label={t('preference.theme')}>
                                    <Select value={themePref.mode} onValueChange={(v) => handleThemeChange(v as ThemeModeType)}>
                                        <SelectTrigger className="w-[180px] h-8">
                                            <SelectValue/>
                                        </SelectTrigger>
                                        <SelectContent>
                                            {themeOptions.map(opt => (
                                                <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </SettingRow>
                            </div>
                            <div className="mb-8">
                                <h2 className="mb-2 text-lg font-semibold text-foreground">{t('preference.language_settings')}</h2>
                                <p className="mb-4 text-sm text-muted-foreground">{t('preference.language_desc')}</p>
                                <SettingRow label={t('preference.language')}>
                                    <Select value={locale as SupportedLanguagesType} onValueChange={(v) => handleLanguageChange(v as SupportedLanguagesType)}>
                                        <SelectTrigger className="w-[180px] h-8">
                                            <SelectValue/>
                                        </SelectTrigger>
                                        <SelectContent>
                                            {languageOptions.map(opt => (
                                                <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
                                            ))}
                                        </SelectContent>
                                    </Select>
                                </SettingRow>
                            </div>
                            <div className="mb-8">
                                <h2 className="mb-2 text-lg font-semibold text-foreground">{t('preference.content_preferences')}</h2>
                                <p className="mb-4 text-sm text-muted-foreground">{t('preference.content_desc')}</p>
                                <div className="space-y-3">
                                    <SettingRow label={t('preference.hide_sensitive_content')}>
                                        <Switch
                                            checked={contentPref.hideSensitiveContent}
                                            onCheckedChange={(checked) => updateContent({hideSensitiveContent: checked})}
                                        />
                                    </SettingRow>
                                    <SettingRow label={t('preference.compact_mode')}>
                                        <Switch
                                            checked={contentPref.compactMode}
                                            onCheckedChange={(checked) => updateContent({compactMode: checked})}
                                        />
                                    </SettingRow>
                                    <SettingRow label={t('preference.show_recommendations')}>
                                        <Switch
                                            checked={contentPref.showRecommendations}
                                            onCheckedChange={(checked) => updateContent({showRecommendations: checked})}
                                        />
                                    </SettingRow>
                                </div>
                            </div>
                            <SettingRow label={t('preference.reset_defaults')}>
                                <Button variant="destructive" size="sm" onClick={() => resetPreferences()}>
                                    {t('preference.reset')}
                                </Button>
                            </SettingRow>
                        </>
                    )}
                </main>

                {/* 右侧帮助区 */}
                <aside className="max-md:hidden">
                    <div className="sticky top-24 rounded-lg border border-border bg-card p-5">
                        <h3 className="mb-3 text-base font-bold text-foreground">{t('help.title')}</h3>
                        <h4 className="mb-2 text-sm font-semibold text-foreground">{t('help.account_password')}</h4>
                        <ul className="mb-4 space-y-1.5 text-xs text-muted-foreground">
                            <li>1. {t('help.q1')}</li>
                            <li>2. {t('help.q2')}</li>
                            <li>3. {t('help.q3')}</li>
                            <li>4. {t('help.q4')}</li>
                            <li>5. {t('help.q5')}</li>
                        </ul>
                        <h4 className="mb-2 text-sm font-semibold text-foreground">{t('help.other_issues')}</h4>
                        <ul className="space-y-1.5 text-xs text-muted-foreground">
                            <li>6. <a href="#" className="text-primary hover:underline">{t('help.q6')} {t('help.q6_link')}</a></li>
                            <li>7. <a href="#" className="text-primary hover:underline">{t('help.q7')} {t('help.q7_link')}</a></li>
                        </ul>
                    </div>
                </aside>
            </div>
        </div>
    );
}
