// frontend/app/taro/src/components/category/CategoryTree.tsx
import {View, Text} from '@tarojs/components';
import React, {useState} from 'react';
import {useTranslations} from '@/lib/next-intl-compat';

import {XIcon} from '@/plugins/xicon';
import {
    getCategoryName,
    getCategoryDescription,
    getCategoryThumbnail,
} from '@/api/hooks/category';
import type {contentservicev1_Category} from '@/api/generated/app/service/v1';

import {cn} from '@/lib/utils';
import Image from '@/components/ui/image';

interface CategoryTreeProps {
    categories: contentservicev1_Category[];
    level?: number;
    onCategoryClick?: (id: number) => void;
}

const levelMarginClass: Record<number, string> = {
    0: '',
    1: 'ml-8 max-md:ml-4',
    2: 'ml-16 max-md:ml-8',
    3: 'ml-24 max-md:ml-12',
};

const CategoryTree: React.FC<CategoryTreeProps> = ({
                                                       categories = [],
                                                       level = 0,
                                                       onCategoryClick
                                                   }) => {
    const t = useTranslations('page.categories');
    const [expandedCategories, setExpandedCategories] = useState<Set<number>>(new Set());

    const handleViewCategory = (id: number) => {
        onCategoryClick?.(id);
    };

    const toggleExpand = (e: React.MouseEvent, category: contentservicev1_Category) => {
        e.stopPropagation();
        if (category.children && category.children.length > 0) {
            const newExpanded = new Set(expandedCategories);
            if (newExpanded.has(category.id || 0)) {
                newExpanded.delete(category.id || 0);
            } else {
                newExpanded.add(category.id || 0);
            }
            setExpandedCategories(newExpanded);
        }
    };

    const isExpanded = (category: contentservicev1_Category) => {
        return expandedCategories.has(category.id || 0);
    };

    if (!categories || categories.length === 0) return null;

    return (
        <View className='flex flex-col gap-4 max-md:gap-3'>
            {categories.map((category) => {
                const hasChildren = !!(category.children && category.children.length > 0);
                const expanded = isExpanded(category);

                return (
                    <View
                      key={category.id}
                      className={cn('flex flex-col', levelMarginClass[level] || '')}
                    >
                        <View
                          className={cn(
                                'group relative flex cursor-pointer items-center overflow-hidden',
                                'rounded-xl border border-border/60 bg-card/50',
                                'transition-all duration-300',
                                'hover:bg-card hover:border-primary/30 hover:shadow-[0_8px_24px_-8px_hsl(var(--primary)/0.12)]',
                                expanded && 'border-primary/40 bg-card shadow-sm',
                            )}
                          onClick={() => handleViewCategory(category.id || 0)}
                        >
                            {/* 左侧色条指示器 */}
                            <View className={cn(
                                'w-1 self-stretch flex-shrink-0 bg-primary/0 transition-colors duration-300',
                                'group-hover:bg-primary',
                                expanded && 'bg-primary',
                            )}
                            />

                            <View className='flex flex-1 items-center gap-4 p-4 max-md:flex-col max-md:items-start max-md:p-3 max-md:gap-3'>
                                {/* 缩图：rounded-lg + 微间距，像精致狐裹的组件 */}
                                <View className={cn(
                                    'relative h-[90px] w-[130px] flex-shrink-0 overflow-hidden rounded-lg bg-muted',
                                    'max-md:h-[180px] max-md:w-full',
                                )}
                                >
                                    <Image
                                      src={getCategoryThumbnail(category)}
                                      alt={getCategoryName(category, t)}
                                      className='h-full w-full object-cover transition-transform duration-500 group-hover:scale-105'
                                    />
                                    <View className='absolute inset-0 bg-gradient-to-t from-black/30 via-transparent to-transparent opacity-0 transition-opacity duration-300 group-hover:opacity-100' />
                                </View>
                                {/* 文字区：垂直居中 */}
                                <View className='flex flex-1 flex-col gap-1.5 max-md:w-full'>
                                    <Text className={cn(
                                        'flex items-center gap-2 text-base font-semibold leading-tight text-foreground transition-colors',
                                        'group-hover:text-primary',
                                    )}
                                    >
                                        {getCategoryName(category, t)}
                                    </Text>
                                    <Text className='line-clamp-2 text-sm leading-relaxed text-muted-foreground'>
                                        {getCategoryDescription(category)}
                                    </Text>
                                    <View className='mt-1 flex items-center gap-3 text-xs text-muted-foreground'>
                                        <Text className='flex items-center gap-1'>
                                            <XIcon name='carbon:document' size={14} />
                                            {category.postCount || 0} {t('articles_count')}
                                        </Text>
                                        {hasChildren && (
                                            <Text className='flex items-center gap-1'>
                                                <XIcon name='carbon:folder' size={14} />
                                                {category.children!.length}
                                            </Text>
                                        )}
                                    </View>
                                </View>

                                {/* 右侧箭头：无子分类时显示 */}
                                {!hasChildren && (
                                    <View className='flex-shrink-0 text-muted-foreground/50 transition-all duration-300 group-hover:text-primary group-hover:translate-x-1 max-md:hidden'>
                                        <XIcon name='carbon:chevron-right' size={20} />
                                    </View>
                                )}
                            </View>

                            {/* 展开/收起按钮 */}
                            {hasChildren && (
                                <View
                                  className={cn(
                                        'flex items-center justify-center px-3',
                                        'border-l border-border text-muted-foreground',
                                        'transition-colors duration-200',
                                        'hover:bg-primary/5 hover:text-primary',
                                        'max-md:absolute max-md:top-2 max-md:right-2 max-md:z-10',
                                        'max-md:h-8 max-md:w-8 max-md:rounded-full max-md:border max-md:border-border',
                                        'max-md:bg-card/90 max-md:shadow-sm max-md:border-l',
                                        'max-md:hover:bg-primary max-md:hover:text-white max-md:hover:scale-110',
                                    )}
                                  onClick={(e) => toggleExpand(e, category)}
                                >
                                    <XIcon
                                      name={expanded ? 'carbon:chevron-down' : 'carbon:chevron-right'}
                                      size={20}
                                      className={cn('transition-transform duration-300', expanded && 'rotate-180')}
                                    />
                                </View>
                            )}
                        </View>

                        {/* 递归渲染子分类 */}
                        {hasChildren && expanded && (
                            <View className={cn(
                                'mt-2 overflow-hidden',
                                'border-l-2 border-primary/20 ml-3',
                            )}
                            >
                                <CategoryTree
                                  categories={category.children!}
                                  level={level + 1}
                                  onCategoryClick={onCategoryClick}
                                />
                            </View>
                        )}
                    </View>
                );
            })}
        </View>
    );
};

export default CategoryTree;

// frontend/app/vue3_old/src/components/CategoryTree/CategoryTree.vue
<script setup lang="ts">
import {ref} from 'vue'
import {useRouter} from 'vue-router'

import {$t} from '@/locales'
import type {Props} from "./types";
import type {
  contentservicev1_Category,
} from "@/api/generated/app/service/v1";
import {useCategoryStore} from '@/stores';


withDefaults(defineProps<Props>(), {
  level: 0
})

const router = useRouter()
const categoryStore = useCategoryStore()
const expandedCategories = ref<Set<number>>(new Set())

function handleViewCategory(id: number) {
  router.push(`/category/${id}`)
}

function toggleExpand(category: contentservicev1_Category) {
  if (category.children && category.children.length > 0) {
    if (expandedCategories.value.has(category.id)) {
      expandedCategories.value.delete(category.id)
    } else {
      expandedCategories.value.add(category.id)
    }
  }
}

function isExpanded(category: contentservicev1_Category) {
  return expandedCategories.value.has(category.id)
}
</script>

<template>
  <div class="category-tree">
    <div
      v-for="category in categories"
      :key="category.id"
      class="category-node"
      :class="[`level-${level}`]"
    >
      <div class="category-item" @click="handleViewCategory(category.id)">
        <div class="category-info">
          <div class="category-image">
            <img :src="categoryStore.getCategoryThumbnail(category)" :alt="categoryStore.getCategoryName(category)"/>
            <div class="image-overlay"/>
          </div>
          <div class="category-content">
            <h3 :class="{'has-children': category.children && category.children.length > 0}">
              {{ categoryStore.getCategoryName(category) }}
            </h3>
            <p class="description">{{ categoryStore.getCategoryDescription(category) }}</p>
            <div class="category-meta">
              <span class="meta-icon">
                <span class="i-carbon:document"/>
              </span>
              <span class="meta-text">{{
                  category.postCount || 0
                }} {{ $t('page.categories.articles_count') }}</span>
            </div>
          </div>
        </div>

        <!-- 展开/收起按钮 (如果有子分类) -->
        <button
          v-if="category.children && category.children.length > 0"
          class="expand-btn"
          @click.stop="toggleExpand(category)"
          :class="{ expanded: isExpanded(category) }"
        >
          <span :class="isExpanded(category) ? 'i-carbon:chevron-down' : 'i-carbon:chevron-right'"/>
        </button>
      </div>

      <!-- 递归渲染子分类 -->
      <transition name="slide">
        <CategoryTree
          v-if="category.children && category.children.length > 0 && isExpanded(category)"
          :categories="category.children"
          :level="level + 1"
        />
      </transition>
    </div>
  </div>
</template>

<style scoped lang="less">
.category-tree {
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.category-node {
  .category-item {
    background: var(--color-surface);
    border-radius: 16px;
    overflow: hidden;
    cursor: pointer;
    transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
    border: 1px solid var(--color-border);
    display: flex;
    align-items: center;
    justify-content: space-between;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);

    &:hover {
      transform: translateY(-4px);
      box-shadow: 0 12px 24px rgba(0, 0, 0, 0.1);
      border-color: var(--color-brand);

      .category-image {
        .image-overlay {
          opacity: 0.5;
        }

        img {
          transform: scale(1.08);
        }
      }

      h3 {
        color: var(--color-brand);
      }
    }

    .category-info {
      display: flex;
      gap: 20px;
      flex: 1;
      padding: 20px;
    }

    .category-image {
      position: relative;
      width: 160px;
      height: 120px;
      flex-shrink: 0;
      overflow: hidden;
      border-radius: 12px;
      background: var(--color-bg);

      img {
        width: 100%;
        height: 100%;
        object-fit: cover;
        transition: transform 0.5s cubic-bezier(0.4, 0, 0.2, 1);
      }

      .image-overlay {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: rgba(0, 0, 0, 0.15);
        transition: opacity 0.3s;
        opacity: 0;
      }
    }

    .category-content {
      flex: 1;
      display: flex;
      flex-direction: column;
      gap: 8px;

      h3 {
        font-size: 18px;
        font-weight: 700;
        margin: 0;
        color: var(--color-text-primary);
        line-height: 1.4;
        transition: color 0.3s;
        display: flex;
        align-items: center;
        gap: 8px;

        &.has-children {
          padding-left: 0;
        }
      }

      .description {
        color: var(--color-text-secondary);
        font-size: 14px;
        line-height: 1.6;
        margin: 0;
        display: -webkit-box;
        -webkit-line-clamp: 2;
        -webkit-box-orient: vertical;
        overflow: hidden;
      }

      .category-meta {
        display: flex;
        align-items: center;
        gap: 8px;
        font-size: 13px;
        color: var(--color-text-secondary);
        font-weight: 500;

        .meta-icon {
          display: flex;
          align-items: center;
          font-size: 16px;
          opacity: 0.8;
        }
      }
    }

    .expand-btn {
      padding: 12px;
      margin-right: 12px;
      background: transparent;
      border: 1px solid var(--color-border);
      border-radius: 8px;
      cursor: pointer;
      transition: all 0.3s;
      display: flex;
      align-items: center;
      justify-content: center;
      color: var(--color-text-secondary);

      &:hover {
        background: rgba(168, 85, 247, 0.1);
        border-color: var(--color-brand);
        color: var(--color-brand);
      }

      span[class^="i-"] {
        font-size: 20px;
        transition: transform 0.3s;
      }
    }
  }

  // 不同层级的缩进
  &.level-1 {
    margin-left: 40px;
  }

  &.level-2 {
    margin-left: 80px;
  }

  &.level-3 {
    margin-left: 120px;
  }
}

// Slide 动画
.slide-enter-active,
.slide-leave-active {
  transition: all 0.3s ease;
  overflow: hidden;
}

.slide-enter-from {
  opacity: 0;
  transform: translateY(-10px);
  max-height: 0;
}

.slide-enter-to {
  opacity: 1;
  transform: translateY(0);
  max-height: 1000px;
}

.slide-leave-from {
  opacity: 1;
  transform: translateY(0);
  max-height: 1000px;
}

.slide-leave-to {
  opacity: 0;
  transform: translateY(-10px);
  max-height: 0;
}

// 响应式
@media (max-width: 768px) {
  .category-node {
    .category-item {
      flex-direction: column;
      position: relative; // 为绝对定位的按钮提供参考

      .category-info {
        flex-direction: column;
        padding: 16px;
        gap: 12px;
        width: 100%;
      }

      .category-image {
        width: 100%;
        height: 200px;
        border-radius: 12px 12px 0 0; // 上圆角
      }

      .category-content {
        width: 100%;
        padding: 16px;
        gap: 8px;

        h3 {
          font-size: 17px;
          line-height: 1.3;
        }

        .description {
          font-size: 13px;
          line-height: 1.5;
        }

        .category-meta {
          font-size: 12px;
        }
      }

      .expand-btn {
        position: absolute;
        top: 12px;
        right: 12px;
        margin: 0;
        z-index: 10;
        background: var(--color-surface); // 使用主题色
        backdrop-filter: blur(8px);
        box-shadow: 0 2px 12px rgba(0, 0, 0, 0.15);
        border: 1px solid var(--color-border);
        color: var(--color-text-secondary);
        width: 36px;
        height: 36px;
        border-radius: 50%; // 圆形按钮
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);

        &:hover {
          background: var(--color-brand);
          border-color: var(--color-brand);
          color: #fff;
          transform: scale(1.1);
          box-shadow: 0 4px 16px rgba(102, 126, 234, 0.4);
        }

        span[class^="i-"] {
          font-size: 18px;
        }
      }
    }

    &.level-1 {
      margin-left: 16px;
    }

    &.level-2 {
      margin-left: 32px;
    }

    &.level-3 {
      margin-left: 48px;
    }
  }

  // 优化子分类的间距
  .category-tree {
    gap: 16px;
  }
}
</style>
