// frontend/app/taro/src/pages/tag/index.tsx
import {useState, useEffect} from 'react';
import {useTranslation} from 'react-i18next';
import {View, Text} from '@tarojs/components';

import {AppEmpty} from '@/components/ui';
import XIcon from '@/plugins/xicon';
import {Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationPrevious, PaginationNext} from '@/components/ui/pagination';
import {useI18nRouter} from "@/i18n/helpers";

import {fetchListTags, getTagTranslation} from '@/api/hooks/tag';
import {contentservicev1_ListTagResponse, contentservicev1_Tag} from '@/api/generated/app/service/v1';
export default function TagListPage() {
  const {t} = useTranslation();

  const router = useI18nRouter();

  const [loading, setLoading] = useState(false);
  const [tags, setTags] = useState<contentservicev1_Tag[]>([]);
  const [page, setPage] = useState(1);
  const [pageSize, _setPageSize] = useState(20);
  const [total, setTotal] = useState(0);

  async function loadTags() {
    setLoading(true);
    try {
      const res = await fetchListTags({
        paging: {
          page: page,
          pageSize: pageSize,
        },
        formValues: {
          status: 'TAG_STATUS_ACTIVE'
        },
        fieldMask: undefined,
        orderBy: undefined,
      }) as contentservicev1_ListTagResponse;
      setTags(res.items || []);
      setTotal(res.total || 0);
    } catch (error) {
      console.error('Load tags failed:', error);
    } finally {
      setLoading(false);
    }
  }

  function handleTagClick(id: number) {
    router.push(`/tag/${id}`);
  }

  function handlePageChange(newPage: number) {
    setPage(newPage);
    loadTags();
  }

  useEffect(() => {
    loadTags();
  }, [page, pageSize]);

  useEffect(() => {
    if (page !== 1) {
      setPage(1);
    }
  }, [pageSize]);

  return (
    <View className='tag-list-page'>
      {/* Hero Section */}
      <View className='hero-section'>
        <View className='hero-content'>
          <Text className='hero-title'>{t('page.tags.tags_list')}</Text>
          <Text className='hero-subtitle'>{t('page.tags.explore_all')}</Text>
          <View className='tag-stats'>
            <View className='stat-item'>
              <XIcon name='carbon:tag' size={20} />
              <Text>{total} {t('page.tags.total_tags')}</Text>
            </View>
          </View>
        </View>
      </View>

      {/* Tags Grid */}
      <View className='page-container'>
        {/* Loading Skeleton - TODO: 实现 Taro 骨架屏 */}
        {loading ? (
          <View className='tags-grid'>
            <Text>{t('common.loading')}</Text>
          </View>
        ) : (
          <>
            {tags.length > 0 && (
              <View className='tags-grid'>
                {tags.map((tag) => (
                  <View
                    key={tag.id}
                    className='tag-card'
                    style={{
                      borderColor: tag.color || 'rgba(0, 0, 0, 0.08)',
                      background: `linear-gradient(135deg, ${tag.color || '#f0f0f0'}15 0%, #ffffff 100%)`
                    }}
                    onClick={() => handleTagClick(tag.id || 0)}
                  >
                    <View className='tag-content'>
                      <Text>{getTagTranslation(tag)?.name || t('page.tags.tag_untitled')}</Text>
                      <Text className='tag-description'>
                        {getTagTranslation(tag)?.description || ''}
                      </Text>
                      <View className='tag-meta'>
                        <XIcon name='carbon:document' size={16} />
                        <Text>
                          {tag.postCount || 0} {t('page.posts.articles')}
                        </Text>
                      </View>
                    </View>
                  </View>
                ))}
                {tags.length === 0 && total > 0 && (
                  <AppEmpty description={t('page.tags.no_tags_in_page')} />
                )}
              </View>
            )}

            {!loading && tags.length === 0 && total === 0 && (
              <AppEmpty inContainer description={t('page.tags.no_tags')} />
            )}

            {total > pageSize && (
              <View className='mt-8'>
                <Pagination>
                  <PaginationContent>
                    <PaginationItem>
                      <PaginationPrevious onClick={() => page > 1 && handlePageChange(page - 1)} />
                    </PaginationItem>
                    {Array.from({length: Math.ceil(total / pageSize)}, (_, i) => i + 1)
                      .filter(p => p === 1 || p === Math.ceil(total / pageSize) || Math.abs(p - page) <= 1)
                      .map(p => (
                        <PaginationItem key={p}>
                          <PaginationLink isActive={p === page} onClick={() => handlePageChange(p)}>
                            {p}
                          </PaginationLink>
                        </PaginationItem>
                      ))
                    }
                    <PaginationItem>
                      <PaginationNext onClick={() => page < Math.ceil(total / pageSize) && handlePageChange(page + 1)} />
                    </PaginationItem>
                  </PaginationContent>
                </Pagination>
              </View>
            )}
          </>
        )}
      </View>
    </View>
  );
}

// frontend/app/vue/app/pages/tag/index.vue
<script setup lang="ts">
import { fetchListTag, getTagTranslation } from '@/api/composables/tag'
import { XIcon } from '@/plugins/xicon'
import { cn } from '@/lib/utils'

const { t } = useI18n()
const localePath = useLocalePath()

const tags = ref<any[]>([])
const loading = ref(true)
const page = ref(1)
const pageSize = ref(20)
const total = ref(0)

function getTagName(tag: any) {
  const translation = getTagTranslation(tag)
  return translation?.name || t('page.tags.tag_untitled')
}

function getTagDescription(tag: any) {
  const translation = getTagTranslation(tag)
  return translation?.description || ''
}

async function loadTags() {
  loading.value = true
  try {
    const res = await fetchListTag({
      paging: { page: page.value, pageSize: pageSize.value },
      formValues: { status: 'TAG_STATUS_ACTIVE' },
    }) as any
    tags.value = res?.items || []
    total.value = res?.total || 0
  } catch (e) {
    console.error('[Tag List] 加载失败:', e)
  } finally {
    loading.value = false
  }
}

function handlePageChange(newPage: number) {
  page.value = newPage
  loadTags()
}

onMounted(loadTags)
</script>

<template>
  <div class="w-full">
    <LayoutPageHero
      :title="t('page.tags.tags_list')"
      :description="t('page.tags.explore_all')"
      icon="carbon:tag"
      size="md"
    >
      <template #default>
        <div class="flex items-center gap-2 text-sm text-muted-foreground">
          <span>{{ total || tags.length }} {{ t('page.tags.total_tags') }}</span>
        </div>
      </template>
    </LayoutPageHero>

    <LayoutSectionContainer>
      <!-- Loading Skeleton -->
      <div v-if="loading" class="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-6">
        <div v-for="i in 12" :key="i">
          <UiSkeleton class="h-[120px] w-full" />
        </div>
      </div>

      <template v-else>
        <!-- Tags Grid -->
        <div v-if="tags.length > 0 || total > 0" class="grid grid-cols-[repeat(auto-fill,minmax(260px,1fr))] gap-6">
          <div
            v-for="tag in tags"
            :key="tag.id"
            :class="cn(
              'group flex cursor-pointer flex-col items-center gap-4 rounded-2xl border bg-card p-6',
              'transition-all duration-300 ease-out',
              'hover:-translate-y-1.5',
              'hover:shadow-[0_10px_30px_-4px_hsl(var(--primary)/0.12)]',
            )"
            :style="{
              borderColor: tag.color || 'hsl(var(--border))',
              background: `linear-gradient(135deg, ${tag.color}10 0%, hsl(var(--card)) 100%)`,
            }"
            @click="navigateTo(localePath(`/tag/${tag.id}`))"
          >
            <div
              class="flex h-12 w-12 items-center justify-center rounded-lg transition-transform duration-300 group-hover:scale-110"
              :style="{ color: tag.color || 'hsl(var(--primary))' }"
            >
              <XIcon :icon="`carbon:${tag.icon || 'tag'}`" :size="48" />
            </div>
            <div class="flex flex-1 flex-col items-center gap-2 text-center">
              <h3 class="text-[15px] font-semibold text-foreground transition-colors group-hover:text-primary">
                {{ getTagName(tag) }}
              </h3>
              <p class="line-clamp-2 min-h-[2.6em] text-xs leading-relaxed text-muted-foreground">
                {{ getTagDescription(tag) }}
              </p>
              <div class="mt-auto flex items-center gap-1 pt-2 text-xs font-medium text-muted-foreground">
                <XIcon icon="carbon:document" :size="14" />
                <span>{{ tag.postCount || 0 }} {{ t('page.posts.articles') }}</span>
              </div>
            </div>
          </div>

          <div v-if="tags.length === 0 && total > 0" class="col-span-full">
            <UiAppEmpty>
              {{ t('page.tags.no_tags_in_page') }}
            </UiAppEmpty>
          </div>
        </div>

        <!-- Empty -->
        <div v-if="tags.length === 0 && total === 0" class="py-20 text-center">
          <UiAppEmpty :in-container="true">
            {{ t('page.tags.no_tags') }}
          </UiAppEmpty>
        </div>

        <!-- Pagination -->
        <div v-if="total > pageSize" class="mt-8 flex items-center justify-center gap-2">
          <UiButton
            variant="outline"
            size="sm"
            :disabled="page <= 1"
            @click="handlePageChange(page - 1)"
          >
            {{ t('common.previous') || 'Previous' }}
          </UiButton>
          <span class="text-sm text-muted-foreground">
            {{ page }} / {{ Math.ceil(total / pageSize) }}
          </span>
          <UiButton
            variant="outline"
            size="sm"
            :disabled="page >= Math.ceil(total / pageSize)"
            @click="handlePageChange(page + 1)"
          >
            {{ t('common.next') || 'Next' }}
          </UiButton>
        </div>
      </template>
    </LayoutSectionContainer>
  </div>
</template>
