// frontend/app/vue3/src/pages/register/components/PhoneRegisterPage.vue
<script setup lang="ts">
import {onBeforeUnmount, ref} from "vue";
import {$t} from '@/locales';

const phone = ref('');
const verificationCode = ref('');
const codeSent = ref(false);
const codeCountdown = ref(0);
const phoneInputId = 'register-phone-number'
const codeInputId = 'register-phone-code'
let codeTimer: number | null = null

function clearCodeTimer() {
  if (codeTimer !== null) {
    clearInterval(codeTimer)
    codeTimer = null
  }
}

/**
 * 发送验证码
 */
function handleButtonSendVerifyCode() {
  if (!phone.value) {
    return;
  }

  codeSent.value = true;
  codeCountdown.value = 60;

  clearCodeTimer()
  codeTimer = window.setInterval(() => {
    codeCountdown.value--;
    if (codeCountdown.value <= 0) {
      clearCodeTimer()
      codeSent.value = false;
    }
  }, 1000);
}

/**
 * 登录或者注册
 */
function handleButtonRegisterOrLogin() {
  if (!phone.value || !verificationCode.value) {
    return;
  }
}

onBeforeUnmount(() => {
  clearCodeTimer()
})
</script>

<template>
  <div class="register-form">
    <!-- Phone Number Group -->
    <div class="form-group">
      <label :for="phoneInputId">{{ $t('authentication.register.phone') }}</label>
      <n-input
        :id="phoneInputId"
        v-model:value="phone"
        :placeholder="$t('authentication.register.input_phone')"
        clearable
        type="text"
        autocomplete="tel"
      />
    </div>

    <!-- Verification Code Group -->
    <div class="form-group">
      <label :for="codeInputId">{{ $t('authentication.register.code') }}</label>
      <div class="code-input-row">
        <n-input
          :id="codeInputId"
          v-model:value="verificationCode"
          :placeholder="$t('authentication.register.input_code')"
          maxlength="6"
          type="text"
          autocomplete="one-time-code"
        />
        <n-button
          :disabled="codeSent"
          :type="codeSent ? 'default' : 'primary'"
          class="send-code-btn"
          aria-live="polite"
          @click="handleButtonSendVerifyCode"
        >
          {{ codeSent ? `${codeCountdown}s` : $t('authentication.register.send_code') }}
        </n-button>
      </div>
    </div>

    <!-- Register Button -->
    <n-button
      type="primary"
      block
      size="large"
      class="register-button"
      @click="handleButtonRegisterOrLogin"
    >
      {{ $t('authentication.register.register_or_login') }}
    </n-button>
  </div>
</template>

<style scoped lang="less">
.register-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;

  :deep(.n-input) {
    --n-color: var(--auth-card-bg);
    --n-color-focus: var(--auth-card-bg);
    --n-text-color: var(--auth-text-primary);
    --n-placeholder-color: var(--auth-text-secondary);
    --n-border: 1px solid var(--auth-border);
    --n-border-hover: 1px solid var(--color-brand);
    --n-border-focus: 1px solid var(--color-brand);
    --n-box-shadow-focus: var(--auth-focus-ring);
  }
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;

  label {
    display: block;
    font-weight: 500;
    font-size: 0.95rem;
    color: var(--auth-text-primary);
  }
}

.code-input-row {
  display: flex;
  gap: 0.75rem;
  align-items: center;

  :deep(.n-input) {
    flex: 1;
  }

  .send-code-btn {
    flex-shrink: 0;
    width: 120px;
    height: 40px;
    font-size: 0.9rem;
    white-space: nowrap;
  }
}

.register-button {
  font-weight: 600;
  height: 44px;
  margin-top: 0.5rem;
}
</style>

// frontend/app/react/src/app/[locale]/register/components/PhoneRegisterPage.tsx
'use client';

import {useState, useEffect} from 'react';
import {useTranslations} from 'next-intl';

export default function PhoneRegisterPage() {
    const t = useTranslations('authentication');
    
    const [phone, setPhone] = useState('');
    const [verificationCode, setVerificationCode] = useState('');
    const [codeSent, setCodeSent] = useState(false);
    const [codeCountdown, setCodeCountdown] = useState(0);

    useEffect(() => {
        let codeTimer: number | null = null;

        if (codeSent && codeCountdown > 0) {
            codeTimer = window.setInterval(() => {
                setCodeCountdown((prev) => {
                    if (prev <= 1) {
                        setCodeSent(false);
                        return 0;
                    }
                    return prev - 1;
                });
            }, 1000);
        }

        return () => {
            if (codeTimer !== null) {
                clearInterval(codeTimer);
            }
        };
    }, [codeSent, codeCountdown]);

    /**
     * 发送验证码
     */
    const handleButtonSendVerifyCode = () => {
        if (!phone) {
            return;
        }

        setCodeSent(true);
        setCodeCountdown(60);
    };

    /**
     * 登录或者注册
     */
    const handleButtonRegisterOrLogin = () => {
        if (!phone || !verificationCode) {
            return;
        }
        console.log('手机号注册/登录:', {phone, verificationCode});
    };

    const inputBase = 'w-full rounded-lg border border-border bg-background px-4 py-2.5 text-sm text-foreground transition-colors hover:border-primary focus:border-primary focus:outline-none focus:ring-[3px] focus:ring-primary/15';

    return (
        <div className="space-y-4">
            {/* Phone Number Group */}
            <div className="space-y-2">
                <label htmlFor="register-phone-number" className="block text-sm font-medium text-foreground">
                    {t('register.phone')}
                </label>
                <input
                    id="register-phone-number"
                    type="text"
                    value={phone}
                    onChange={(e) => setPhone(e.target.value)}
                    placeholder={t('register.input_phone')}
                    autoComplete="tel"
                    className={inputBase}
                />
            </div>

            {/* Verification Code Group */}
            <div className="space-y-2">
                <label htmlFor="register-phone-code" className="block text-sm font-medium text-foreground">
                    {t('register.code')}
                </label>
                <div className="flex gap-2">
                    <input
                        id="register-phone-code"
                        type="text"
                        value={verificationCode}
                        onChange={(e) => setVerificationCode(e.target.value)}
                        placeholder={t('register.input_code')}
                        maxLength={6}
                        autoComplete="one-time-code"
                        className="flex-1 rounded-lg border border-border bg-background px-4 py-2.5 text-sm text-foreground transition-colors hover:border-primary focus:border-primary focus:outline-none focus:ring-[3px] focus:ring-primary/15"
                    />
                    <button
                        type="button"
                        disabled={codeSent}
                        className={`shrink-0 cursor-pointer rounded-lg border border-border bg-card px-4 py-2.5 text-sm font-medium text-foreground transition-all hover:border-primary hover:bg-primary/5 active:scale-[0.98] ${codeSent ? 'cursor-not-allowed opacity-60' : ''}`}
                        onClick={handleButtonSendVerifyCode}
                    >
                        {codeSent ? `${codeCountdown}s` : t('register.send_code')}
                    </button>
                </div>
            </div>

            {/* Register Button */}
            <button
                type="button"
                className="w-full cursor-pointer rounded-lg bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground transition-all hover:bg-primary/90 active:scale-[0.98]"
                onClick={handleButtonRegisterOrLogin}
            >
                {t('register.register_or_login')}
            </button>
        </div>
    );
}
