// frontend/app/react/src/app/[locale]/category/[id]/page.tsx
'use client';

import {useState, useEffect, useMemo} from 'react';
import {useParams} from 'next/navigation';
import {useTranslations} from 'next-intl';
import {Button} from '@/components/ui/button';
import {ArrowLeft} from 'lucide-react';
import {AppEmpty} from '@/components/ui';

import {useI18nRouter} from "@/i18n/helpers";

import {
    fetchCategory,
    getCategoryName,
    getCategoryDescription,
} from '@/api/hooks/category';
import CategoryList from '@/components/category/CategoryList';
import PostListWithPagination from '@/components/post/PostList';
import PageHero from '@/components/layout/PageHero';
import {XIcon} from '@/plugins/xicon';
import {contentservicev1_Category} from "@/api/generated/app/service/v1";

export default function CategoryDetailPage() {
    const t = useTranslations('page');
    const params = useParams();
    const router = useI18nRouter();

    const [_loading, setLoading] = useState(false);
    const [category, setCategory] = useState<contentservicev1_Category | null>(null);
    const [childCategories, setChildCategories] = useState<contentservicev1_Category[]>([]);

    const categoryId = useMemo(() => {
        const id = params?.id;
        return id ? parseInt(id as string) : null;
    }, [params?.id]);

    // Get parent category ID
    const parentCategoryId = useMemo(() => {
        if (!category?.parentId) return null;
        return category.parentId;
    }, [category?.parentId]);

    async function loadCategory() {
        if (!categoryId) return;

        setLoading(true);
        try {
            const categoryData = (await fetchCategory({
                id: categoryId!,
                fieldMask: 'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image'
            })) as contentservicev1_Category;
            setCategory(categoryData);
            // Extract child categories - create new array reference to ensure reactive update
            if (categoryData?.children && categoryData.children.length > 0) {
                setChildCategories([...categoryData.children]);
            } else {
                setChildCategories([]);
            }
        } catch (error) {
            console.error('Load category failed:', error);
        } finally {
            setLoading(false);
        }
    }

    function handleViewChildCategory(id: number) {
        router.push(`/category/${id}`);
    }

    function handleBackToParent() {
        if (parentCategoryId) {
            router.push(`/category/${parentCategoryId}`);
        } else {
            router.push('/category');
        }
    }

    useEffect(() => {
        loadCategory();
    }, [categoryId]);

    if (!categoryId) {
        return <AppEmpty variant="error" description="Invalid category ID"/>;
    }

    return (
        <div className="w-full">
            <PageHero
                title={getCategoryName(category) || ''}
                description={getCategoryDescription(category) || undefined}
                icon={category?.icon || 'carbon:folder'}
                size="lg"
                meta={
                    <>
                        <div className="flex items-center gap-2">
                            <XIcon name="carbon:document" size={16}/>
                            <span>{category?.postCount || 0} {t('posts.articles')}</span>
                        </div>
                        {childCategories.length > 0 && (
                            <div className="flex items-center gap-2">
                                <XIcon name="carbon:folder" size={16}/>
                                <span>{childCategories.length} {t('categories.categories')}</span>
                            </div>
                        )}
                    </>
                }
            />

            {/* Posts Section */}
            <div className="w-full max-w-[1200px] mx-auto px-8 py-12 max-md:px-4">
                {/* Back to Parent Button */}
                <div className="mb-8">
                    <Button
                        variant="outline"
                        size="sm"
                        onClick={handleBackToParent}
                        className="gap-2"
                    >
                        <ArrowLeft className="h-4 w-4"/>
                        {parentCategoryId ? t('categories.back_to_parent') : t('categories.back_to_list')}
                    </Button>
                </div>

                {/* Sub Categories List */}
                {childCategories.length > 0 && (
                    <div className="mb-8">
                        <CategoryList
                            categories={childCategories}
                            loading={false}
                            showSkeleton={false}
                            onCategoryClick={handleViewChildCategory}
                        />
                    </div>
                )}

                {/* Posts List with Pagination */}
                <PostListWithPagination
                    key={categoryId}
                    initialPageSize={10}
                    pageSizes={[10, 20, 30, 40]}
                    categoryId={categoryId}
                    from="category"
                />
            </div>
        </div>
    );
}

// frontend/app/vue/app/pages/category/[id].vue
<script setup lang="ts">
import { XIcon } from '@/plugins/xicon'
import { fetchCategory, getCategoryName, getCategoryDescription } from '@/api/composables/category'

const { t } = useI18n()
const localePath = useLocalePath()
const route = useRoute()

const category = ref<any>(null)
const childCategories = ref<any[]>([])
const loading = ref(true)
const error = ref('')

const categoryId = computed(() => Number(route.params.id))

// 动态标题
const categoryTitle = computed(() =>
  category.value ? getCategoryName(category.value, t('page.categories.category_untitled')) : t('page.categories.categories')
)
useHead({ title: () => categoryTitle.value })

const parentCategoryId = computed(() => {
  if (!category.value?.parentId) return null
  return category.value.parentId
})

async function loadCategory() {
  if (!categoryId.value) return
  loading.value = true
  try {
    const catData = await fetchCategory(
      categoryId.value,
      'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image'
    ) as any
    category.value = catData
    if (catData?.children?.length > 0) {
      childCategories.value = [...catData.children]
    } else {
      childCategories.value = []
    }
  } catch (e) {
    console.error('[Category Detail] 加载失败:', e)
    error.value = t('page.categories.load_failed')
  } finally {
    loading.value = false
  }
}

function handleViewChildCategory(id: number) {
  navigateTo(localePath(`/category/${id}`))
}

function handleBackToParent() {
  if (parentCategoryId.value) {
    navigateTo(localePath(`/category/${parentCategoryId.value}`))
  } else {
    navigateTo(localePath('/category'))
  }
}

onMounted(loadCategory)
</script>

<template>
  <div class="w-full">
    <!-- Error -->
    <div v-if="error" class="w-full py-20 text-center">
      <LayoutSectionContainer>
        <div class="flex flex-col items-center gap-4">
          <XIcon icon="carbon:warning-alt" :size="48" class="text-muted-foreground" />
          <p class="text-lg text-muted-foreground">{{ error }}</p>
          <UiButton variant="outline" @click="navigateTo(localePath('/category'))">
            {{ t('common.back') || '← Back' }}
          </UiButton>
        </div>
      </LayoutSectionContainer>
    </div>

    <!-- Category Detail -->
    <template v-else-if="category">
      <LayoutPageHero
        :title="getCategoryName(category, t('page.categories.category_untitled'))"
        :description="getCategoryDescription(category) || undefined"
        :icon="category.icon || 'carbon:folder'"
        size="lg"
      >
        <template #default>
          <div class="flex items-center gap-2">
            <XIcon icon="carbon:document" :size="16" />
            <span>{{ category.postCount || 0 }} {{ t('page.posts.articles') }}</span>
          </div>
          <div v-if="childCategories.length > 0" class="flex items-center gap-2">
            <XIcon icon="carbon:folder" :size="16" />
            <span>{{ childCategories.length }} {{ t('page.categories.categories') }}</span>
          </div>
        </template>
      </LayoutPageHero>

      <LayoutSectionContainer>
        <!-- Back Button -->
        <div class="mb-8">
          <LayoutBackButton
            :label="parentCategoryId ? t('page.categories.back_to_parent') : t('page.categories.back_to_list')"
            :on-click="handleBackToParent"
          />
        </div>

        <!-- Sub Categories List -->
        <div v-if="childCategories.length > 0" class="mb-8">
          <CategoryList
            :categories="childCategories"
            :loading="false"
            :show-skeleton="false"
            :on-category-click="handleViewChildCategory"
          />
        </div>

        <!-- Posts List with Pagination -->
        <PostList
          :key="categoryId"
          :initial-page-size="10"
          :show-pagination="true"
          :category-id="categoryId"
          from="category"
        />
      </LayoutSectionContainer>
    </template>
  </div>
</template>
