// frontend/app/taro/src/pages/[locale]/category/[id]/index.tsx
'use client';

import {useEffect, useMemo, useState} from 'react';
import {useTranslation} from 'react-i18next';
import {View, Text} from '@tarojs/components';
import Taro from '@tarojs/taro';
import {AppEmpty} from '@/components/ui';
import {useCategoryStore} from '@/store/slices/category/hooks';

import CategoryList from '@/components/category/CategoryList';
import PostListWithPagination from '@/components/post/PostList';
import {contentservicev1_Category} from "@/api/generated/app/service/v1";

import '../../../globals.css'; // 导入全局 CSS，确保 CSS 变量可用
import styles from './category-detail.scss';

export default function CategoryDetailPage() {
  const {t} = useTranslation('page');
  const categoryStore = useCategoryStore();
  const [childCategories, setChildCategories] = useState<contentservicev1_Category[]>([]);

  const categoryId = useMemo(() => {
    const pages = Taro.getCurrentPages();
    const currentPage = pages[pages.length - 1];
    const id = (currentPage as any).options?.id;
    return id ? parseInt(id) : null;
  }, []);

  // Get parent category ID
  const parentCategoryId = useMemo(() => {
    if (!categoryStore.detail?.parentId) return null;
    return categoryStore.detail.parentId;
  }, [categoryStore.detail?.parentId]);

  async function loadCategory() {
    if (!categoryId) return;

    try {
      await categoryStore.getCategory({
        id: categoryId,
        fieldMask: 'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image'
      });
      // Extract child categories from the loaded category
      const loadedCategory = categoryStore.detail;
      if (loadedCategory?.children && loadedCategory.children.length > 0) {
        setChildCategories([...loadedCategory.children]);
      } else {
        setChildCategories([]);
      }
    } catch (error) {
      console.error('Load category failed:', error);
    }
  }

  function handleViewChildCategory(id: number) {
    Taro.navigateTo({url: `/pages/[locale]/category/${id}/page`});
  }

  function handleBackToParent() {
    if (parentCategoryId) {
      Taro.navigateTo({url: `/pages/[locale]/category/${parentCategoryId}/page`});
    } else {
      Taro.navigateBack();
    }
  }

  useEffect(() => {
    loadCategory();
  }, [categoryId]);

  if (!categoryId) {
    return <AppEmpty variant="error" description="Invalid category ID"/>;
  }

  return (
    <View className={styles['category-detail-page']}>
      {/* Hero Section */}
      <View className={styles['hero-section']}>
        <View className={styles['hero-content']}>
          <Text>{categoryStore.getCategoryName(categoryStore.detail)}</Text>
          {categoryStore.getCategoryDescription(categoryStore.detail) && (
            <Text className={styles['category-description']}>
              {categoryStore.getCategoryDescription(categoryStore.detail)}
            </Text>
          )}
          <View className={styles['category-stats']}>
            <View className={styles['stat-item']}>
              <Text>📄</Text>
              <Text>{categoryStore.detail?.postCount || 0} {t('posts.articles')}</Text>
            </View>
          </View>
        </View>
      </View>

      {/* Posts Section */}
      <View className={styles['page-container']}>
        {/* Back to Parent Button */}
        <View className={styles['back-button-container']}>
          <View className={styles['back-btn']} onClick={handleBackToParent}>
            <Text>← </Text>
            <Text>{parentCategoryId ? t('categories.back_to_parent') : t('categories.back_to_list')}</Text>
          </View>
        </View>

        {/* Sub Categories List */}
        {childCategories.length > 0 && (
          <View className={styles['sub-categories-wrapper']}>
            <CategoryList
              categories={childCategories}
              loading={false}
              showSkeleton={false}
              onCategoryClick={handleViewChildCategory}
            />
          </View>
        )}

        {/* Posts List with Pagination */}
        <PostListWithPagination
          key={categoryId}
          initialPageSize={10}
          pageSizes={[10, 20, 30, 40]}
          categoryId={categoryId}
          from="category"
        />
      </View>
    </View>
  );
}

// frontend/app/vue/app/pages/category/[id].vue
<script setup lang="ts">
import { XIcon } from '@/plugins/xicon'
import { fetchCategory, getCategoryName, getCategoryDescription } from '@/api/composables/category'

const { t } = useI18n()
const localePath = useLocalePath()
const route = useRoute()

const category = ref<any>(null)
const childCategories = ref<any[]>([])
const loading = ref(true)
const error = ref('')

const categoryId = computed(() => Number(route.params.id))

// 动态标题
const categoryTitle = computed(() =>
  category.value ? getCategoryName(category.value, t('page.categories.category_untitled')) : t('page.categories.categories')
)
useHead({ title: () => categoryTitle.value })

const parentCategoryId = computed(() => {
  if (!category.value?.parentId) return null
  return category.value.parentId
})

async function loadCategory() {
  if (!categoryId.value) return
  loading.value = true
  try {
    const catData = await fetchCategory(
      categoryId.value,
      'id,status,sort_order,icon,code,post_count,direct_post_count,parent_id,created_at,children,translations.id,translations.category_id,translations.name,translations.language_code,translations.description,translations.thumbnail,translations.cover_image'
    ) as any
    category.value = catData
    if (catData?.children?.length > 0) {
      childCategories.value = [...catData.children]
    } else {
      childCategories.value = []
    }
  } catch (e) {
    console.error('[Category Detail] 加载失败:', e)
    error.value = t('page.categories.load_failed')
  } finally {
    loading.value = false
  }
}

function handleViewChildCategory(id: number) {
  navigateTo(localePath(`/category/${id}`))
}

function handleBackToParent() {
  if (parentCategoryId.value) {
    navigateTo(localePath(`/category/${parentCategoryId.value}`))
  } else {
    navigateTo(localePath('/category'))
  }
}

onMounted(loadCategory)
</script>

<template>
  <div class="w-full">
    <!-- Error -->
    <div v-if="error" class="w-full py-20 text-center">
      <LayoutSectionContainer>
        <div class="flex flex-col items-center gap-4">
          <XIcon icon="carbon:warning-alt" :size="48" class="text-muted-foreground" />
          <p class="text-lg text-muted-foreground">{{ error }}</p>
          <UiButton variant="outline" @click="navigateTo(localePath('/category'))">
            {{ t('common.back') || '← Back' }}
          </UiButton>
        </div>
      </LayoutSectionContainer>
    </div>

    <!-- Category Detail -->
    <template v-else-if="category">
      <LayoutPageHero
        :title="getCategoryName(category, t('page.categories.category_untitled'))"
        :description="getCategoryDescription(category) || undefined"
        :icon="category.icon || 'carbon:folder'"
        size="lg"
      >
        <template #default>
          <div class="flex items-center gap-2">
            <XIcon icon="carbon:document" :size="16" />
            <span>{{ category.postCount || 0 }} {{ t('page.posts.articles') }}</span>
          </div>
          <div v-if="childCategories.length > 0" class="flex items-center gap-2">
            <XIcon icon="carbon:folder" :size="16" />
            <span>{{ childCategories.length }} {{ t('page.categories.categories') }}</span>
          </div>
        </template>
      </LayoutPageHero>

      <LayoutSectionContainer>
        <!-- Back Button -->
        <div class="mb-8">
          <LayoutBackButton
            :label="parentCategoryId ? t('page.categories.back_to_parent') : t('page.categories.back_to_list')"
            :on-click="handleBackToParent"
          />
        </div>

        <!-- Sub Categories List -->
        <div v-if="childCategories.length > 0" class="mb-8">
          <CategoryList
            :categories="childCategories"
            :loading="false"
            :show-skeleton="false"
            :on-category-click="handleViewChildCategory"
          />
        </div>

        <!-- Posts List with Pagination -->
        <PostList
          :key="categoryId"
          :initial-page-size="10"
          :show-pagination="true"
          :category-id="categoryId"
          from="category"
        />
      </LayoutSectionContainer>
    </template>
  </div>
</template>
