// frontend/app/taro/src/components/post/PostCard.tsx
import {View, Text} from '@tarojs/components';
import React from 'react';

import {XIcon} from '@/plugins/xicon';
import {
    getPostTitle,
    getPostSummary,
    getPostThumbnail,
} from '@/api/hooks/post';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';

import type {contentservicev1_Post} from '@/api/generated/app/service/v1';

import Image from '@/components/ui/image';
import {formatDate} from "@/utils";
import {cn} from '@/lib/utils';
import Taro from '@tarojs/taro';

interface PostCardProps {
    post: contentservicev1_Post;
    from?: string;
    categoryId?: number;
}

const PostCard: React.FC<PostCardProps> = ({
                                               post,
                                               from = 'post-list',
                                               categoryId
                                           }) => {
    const router = useI18nRouter();

    const handleViewPost = () => {
        const query: string[] = [`from=${from}`];
        if (categoryId) {
            query.push(`categoryId=${categoryId}`);
        }

        router.push(`/post/detail?id=${post.id}&${query.join('&')}`);

        // 滚动到顶部（Taro 兼容）
        if (typeof Taro !== 'undefined') {
            Taro.pageScrollTo({scrollTop: 0, duration: 300});
        } else if (typeof window !== 'undefined') {
            window.scrollTo({top: 0, behavior: 'smooth'});
        }
    };

    return (
        <View
          className={cn(
                'group flex h-full cursor-pointer flex-col overflow-hidden',
                /* 亮色模式：纯白卡片 */
                'rounded-2xl border border-border bg-card shadow-sm',
                /* 深色模式：磨砂玻璃浮空塊 */
                'dark:border-slate-800/50 dark:bg-slate-900/40 dark:backdrop-blur-md dark:shadow-xl',
                /* 空气动力学悬浮：纯 primary 辉光（无暗影底），更空灵 */
                'transition-all duration-500 ease-out',
                'hover:-translate-y-1.5 hover:border-primary/40',
                'hover:shadow-[0_20px_40px_-8px_hsl(var(--primary)/0.15)]',
            )}
          onClick={handleViewPost}
          style={{ willChange: 'transform, box-shadow' }}
        >
            <View className='relative h-[240px] w-full flex-shrink-0 overflow-hidden bg-background max-md:h-[200px]'>
                <Image
                  src={getPostThumbnail(post)}
                  alt={getPostTitle(post)}
                  className='h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-[1.12]'
                />
                {/* hover 风迹渐变蒙层 */}
                <View className='absolute inset-0 bg-gradient-to-tr from-primary/20 via-transparent to-sky-400/20 opacity-0 transition-opacity duration-500 group-hover:opacity-100' />
            </View>
            <View className='flex flex-1 flex-col gap-3 p-6 max-md:p-4 max-md:gap-2.5'>
                {/* 标题：固定 min-h 确保两行高度 */}
                <Text className={cn(
                    'line-clamp-2 min-h-[3.4em] text-lg font-bold leading-[1.7] text-foreground transition-colors duration-300',
                    'group-hover:text-primary',
                    'max-md:min-h-[3em] max-md:text-[17px]',
                )}
                >
                    {getPostTitle(post)}
                </Text>
                {/* 摘要：固定 min-h 确保三行高度，底部的数据列永退贴底 */}
                <Text className={cn(
                    'line-clamp-3 min-h-[4.4em] flex-1 text-sm leading-relaxed text-muted-foreground',
                    'max-md:min-h-[4em] max-md:text-xs max-md:leading-relaxed',
                )}
                >
                    {getPostSummary(post)}
                </Text>
                {/* 元数据固定双行布局：第一行作者+日期，第二行浏览+点赞，确保所有卡片对齐 */}
                <View className={cn(
                    'border-t border-border pt-3 text-[13px] font-medium text-muted-foreground',
                    'flex flex-col gap-1.5',
                    'max-md:text-xs',
                )}
                >
                    <View className='flex flex-wrap gap-4'>
                        <View className='flex items-center gap-1.5 whitespace-nowrap'>
                            <XIcon name='carbon:user' size={16} />
                            <Text>{post.authorName || '—'}</Text>
                        </View>
                        <View className='flex items-center gap-1.5 whitespace-nowrap'>
                            <XIcon name='carbon:calendar' size={16} />
                            <Text>{formatDate(post.createdAt)}</Text>
                        </View>
                    </View>
                    <View className='flex flex-wrap gap-4'>
                        <View className='flex items-center gap-1.5 whitespace-nowrap'>
                            <XIcon name='carbon:view' size={16} />
                            <Text>{post.visits || 0}</Text>
                        </View>
                        <View className='flex items-center gap-1.5 whitespace-nowrap'>
                            <XIcon name='carbon:thumbs-up' size={16} />
                            <Text>{post.likes || 0}</Text>
                        </View>
                    </View>
                </View>
            </View>
        </View>
    );
};

export default PostCard;

// frontend/app/vue3_old/src/components/PostCard/PostCard.vue
<script setup lang="ts">
import {useRouter} from 'vue-router'

import {usePostStore} from '@/stores';
import type {contentservicev1_Post} from "@/api/generated/app/service/v1";
import {scrollToTop} from "@/utils";
import {formatDate} from "@/utils/date";

interface Props {
  post: contentservicev1_Post
  from?: string
  categoryId?: number
}

const props = withDefaults(defineProps<Props>(), {
  from: 'post-list',
  categoryId: undefined
})

const router = useRouter()
const postStore = usePostStore()

function handleViewPost() {
  const query: any = {from: props.from}
  if (props.categoryId) {
    query.categoryId = props.categoryId
  }

  router.push({
    path: `/post/${props.post.id}`,
    query
  })

  scrollToTop()
}
</script>

<template>
  <article
    class="post-card"
    @click="handleViewPost"
  >
    <div class="post-image">
      <img :src="postStore.getPostThumbnail(post)" :alt="postStore.getPostTitle(post)"/>
      <div class="image-overlay"/>
    </div>
    <div class="post-content">
      <h3 class="post-title">{{ postStore.getPostTitle(post) }}</h3>
      <p class="post-summary">{{ postStore.getPostSummary(post) }}</p>
      <div class="post-meta">
        <div class="meta-item">
          <span class="i-carbon:user"/>
          <span>{{ post.authorName }}</span>
        </div>
        <div class="meta-item">
          <span class="i-carbon:calendar"/>
          <span>{{ formatDate(post.createdAt) }}</span>
        </div>
        <div class="meta-item">
          <span class="i-carbon:view"/>
          <span>{{ post.visits || 0 }}</span>
        </div>
        <div class="meta-item">
          <span class="i-carbon:thumbs-up"/>
          <span>{{ post.likes || 0 }}</span>
        </div>
      </div>
    </div>
  </article>
</template>

<style scoped lang="less">
.post-card {
  background: var(--color-surface);
  border-radius: 16px;
  overflow: hidden;
  cursor: pointer;
  transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);
  border: 1px solid var(--color-border);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);
  display: flex;
  flex-direction: column;
  height: 100%;

  &:hover {
    transform: translateY(-6px);
    box-shadow: 0 16px 32px rgba(0, 0, 0, 0.12);
    border-color: var(--color-brand);

    .post-image {
      .image-overlay {
        opacity: 0.5;
      }

      img {
        transform: scale(1.08);
      }
    }

    .post-title {
      color: var(--color-brand);
    }
  }

  .post-image {
    position: relative;
    width: 100%;
    height: 240px;
    flex-shrink: 0;
    overflow: hidden;
    background: var(--color-bg);

    img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      transition: transform 0.5s cubic-bezier(0.4, 0, 0.2, 1);
    }

    .image-overlay {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.15);
      transition: opacity 0.3s;
      opacity: 0;
    }
  }

  .post-content {
    padding: 24px;
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 12px;

    .post-title {
      font-size: 18px;
      font-weight: 700;
      margin: 0;
      color: var(--color-text-primary);
      line-height: 1.4;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
      transition: color 0.3s;
    }

    .post-summary {
      color: var(--color-text-secondary);
      font-size: 14px;
      line-height: 1.6;
      margin: 0;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      overflow: hidden;
      flex: 1;
    }

    .post-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 16px;
      font-size: 13px;
      color: var(--color-text-secondary);
      padding-top: 12px;
      border-top: 1px solid var(--color-border);

      .meta-item {
        display: flex;
        align-items: center;
        gap: 6px;
        white-space: nowrap;

        span[class^="i-"] {
          font-size: 16px;
          opacity: 0.7;
        }
      }
    }
  }
}

// 响应式
@media (max-width: 768px) {
  .post-card {
    .post-image {
      height: 200px;
    }

    .post-content {
      padding: 16px;
      gap: 10px;

      .post-title {
        font-size: 17px;
      }

      .post-summary {
        font-size: 13px;
      }

      .post-meta {
        font-size: 12px;
        flex-wrap: wrap;

        .meta-item {
          span[class^="i-"] {
            font-size: 14px;
          }
        }
      }
    }
  }
}
</style>
