// frontend/app/vue/app/components/layout/SearchBar.vue
<script setup lang="ts">
const { t } = useI18n()
const searchQuery = ref('')

const handleSearch = () => {
  console.log('Searching for:', searchQuery.value)
}
</script>

<template>
  <div class="mx-2 hidden h-11 max-w-80 flex-1 items-center md:flex lg:max-w-80">
    <div class="relative w-full">
      <iconify-icon icon="lucide:search" width="16" height="16" class="absolute left-2 top-1/2 -translate-y-1/2 text-muted-foreground" />
      <UIInput
        class="h-full w-full pl-8"
        v-model="searchQuery"
        @keyup="handleSearch"
        :placeholder="t('navbar.top.search_placeholder')"
      />
    </div>
  </div>
</template>

// frontend/app/taro/src/components/layout/SearchBar.tsx
import {useState} from 'react';
import {View} from '@tarojs/components';
import {Input} from '@/components/ui/input';
import {XIcon} from '@/plugins/xicon';
import {useTranslations} from '@/lib/next-intl-compat';

export default function SearchBar() {
    const t = useTranslations('navbar.top');
    const [searchQuery, setSearchQuery] = useState('');

    const handleSearch = () => {
        console.log('Searching for:', searchQuery);
    };

    return (
        <View className='mx-2 hidden h-11 max-w-80 flex-1 md:flex lg:max-w-80'>
            <View className='relative w-full'>
                <View className='absolute left-2 top-1/2 -translate-y-1/2 text-muted-foreground'>
                    <XIcon name='carbon:search' size={16} />
                </View>
                <Input
                  className='h-full w-full pl-8'
                  value={searchQuery}
                  onInput={(e: any) => setSearchQuery(e.detail?.value ?? e.target?.value ?? '')}
                  placeholder={t('search_placeholder')}
                />
            </View>
        </View>
    );
}
