// frontend/app/taro/src/components/post/PostList.tsx
import {View, Text} from '@tarojs/components';
import React, {useState, useEffect, useCallback} from 'react';
import {Skeleton} from '@/components/ui/skeleton';
import {Button} from '@/components/ui/button';
import {useTranslations} from '@/lib/next-intl-compat';
import {AppEmpty} from '@/components/ui';

import {fetchListPosts} from '@/api/hooks/post';
import type {
    contentservicev1_ListPostResponse,
    contentservicev1_Post
} from '@/api/generated/app/service/v1';

import PostCard from './PostCard';

interface PostListProps {
    queryParams?: object;
    fieldMask?: string;
    orderBy?: string[];
    page?: number;
    pageSize?: number;
    initialPageSize?: number; // 初始每页条数
    showSkeleton?: boolean;
    from?: string;
    categoryId?: number;
    tagId?: number; // 新增 tagId 支持
    columns?: number; // 控制列数
    showPagination?: boolean; // 是否显示分页
    pageSizes?: number[]; // 每页条数选项
}

const PostList: React.FC<PostListProps> = ({
                                               queryParams = {},
                                               fieldMask,
                                               orderBy,
                                               page = 1,
                                               pageSize,
                                               initialPageSize = 10, // 默认 10 条
                                               showSkeleton = true,
                                               from = 'post-list',
                                               categoryId,
                                               tagId,
                                               columns = 3,
                                               showPagination = false,
                                               pageSizes = [10, 20, 30, 40]
                                           }) => {
    const t = useTranslations('page.posts');
    const [posts, setPosts] = useState<contentservicev1_Post[]>([]);
    const [loading, setLoading] = useState(false);
    const [total, setTotal] = useState(0);
    const [currentPage, setCurrentPage] = useState<number>(page);
    const [currentPageSize, setCurrentPageSize] = useState<number>(pageSize ?? initialPageSize);

    // 同步外部 page 变化（只在首次渲染或外部 page 真正变化时）
    useEffect(() => {
        if (page !== undefined && page !== currentPage) {
            setCurrentPage(page);
        }
    }, [currentPage, page]);

    // 同步外部 pageSize 变化（只在首次渲染或外部 pageSize 真正变化时）
    useEffect(() => {
        if (pageSize !== undefined && pageSize !== currentPageSize) {
            setCurrentPageSize(pageSize);
        }
    }, [currentPageSize, pageSize]);

    // 监听 categoryId 和 tagId 变化，重置页码并重新查询
    useEffect(() => {
        setCurrentPage(1);
        // 直接调用 fetchPosts，使用新的 categoryId/tagId
        fetchPosts(1, currentPageSize);
    }, [categoryId, tagId]);

    const fetchPosts = useCallback(async (page: number, pageSize: number) => {
        setLoading(true);
        try {
            const res = await fetchListPosts({
                paging: {
                    page: page,
                    pageSize: pageSize,
                },
                formValues: {
                    ...queryParams,
                    ...(categoryId && {category_ids__in: [categoryId]}),
                    ...(tagId && {tag_ids__in: [tagId]})
                },
                fieldMask: fieldMask,
                orderBy: orderBy
            }) as unknown as contentservicev1_ListPostResponse;
            setPosts(res.items || []);
            setTotal(res.total || 0);
        } catch (error) {
            console.error('PostList fetch failed:', error);
            setPosts([]);
        } finally {
            setLoading(false);
        }
    }, [queryParams, categoryId, tagId, fieldMask, orderBy]);

    // 监听页面变化
    useEffect(() => {
        fetchPosts(currentPage, currentPageSize);
    }, [currentPage, currentPageSize]); // 移除 fetchPosts 依赖，避免循环

    // 监听外部 page 变化（已在上面处理）

    // 处理页面变化
    const handlePageChange = (newPage: number) => {
        setCurrentPage(newPage);
    };

    // 处理每页条数变化
    const handlePageSizeChange = (size: number, newPage: number) => {
        setCurrentPageSize(size);
        setCurrentPage(newPage);
    };

    return (
        <View className='w-full'>
            {/* Loading Skeleton */}
            {loading && showSkeleton && (
                <View
                  className='grid gap-6 max-md:!grid-cols-1 max-md:gap-4'
                  style={{gridTemplateColumns: `repeat(${columns}, 1fr)`}}
                >
                    {Array.from({length: currentPageSize}).map((_, index) => (
                        <View key={index} className='overflow-hidden rounded-2xl border border-border bg-card'>
                            <Skeleton className='h-60 w-full' />
                            <View className='p-6'>
                                <Skeleton className='h-4 w-full' />
                                <Skeleton className='h-4 w-3/4' />
                                <View className='mt-4 flex gap-3 border-t border-border pt-4'>
                                    <Skeleton className='h-6 w-[60px]' />
                                    <Skeleton className='h-6 w-[60px]' />
                                    <Skeleton className='h-6 w-[60px]' />
                                </View>
                            </View>
                        </View>
                    ))}
                </View>
            )}

            {/* Loaded Content */}
            {!loading && posts.length > 0 && (
                <>
                    {showPagination && total > currentPageSize && (
                        <View className='mb-6 rounded-xl border border-border bg-card px-5 py-4 text-sm text-muted-foreground'>
                            <Text>{t('total_articles', {total})}</Text>
                        </View>
                    )}

                    <View
                      className='grid gap-6 max-md:!grid-cols-1 max-md:gap-4'
                      style={{gridTemplateColumns: `repeat(${columns}, 1fr)`}}
                    >
                        {posts.map((post, index) => (
                            <PostCard
                              key={`${post.id}-${index}`}
                              post={post}
                              from={from}
                              categoryId={categoryId}
                            />
                        ))}
                    </View>

                    {showPagination && total > currentPageSize && (
                        <View className='flex justify-center py-10'>
                            <View className='flex items-center justify-center gap-2'>
                                <Button
                                  variant='outline'
                                  size='sm'
                                  disabled={currentPage <= 1}
                                  onClick={() => handlePageChange(currentPage - 1)}
                                >
                                    Previous
                                </Button>
                                <Text className='px-2 text-sm text-muted-foreground'>
                                    {currentPage} / {Math.ceil(total / currentPageSize)}
                                </Text>
                                <Button
                                  variant='outline'
                                  size='sm'
                                  disabled={currentPage >= Math.ceil(total / currentPageSize)}
                                  onClick={() => handlePageChange(currentPage + 1)}
                                >
                                    Next
                                </Button>
                            </View>
                        </View>
                    )}
                </>
            )}

            {/* Empty State */}
            {!loading && posts.length === 0 && (
                <AppEmpty description={t('no_results')} />
            )}
        </View>
    );
};

export default PostList;

// frontend/app/vue3/src/components/PostList/PostList.vue
<script setup lang="ts">
import {ref, defineProps, defineExpose} from 'vue';

import {usePostStore} from '@/stores';
import {$t} from '@/locales';
import PostCard from '@/components/PostCard';
import type {contentservicev1_Post} from "@/api/generated/app/service/v1";
import {useLanguageChangeEffect} from '@/hooks/useLanguageChangeEffect';

interface Props {
  queryParams?: object;
  fieldMask?: string;
  orderBy?: string[];
  page?: number;
  pageSize?: number;
  showSkeleton?: boolean;
  from?: string;
  categoryId?: number;
  columns?: number; // 新增：控制列数
}

const props = withDefaults(defineProps<Props>(), {
  queryParams: () => ({}),
  fieldMask: undefined,
  orderBy: undefined,
  page: 1,
  pageSize: 6,
  showSkeleton: true,
  from: 'post-list',
  categoryId: undefined,
  columns: 3, // 默认 3 列
});

defineExpose({reload});

const postStore = usePostStore();
const posts = ref<contentservicev1_Post[]>([]);
const loading = ref(false);

async function fetchPosts() {
  // console.log('PostList fetching...')

  loading.value = true;
  try {
    const res = await postStore.listPost(
      {page: props.page, pageSize: props.pageSize},
      props.queryParams,
      props.fieldMask,
      props.orderBy
    );
    posts.value = res.items || [];
  } catch (error) {
    posts.value = [];
    console.error('PostList fetch failed:', error);
  } finally {
    loading.value = false;
  }
}

function reload() {
  // console.log('PostList reload...')
  fetchPosts();
}

useLanguageChangeEffect(() => {
  fetchPosts();
}, {
  immediate: false,
  autoCleanup: true,
});
</script>

<template>
  <div class="posts-list-container">
    <!-- Loading Skeleton -->
    <div v-if="loading && showSkeleton" class="posts-grid">
      <div v-for="i in 6" :key="i" class="post-card">
        <n-skeleton height="220px"/>
        <div style="padding: 24px;">
          <n-skeleton :width="'80%'" size="medium" style="margin-bottom: 12px;"/>
          <n-skeleton :width="'90%'" size="small" style="margin-bottom: 16px;"/>
          <div style="display: flex; gap: 12px;">
            <n-skeleton :width="60" size="small"/>
            <n-skeleton :width="60" size="small"/>
            <n-skeleton :width="60" size="small"/>
          </div>
        </div>
      </div>
    </div>

    <!-- Loaded Content -->
    <div v-else-if="!loading && posts.length > 0" class="posts-grid">
      <PostCard
        v-for="post in posts"
        :key="post.id"
        :post="post"
        :from="from"
        :category-id="categoryId"
      />
    </div>

    <!-- Empty State -->
    <div v-else-if="!loading && posts.length === 0" class="empty-state">
      <n-empty :description="$t('page.posts.no_results')"/>
    </div>
  </div>
</template>

<style scoped lang="less">
.posts-list-container {
  width: 100%;
}

.posts-grid {
  display: grid;
  grid-template-columns: repeat(v-bind('props.columns'), 1fr);
  gap: 24px;
}

.empty-state {
  padding: 60px 20px;
  text-align: center;
}

// 响应式
@media (max-width: 768px) {
  .posts-grid {
    grid-template-columns: 1fr;
    gap: 16px;
  }
}
</style>
