// frontend/app/taro/src/components/ui/skeleton.tsx
import * as React from 'react';
import {View} from '@tarojs/components';
import {cn} from '@/lib/utils';

function Skeleton({className, ...props}: React.HTMLAttributes<HTMLDivElement>) {
    return <View className={cn('animate-pulse rounded-md bg-muted', className)} {...props} />;
}

export {Skeleton};

// frontend/app/vue/app/components/ui/skeleton/Skeleton.vue
<script setup lang="ts">
import { type HTMLAttributes, computed } from 'vue'
import { cn } from '@/lib/utils'

const props = defineProps<{
  class?: HTMLAttributes['class']
}>()

const delegatedProps = computed(() => {
  const { class: _, ...delegated } = props
  return delegated
})
</script>

<template>
  <div v-bind="delegatedProps" :class="cn('animate-pulse rounded-md bg-primary/10', props.class)" />
</template>
