// frontend/app/vue3_old/src/components/Footer/Footer.vue
<template>
  <footer class="footer-outer">
    <div class="footer-container stick-content">
      <nav class="footer-links" aria-label="Footer links">
        <n-button
          v-for="link in footerLinks"
          :key="link.key"
          text
          class="footer-link"
          @click="handleFooterLinkClick(link.key)"
        >
          {{ $t(link.labelKey) }}
        </n-button>
      </nav>

      <div class="footer-meta">
        <span class="copyright">{{ $t('ui.copyright') }}</span>
        <n-divider vertical class="meta-divider"/>
        <div class="social-list" aria-label="Social links">
          <n-button
            v-for="item in socialLinks"
            :key="item.key"
            text
            class="social-btn"
            :aria-label="item.name"
            @click="handleSocialClick(item.name)"
          >
            <template #icon>
              <component :is="item.icon"/>
            </template>
          </n-button>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import type {Component} from 'vue'
import {FacebookSquare, Telegram, InstagramSquare, TwitterSquare, Weixin, Weibo, Qq} from '@vicons/fa'
import {$t} from '@/locales'
import {navigateTo} from '@/router'

type FooterLinkKey =
  | 'about_us'
  | 'contact_us'
  | 'non_responsibility'
  | 'privacy_agreement'
  | 'terms_of_service'

interface FooterLinkItem {
  key: FooterLinkKey
  labelKey: `ui.button.${FooterLinkKey}`
}

interface SocialItem {
  key: 'twitter' | 'facebook' | 'instagram' | 'telegram' | 'wechat' | 'weibo' | 'qq'
  name: 'Twitter' | 'Facebook' | 'Instagram' | 'Telegram' | 'WeChat' | 'Weibo' | 'QQ'
  icon: Component
}

const footerLinks: FooterLinkItem[] = [
  {key: 'about_us', labelKey: 'ui.button.about_us'},
  {key: 'contact_us', labelKey: 'ui.button.contact_us'},
  {key: 'non_responsibility', labelKey: 'ui.button.non_responsibility'},
  {key: 'privacy_agreement', labelKey: 'ui.button.privacy_agreement'},
  {key: 'terms_of_service', labelKey: 'ui.button.terms_of_service'},
]

const footerRouteMap: Record<FooterLinkKey, string> = {
  about_us: '/about',
  contact_us: '/contact',
  non_responsibility: '/disclaimer',
  privacy_agreement: '/privacy',
  terms_of_service: '/terms',
}

const socialLinks: SocialItem[] = [
  {key: 'twitter', name: 'Twitter', icon: TwitterSquare},
  {key: 'facebook', name: 'Facebook', icon: FacebookSquare},
  {key: 'instagram', name: 'Instagram', icon: InstagramSquare},
  {key: 'telegram', name: 'Telegram', icon: Telegram},
  {key: 'wechat', name: 'WeChat', icon: Weixin},
  {key: 'weibo', name: 'Weibo', icon: Weibo},
  {key: 'qq', name: 'QQ', icon: Qq},
]

function handleFooterLinkClick(key: FooterLinkKey) {
  navigateTo(footerRouteMap[key])
}

function handleSocialClick(name: SocialItem['name']) {
  console.log(name)
}
</script>

<style scoped lang="less">
.footer-outer {
  width: 100%;
  background: var(--color-surface);
  display: flex;
  justify-content: center;
}

.footer-container {
  min-height: 72px;
  padding: var(--space-4) 0;
  color: var(--color-text-secondary);
  border-top: 1px solid var(--color-border);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: var(--space-4);
}

.footer-links {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 4px;
}

.footer-meta {
  display: flex;
  align-items: center;
  gap: var(--space-3);
  flex-shrink: 0;
}

.footer-link {
  --n-text-color-text: var(--color-text-secondary);
  --n-text-color-text-hover: var(--color-text-primary);
  --n-text-color-text-pressed: var(--color-text-primary);
  padding: 0 4px;
}

.footer-link:deep(.n-button__content) {
  color: var(--color-text-secondary) !important;
}

.footer-link:hover:deep(.n-button__content) {
  color: var(--color-text-primary) !important;
}

.social-list {
  display: flex;
  align-items: center;
  gap: 2px;
}

.social-btn {
  font-size: 24px;
  color: var(--color-text-secondary) !important;
  transition: all 0.2s ease;
  --n-text-color-text: var(--color-text-secondary);
  --n-text-color-text-hover: var(--color-brand);
  --n-text-color-text-pressed: var(--color-brand);
}

.social-btn:hover {
  transform: translateY(-1px);
}

.copyright {
  color: var(--color-text-secondary);
  font-size: 14px;
  white-space: nowrap;
}

.meta-divider:deep(.n-divider) {
  background-color: var(--color-border);
}

@media (max-width: 960px) {
  .footer-container {
    flex-direction: column;
    align-items: flex-start;
    gap: var(--space-3);
    padding: var(--space-4) 0 var(--space-5);
  }

  .footer-meta {
    width: 100%;
    justify-content: space-between;
  }

  .meta-divider {
    display: none;
  }
}
</style>

// frontend/app/react/src/components/layout/Footer.tsx
'use client';

import React from 'react';
import {Button} from '@/components/ui/button';
import {Separator} from '@/components/ui/separator';
import {Icon} from '@iconify/react';
import {useTranslations} from 'next-intl';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';

type FooterLinkKey =
    | 'about_us'
    | 'contact_us'
    | 'non_responsibility'
    | 'privacy_agreement'
    | 'terms_of_service';

interface FooterLinkItem {
    key: FooterLinkKey;
    labelKey: string;
}

interface SocialItem {
    key: 'twitter' | 'facebook' | 'instagram' | 'telegram' | 'wechat' | 'weibo' | 'qq';
    name: string;
    icon: string;
}

export default function Footer() {
    const t = useTranslations('ui');
    const router = useI18nRouter();

    const footerLinks: FooterLinkItem[] = [
        {key: 'about_us', labelKey: 'button.about_us'},
        {key: 'contact_us', labelKey: 'button.contact_us'},
        {key: 'non_responsibility', labelKey: 'button.non_responsibility'},
        {key: 'privacy_agreement', labelKey: 'button.privacy_agreement'},
        {key: 'terms_of_service', labelKey: 'button.terms_of_service'},
    ];

    const footerRouteMap: Record<FooterLinkKey, string> = {
        about_us: '/about',
        contact_us: '/contact',
        non_responsibility: '/disclaimer',
        privacy_agreement: '/privacy',
        terms_of_service: '/terms',
    };

    const socialLinks: SocialItem[] = [
        {key: 'twitter', name: 'Twitter', icon: 'fa:twitter'},
        {key: 'facebook', name: 'Facebook', icon: 'fa:facebook'},
        {key: 'instagram', name: 'Instagram', icon: 'fa:instagram'},
        {key: 'telegram', name: 'Telegram', icon: 'fa:telegram'},
        {key: 'wechat', name: 'WeChat', icon: 'fa:wechat'},
        {key: 'weibo', name: 'Weibo', icon: 'fa:weibo'},
        {key: 'qq', name: 'QQ', icon: 'fa:qq'},
    ];

    const handleFooterLinkClick = (key: FooterLinkKey) => {
        router.push(footerRouteMap[key]);
    };

    const handleSocialClick = (name: string) => {
        console.log(name);
    };

    return (
        <footer className="w-full bg-card flex justify-center">
            <div className="flex w-full max-w-[1200px] items-center justify-between gap-4 border-t border-border px-6 py-4 text-muted-foreground min-h-[72px] max-md:flex-col max-md:items-start max-md:gap-3 max-md:py-4 max-md:pb-5">
                <nav className="flex flex-wrap items-center gap-1" aria-label="Footer links">
                    {footerLinks.map(link => (
                        <Button
                            key={link.key}
                            variant="ghost"
                            className="px-1 text-muted-foreground hover:text-foreground transition-colors"
                            onClick={() => handleFooterLinkClick(link.key)}
                        >
                            {t(link.labelKey)}
                        </Button>
                    ))}
                </nav>

                <div className="flex shrink-0 items-center gap-3 max-md:w-full max-md:justify-between">
                    <span className="text-sm whitespace-nowrap">
                        {t('copyright')}
                    </span>
                    <Separator orientation="vertical" className="h-3.5 w-px bg-border max-md:hidden"/>
                    <div className="flex items-center gap-1" aria-label="Social links">
                        {socialLinks.map(social => (
                            <Button
                                key={social.key}
                                variant="ghost"
                                size="icon"
                                className="text-2xl text-muted-foreground hover:text-primary transition-all hover:-translate-y-0.5"
                                aria-label={social.name}
                                onClick={() => handleSocialClick(social.name)}
                            >
                                <Icon icon={social.icon}/>
                            </Button>
                        ))}
                    </div>
                </div>
            </div>
        </footer>
    );
}
