// frontend/app/vue/app/components/layout/Header.vue
<script setup lang="ts">
import { XIcon } from '@/plugins/xicon'
import { usePreferences } from '@/core/preferences/use-preferences'
import { useAccessStore } from '@/stores/modules/core/access.state'
import { useAuthStore } from '@/stores/modules/app/auth.state'

const { t } = useI18n()
const { themePreferences: themePref, setTheme: setThemeMode } = usePreferences()
const currentMode = computed(() => themePref.value.mode)

const localePath = useLocalePath()
const switchLocalePath = useSwitchLocalePath()

const changeLocale = (code: 'zh-CN' | 'en-US') => {
  navigateTo(switchLocalePath(code))
}
const accessStore = useAccessStore()
const authStore = useAuthStore()

const isLogin = computed(() => {
  const token = accessStore.accessToken
  return !!token?.value && !accessStore.loginExpired
})

const handleClickLogo = () => navigateTo(localePath('/'))
const handleClickSettings = () => navigateTo(localePath('/settings'))
const handleClickUserHomepage = () => navigateTo(localePath('/user'))
const handleClickLogin = () => navigateTo(localePath('/login'))
const handleClickRegister = () => navigateTo(localePath('/register'))
const handleClickLogout = async () => {
  if (isLogin.value) await authStore.logout()
}
</script>

<template>
  <header class="fixed top-0 left-0 right-0 z-1000 flex justify-center bg-background/80 backdrop-blur-md border-b border-border/50 dark:border-border/30 dark:bg-background/60">
    <div class="flex h-(--layout-header-height) w-full max-w-300 items-center gap-6 px-4 max-md:gap-3 max-md:px-3">
      <!-- Logo -->
      <button
        type="button"
        class="flex shrink-0 items-center gap-2 rounded-lg p-1 transition-colors hover:bg-primary/10"
        aria-label="Go to homepage"
        @click="handleClickLogo"
      >
        <img src="/logo.png" alt="Logo" width="36" height="36" class="h-9 w-9 shrink-0 max-md:h-8 max-md:w-8" />
        <span class="text-lg font-bold text-primary whitespace-nowrap max-md:hidden">
          {{ t('app.title') }}
        </span>
      </button>

      <!-- 桌面端导航区 -->
      <div class="min-w-0 flex-1 max-md:hidden">
        <LayoutTopNavbar />
      </div>

      <!-- 桌面端功能按钮区 -->
      <div class="flex shrink-0 items-center gap-1 max-md:hidden">
        <!-- 用户菜单 -->
        <UiDropdownMenu :modal="false">
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="User menu">
              <XIcon icon="lucide:user" width="16" height="16" />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <template v-if="isLogin">
              <UiDropdownMenuItem @click="handleClickUserHomepage">
                <XIcon icon="lucide:home" width="16" height="16" />
                {{ t('menu.homepage') }}
              </UiDropdownMenuItem>
              <UiDropdownMenuItem @click="handleClickSettings">
                <XIcon icon="lucide:user" width="16" height="16" />
                {{ t('menu.my_profile') }}
              </UiDropdownMenuItem>
              <UiDropdownMenuSeparator />
              <UiDropdownMenuItem class="text-destructive" @click="handleClickLogout">
                <XIcon icon="lucide:log-out" width="16" height="16" />
                {{ t('menu.logout') }}
              </UiDropdownMenuItem>
            </template>
            <template v-else>
              <UiDropdownMenuItem @click="handleClickLogin">
                <XIcon icon="lucide:user" width="16" height="16" />
                {{ t('navbar.user.login') }}
              </UiDropdownMenuItem>
              <UiDropdownMenuItem @click="handleClickRegister">
                <XIcon icon="lucide:user" width="16" height="16" />
                {{ t('navbar.user.register') }}
              </UiDropdownMenuItem>
            </template>
          </UiDropdownMenuContent>
        </UiDropdownMenu>

        <!-- 语言菜单 -->
        <UiDropdownMenu :modal="false">
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="Language">
              <XIcon icon="lucide:globe" width="16" height="16" />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <UiDropdownMenuItem @click="changeLocale('zh-CN')">
              简体中文
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="changeLocale('en-US')">
              English
            </UiDropdownMenuItem>
          </UiDropdownMenuContent>
        </UiDropdownMenu>

        <!-- 主题菜单 -->
        <UiDropdownMenu :modal="false">
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="Toggle theme">
              <XIcon                 :icon="currentMode === 'dark' ? 'lucide:moon' : currentMode === 'light' ? 'lucide:sun' : 'lucide:monitor'"
                width="16" height="16"
                class="theme-icon-animate"
              />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <UiDropdownMenuItem @click="setThemeMode('dark')">
              <XIcon icon="lucide:moon" width="16" height="16" />
              {{ t('navbar.theme.dark') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('light')">
              <XIcon icon="lucide:sun" width="16" height="16" />
              {{ t('navbar.theme.light') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('auto')">
              <XIcon icon="lucide:monitor" width="16" height="16" />
              {{ t('navbar.theme.system') }}
            </UiDropdownMenuItem>
          </UiDropdownMenuContent>
        </UiDropdownMenu>
      </div>

      <!-- 手机端：主题切换 + 汉堡选单 -->
      <div class="flex shrink-0 items-center gap-1 md:hidden">
        <UiDropdownMenu :modal="false">
          <UiDropdownMenuTrigger as-child>
            <UiButton variant="ghost" size="icon" aria-label="Toggle theme">
              <XIcon                 :icon="currentMode === 'dark' ? 'lucide:moon' : currentMode === 'light' ? 'lucide:sun' : 'lucide:monitor'"
                width="16" height="16"
                class="theme-icon-animate"
              />
            </UiButton>
          </UiDropdownMenuTrigger>
          <UiDropdownMenuContent align="end">
            <UiDropdownMenuItem @click="setThemeMode('dark')">
              <XIcon icon="lucide:moon" width="16" height="16" />
              {{ t('navbar.theme.dark') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('light')">
              <XIcon icon="lucide:sun" width="16" height="16" />
              {{ t('navbar.theme.light') }}
            </UiDropdownMenuItem>
            <UiDropdownMenuItem @click="setThemeMode('auto')">
              <XIcon icon="lucide:monitor" width="16" height="16" />
              {{ t('navbar.theme.system') }}
            </UiDropdownMenuItem>
          </UiDropdownMenuContent>
        </UiDropdownMenu>

        <!-- 汉堡选单 -->
        <LayoutMobileNav />
      </div>
    </div>
  </header>
</template>

// frontend/app/react/src/components/layout/Header.tsx
'use client';

import React, {useState, useEffect} from 'react';
import {useTranslations} from 'next-intl';
import {User, Home, LogOut, Globe, Moon, Sun, Monitor} from 'lucide-react';

import {Button} from '@/components/ui/button';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

import {useI18n} from '@/i18n';
import {useI18nRouter} from '@/i18n/helpers/useI18nRouter';
import {usePreferences} from '@/core/preferences';

import TopNavbar from './TopNavbar';
import MobileNav from './MobileNav';

import {useAccessStore} from '@/store/core/access/store';
import {useAuth} from '@/api/hooks/auth';

export default function Header() {
    const t = useTranslations('navbar');
    const appT = useTranslations('app');
    const menuT = useTranslations('menu');
    const brandTitle = appT('title');

    const {theme: themePref, setThemeMode} = usePreferences();
    const currentMode = themePref.mode;
    const {changeLocale} = useI18n();
    const router = useI18nRouter();
    const accessStore = useAccessStore();
    const auth = useAuth();

    const accessToken = accessStore.accessToken;
    const isLogin = !!accessToken && !accessStore.loginExpired;

    const handleClickLogo = () => router.push('/');
    const handleClickSettings = () => router.push('/settings');
    const handleClickUserHomepage = () => router.push('/user');
    const handleClickLogin = () => router.push('/login');
    const handleClickRegister = () => router.push('/register');
    const handleClickLogout = async () => {
        if (isLogin) await auth.logout();
    };

    // SSR 兼容
    const [mounted, setMounted] = useState(false);
    useEffect(() => {
        // eslint-disable-next-line react-hooks/set-state-in-effect
        setMounted(true);
    }, []);

    const themeIcon = (() => {
        const animClass = 'h-4 w-4 theme-icon-animate';
        if (!mounted) return <Monitor key="monitor" className={animClass}/>;
        if (currentMode === 'dark') return <Moon key="moon" className={animClass}/>;
        if (currentMode === 'light') return <Sun key="sun" className={animClass}/>;
        return <Monitor key="monitor" className={animClass}/>;
    })();

    return (
        <header className="fixed top-0 left-0 right-0 z-1000 flex justify-center bg-background/80 backdrop-blur-md border-b border-border/50 dark:border-border/30 dark:bg-background/60">
            <div className="flex h-(--layout-header-height) w-full max-w-300 items-center gap-6 px-4 max-md:gap-3 max-md:px-3">
                {/* Logo */}
                <button
                    type="button"
                    onClick={handleClickLogo}
                    className="flex shrink-0 items-center gap-2 rounded-lg p-1 transition-colors hover:bg-primary/10"
                    aria-label="Go to homepage"
                >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                        src="/logo.png"
                        alt="Logo"
                        width={36}
                        height={36}
                        className="h-9 w-9 shrink-0 max-md:h-8 max-md:w-8"
                    />
                    <span className="text-lg font-bold text-primary whitespace-nowrap max-md:hidden">
                        {brandTitle}
                    </span>
                </button>

                {/* 桌面端导航区 */}
                <div className="min-w-0 flex-1 max-md:hidden">
                    <TopNavbar/>
                </div>

                {/* 桌面端功能按钮区 */}
                <div className="flex shrink-0 items-center gap-1 max-md:hidden">
                    {/* 用户菜单 */}
                    <DropdownMenu modal={false}>
                        <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" aria-label="User menu">
                                <User className="h-4 w-4"/>
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                            {isLogin ? (
                                <>
                                    <DropdownMenuItem onClick={handleClickUserHomepage}>
                                        <Home className="h-4 w-4"/>
                                        {menuT('homepage')}
                                    </DropdownMenuItem>
                                    <DropdownMenuItem onClick={handleClickSettings}>
                                        <User className="h-4 w-4"/>
                                        {menuT('my_profile')}
                                    </DropdownMenuItem>
                                    <DropdownMenuSeparator/>
                                    <DropdownMenuItem
                                        onClick={handleClickLogout}
                                        className="text-destructive"
                                    >
                                        <LogOut className="h-4 w-4"/>
                                        {menuT('logout')}
                                    </DropdownMenuItem>
                                </>
                            ) : (
                                <>
                                    <DropdownMenuItem onClick={handleClickLogin}>
                                        <User className="h-4 w-4"/>
                                        {t('user.login')}
                                    </DropdownMenuItem>
                                    <DropdownMenuItem onClick={handleClickRegister}>
                                        <User className="h-4 w-4"/>
                                        {t('user.register')}
                                    </DropdownMenuItem>
                                </>
                            )}
                        </DropdownMenuContent>
                    </DropdownMenu>

                    {/* 语言菜单 */}
                    <DropdownMenu modal={false}>
                        <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" aria-label="Language">
                                <Globe className="h-4 w-4"/>
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                            <DropdownMenuItem onClick={() => changeLocale('zh-CN')}>
                                简体中文
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => changeLocale('en-US')}>
                                English
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>

                    {/* 主题菜单 */}
                    <DropdownMenu modal={false}>
                        <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" aria-label="Toggle theme">
                                {themeIcon}
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                            <DropdownMenuItem onClick={() => setThemeMode('dark')}>
                                <Moon className="h-4 w-4"/>
                                {t('theme.dark')}
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => setThemeMode('light')}>
                                <Sun className="h-4 w-4"/>
                                {t('theme.light')}
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => setThemeMode('auto')}>
                                <Monitor className="h-4 w-4"/>
                                {t('theme.system')}
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>
                </div>

                {/* 手机端：主题切换 + 汉堡选单 */}
                <div className="flex shrink-0 items-center gap-1 md:hidden">
                    <DropdownMenu modal={false}>
                        <DropdownMenuTrigger asChild>
                            <Button variant="ghost" size="icon" aria-label="Toggle theme">
                                {themeIcon}
                            </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                            <DropdownMenuItem onClick={() => setThemeMode('dark')}>
                                <Moon className="h-4 w-4"/>
                                {t('theme.dark')}
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => setThemeMode('light')}>
                                <Sun className="h-4 w-4"/>
                                {t('theme.light')}
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => setThemeMode('auto')}>
                                <Monitor className="h-4 w-4"/>
                                {t('theme.system')}
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>

                    {/* 汉堡选单 */}
                    <MobileNav/>
                </div>
            </div>
        </header>
    );
}
